// Abbréviations médicales courantes — Dictionnaire rapide
const ABBREVIATIONS = [
  { abbr: 'ADL', complet: 'Activities of Daily Living', fr: 'Activités de la Vie Domestique' },
  { abbr: 'IADL', complet: 'Instrumental ADL', fr: 'Activités instrumentales' },
  { abbr: 'MMS', complet: 'Mini Mental State', fr: 'Test cognitif (30 points)' },
  { abbr: 'GDS', complet: 'Geriatric Depression Scale', fr: 'Échelle dépression gériatrique' },
  { abbr: 'MNA', complet: 'Mini Nutritional Assessment', fr: 'Évaluation nutritionnelle' },
  { abbr: 'CAM', complet: 'Confusion Assessment Method', fr: 'Diagnostic confusion aiguë' },
  { abbr: 'ECPA', complet: 'Échelle Comportementale Personne Âgée', fr: 'Douleur non communicant' },
  { abbr: 'DFG', complet: 'Débit de Filtration Glomérulaire', fr: 'Fonction rénale' },
  { abbr: 'EVA', complet: 'Échelle Visuelle Analogique', fr: 'Douleur 0-10' },
  { abbr: 'DEXA', complet: 'Dual Energy X-ray Absorptiometry', fr: 'Densitométrie osseuse' },
  { abbr: 'FRAX', complet: 'Fracture Risk Assessment', fr: 'Risque fracturaire 10 ans' },
  { abbr: 'HTA', complet: 'Hypertension Artérielle', fr: 'PAS ≥ 140 ou PAD ≥ 90' },
  { abbr: 'BPCO', complet: 'Broncho-Pneumopathie Chronique Obstructive', fr: 'Maladie pulmonaire chronique' },
  { abbr: 'DM2', complet: 'Diabète de type 2', fr: 'Diabète non insulino-dépendant' },
  { abbr: 'AVC', complet: 'Accident Vasculaire Cérébral', fr: 'Stroke' },
  { abbr: 'EP', complet: 'Embolie Pulmonaire', fr: 'Caillot dans l\'artère pulmonaire' },
  { abbr: 'TVP', complet: 'Thrombose Veineuse Profonde', fr: 'Caillot dans les veines profondes' },
  { abbr: 'FA', complet: 'Fibrillation Atriale', fr: 'Arythmie cardiaque la plus fréquente' },
  { abbr: 'IC', complet: 'Insuffisance Cardiaque', fr: 'Cœur ne pompe pas assez' },
  { abbr: 'IRA', complet: 'Insuffisance Rénale Aiguë', fr: 'Rein ne filtre plus' },
  { abbr: 'ITU', complet: 'Infection des Voies Urinaires', fr: 'Cystite, pyélonéphrite' },
  { abbr: 'DMLA', complet: 'Dégénérescence Maculaire Liée à l\'Âge', fr: 'Perte vision centrale' },
  { abbr: 'DLB', complet: 'Dementia with Lewy Bodies', fr: 'Démence à corps de Lewy' },
  { abbr: 'EHPAD', complet: 'Établissement Hébergement Personnes Âgées Dépendantes', fr: 'Maison de retraite médicalisée' },
  { abbr: 'SSR', complet: 'Suite de Rétablissement et de Réadaptation', fr: 'Rééducation post-hospitalisation' },
  { abbr: 'HAD', complet: 'Hospitalisation A Domicile', fr: 'Soins hospitaliers à domicile' },
  { abbr: 'APA', complet: 'Allocation Personnalisée d\'Autonomie', fr: 'Aide financière perte autonomie' },
  { abbr: 'PEG', complet: 'Percutaneous Endoscopic Gastrostomy', fr: 'Gastrostomie (nutrition entérale)' },
  { abbr: 'SNG', complet: 'Sonde Naso-Gastrique', fr: 'Tube nutrition par le nez' },
  { abbr: 'TVT', complet: 'Tension-free Vaginal Tape', fr: 'Bandelette incontinence effort' },
  { abbr: 'CI', complet: 'Contre-Indication', fr: 'Ne pas prescrire' },
  { abbr: 'SA', complet: 'Effet Secondaire', fr: 'Effet indésirable' },
  { abbr: 'BZD', complet: 'Benzodiazépines', fr: 'Anxiolytiques (diazépam, lorazépam)' },
  { abbr: 'ISRS', complet: 'Inhibiteur Sélectif Recapture Sérotonine', fr: 'Antidépresseur (sertraline)' },
  { abbr: 'IRSN', complet: 'Inhibiteur Recapture Sérotonine Noradrénaline', fr: 'Antidépresseur (venlafaxine)' },
  { abbr: 'AINS', complet: 'Anti-Inflammatoire Non Stéroïdien', fr: 'Ibuprofène, diclofénac' },
  { abbr: 'IEC', complet: 'Inhibiteur Enzyme de Conversion', fr: 'Antihypertenseur' },
  { abbr: 'ARA2', complet: 'Antagoniste Récepteur Angiotensine 2', fr: 'Antihypertenseur (losartan)' },
  { abbr: 'INR', complet: 'International Normalized Ratio', fr: 'Mesure coagulation (warfarine)' },
  { abbr: 'NFS', complet: 'Numération Formule Sanguine', fr: 'Bilan sanguin de base' },
  { abbr: 'CRP', complet: 'Protéine C Réactive', fr: 'Marqueur inflammation' },
  { abbr: 'ECBU', complet: 'Examen Cytobactériologique des Urines', fr: 'Analyse urinaire' },
  { abbr: 'ECG', complet: 'ÉlectroCardioGramme', fr: 'Activité électrique du cœur' },
  { abbr: 'IRM', complet: 'Imagerie par Résonance Magnétique', fr: 'Scanner sans radiation' },
  { abbr: 'TDM', complet: 'Tomodensitométrie', fr: 'Scanner avec radiation' },
  { abbr: 'Rx', complet: 'Radiographie', fr: 'Radio standard' }
];
