// Conduites à tenir — Situations cliniques fréquentes
const CONDUITES_A_TENIR = [
  { id: 'ctt-1', situation: 'Patient qui refuse le traitement', reponse: '1. Comprendre la raison du refus (croyance, peur, méconnaissance). 2. Expliquer les bénéfices et risques. 3. Proposer des alternatives. 4. Respecter le droit de refus (autonomie). 5. Documenter le refus dans le dossier. 6. Réévaluer régulièrement.' },
  { id: 'ctt-2', situation: 'Patient agité qui arrache ses perfusions', reponse: '1. Évaluer la douleur (ECPA). 2. Rechercher cause (infection, rétention, constipation). 3. Réorientation calme. 4. Si nécessaire: halopéridol 0.5mg. 5. Pas de contention. 6. Préserver les voies veineuses si possible (serre-bande).' },
  { id: 'ctt-3', situation: 'Famille qui demande "tout faire"', reponse: '1. Écouter les préoccupations. 2. Expliquer la situation médicale clairement. 3. Distinguer obstination déraisonnable vs soins appropriés. 4. Proposer un projet de soins partagé. 5. Impliquer la personne de confiance. 6. Si conflit: réunion pluridisciplinaire + avis éthique.' },
  { id: 'ctt-4', situation: 'Patient qui tombe en répétition', reponse: '1. Chaque chute = réévaluation complète. 2. Révision médicamenteuse systématique. 3. Bilan orthostatique. 4. Évaluation Tinetti. 5. Correction visuelle. 6. Adaptation domicile. 7. Rééducation équilibre. 8. Vit D 800UI. 9. Si malgré tout: protection (matelas, casque).' },
  { id: 'ctt-5', situation: 'Confusion post-opératoire', reponse: '1. CAM (confirmer delirium). 2. Rechercher cause (infection, douleur, médicaments, métabolique). 3. Bilan: T°, NFS, CRP, iono, ECBU, gaz du sang. 4. Traitement cause. 5. Si agitation: halopéridol 0.5mg. 6. Pas de contention. 7. Réorientation. 8. Présence familiale.' },
  { id: 'ctt-6', situation: 'Dénutrition sévère', reponse: '1. MNA (<17 = dénutrition). 2. Rechercher cause (dentition, dépression, isolement, cancer). 3. Enrichissement alimentaire. 4. CNO x3/j. 5. Si échec: nutrition entérale (SNG → PEG). 6. Protéines 1.2-1.5g/kg/j. 7. Vit D + B12 si carence. 8. Soins dentaires.' },
  { id: 'ctt-7', situation: 'Douleur chronique mal contrôlée', reponse: '1. Évaluer (EVA/ECPA). 2. Identifier le type (nociceptive vs neuropathique). 3. Paracétamol 1g x3/j (1ère ligne). 4. Si neuropathique: gabapentine/pregabaline. 5. Si insuffisant: tramadol. 6. Si toujours insuffisant: morphine. 7. Non-pharmacologique: kiné, TENS, chaleur. 8. Réévaluation mensuelle.' },
  { id: 'ctt-8', situation: 'Incontinence urinaire récente', reponse: '1. Identifier le type (effort, urgence, mixte, fonctionnelle). 2. Calendrier mictionnel. 3. ECBU (infection ?). 4. Résidu post-mictionnel. 5. Révision médicamenteuse (diurétiques, anticholinergiques). 6. Si effort: rééducation périnéale. 7. Si urgence: anticholinergiques (si pas de confusion). 8. Si fonctionnelle: aide toilettes, horaires.' },
  { id: 'ctt-9', situation: 'Fin de vie — accompagnement', reponse: '1. Projet de soins palliatifs. 2. Douleur: morphine SC. 3. Dyspnée: morphine + O2. 4. Agitation: midazolam. 5. Soins de bouche toutes les 2h. 6. Hydratation cutanée. 7. Pas de nutrition artificielle. 8. Accompagnement psychosocial (famille, aumônerie). 9. Sédation si souffrance réfractaire.' },
  { id: 'ctt-10', situation: 'Polymédication excessive', reponse: '1. Lister TOUS les médicaments (y compris OTC). 2. Identifier les Beers. 3. Vérifier les interactions. 4. Déprescrire un médicament à la fois. 5. Sevrage progressif. 6. Surveiller les effets de sevrage. 7. Simplifier le schéma (1 prise/j). 8. Pilulier. 9. Éducation patient. 10. Réévaluation trimestrielle.' }
];
