// Examens complémentaires — Guide de prescription rapide
const EXAMENS_GUIDE = [
  { id: 'ex-1', nom: 'NFS (NFS)', indication: 'Tout patient âgé admis', parametres: ['Hb (anémie <12/<13)', 'Leucocytes (infection >10, immunodépression <4)', 'Plaquettes (thrombopénie <150)', 'VHS (<âge/2)', 'CRP (infection >50)'], interpretation: 'Anémie = carence, inflammation, insuffisance médullaire. Leucocytose = infection. Leucopénie = médicaments, viral.' },
  { id: 'ex-2', nom: 'Ionogramme', indication: 'Confusion, déshydratation, diurétiques, IEC', parametres: ['Na (135-145)', 'K (3.5-5.0)', 'Cl (98-106)', 'HCO3 (22-28)'], interpretation: 'Hyponatrémie = SIADH, diurétiques. Hyperkaliémie = IRA, IEC, K-sparing. Acidose = IRA, lactique.' },
  { id: 'ex-3', nom: 'Rénal', indication: 'Tout patient >65 ans', parametres: ['Créatinine (DFG CKD-EPI)', 'Urée (2.5-7.5)', 'DFG (>90 normal)'], interpretation: 'DFG <60 = adapter doses. DFG <30 = éviter certains médicaments. DFG <15 = avis néphro.' },
  { id: 'ex-4', nom: 'Hépatique', indication: 'Ictère, médicaments hépatotoxiques, dénutrition', parametres: ['ALAT (<45)', 'ASAT (<35)', 'GGT (<55)', 'PAL (<130)', 'Bilirubine (<17)', 'Albumine (35-50)'], interpretation: 'Albumine <35 = dénutrition/inflammation. Transaminases ↑ = hépatite, médicaments. GGT ↑ = alcool.' },
  { id: 'ex-5', nom: 'Thyroïde', indication: 'Confusion, dépression, HTA, troubles du rythme', parametres: ['TSH (0.4-4.0)', 'L-T4 libre (12-22)'], interpretation: 'TSH ↑ = hypothyroïdie (fatigue, confusion, HTA). TSH ↓ = hyperthyroïdie (tachycardie, amaigrissement, FA).' },
  { id: 'ex-6', nom: 'ECG', indication: 'Douleur thoracique, syncope, trouble du rythme, médicaments QT', parametres: ['Rythme (sinusal, FA)', 'FC (60-100)', 'QT (<450ms)', 'ST (dépression/élévation)', 'Hypertrophie VG'], interpretation: 'FA = anticoagulation. QT long = arrêter médicament. ST+ = IDM. BBG = hypertrophie.' },
  { id: 'ex-7', nom: 'Rx thoracique', indication: 'Dyspnée, fièvre, toux, chute', parametres: ['Opacité (pneumopathie)', 'Cardiomégalie (IC)', 'Épanchement pleural', 'Médiastin'], interpretation: 'Opacité = pneumopathie. Cardiomégalie = IC. Épanchement = cancer, IC, infection.' },
  { id: 'ex-8', nom: 'ECBU', indication: 'Fièvre, confusion, pollakiurie, brûlures mictionnelles', parametres: ['Leucocytes (>10⁴/mL = infection)', 'Nitrites (bactéries Gram-)', 'Hématurie', 'Antibiogramme'], interpretation: 'ECBU + ≠ infection urinaire toujours (colonisation fréquente). Traiter si symptômes + ECBU +.' },
  { id: 'ex-9', nom: 'Gaz du sang', indication: 'Dyspnée, confusion, acidose suspectée', parametres: ['pH (7.35-7.45)', 'PaCO2 (35-45)', 'PaO2 (80-100)', 'HCO3 (22-28)', 'Lactates (<2)'], interpretation: 'Acidose métabolique = lactique, rénale, cétose. Alcalose = hyperventilation, vomissements. Lactates >2 = hypoperfusion.' },
  { id: 'ex-10', nom: 'HbA1c', indication: 'Diabète connu ou suspecté', parametres: ['HbA1c (<7% jeune, 7-8% sujet âgé autonome, <8.5% fragile)'], interpretation: 'Ne pas viser <7% chez >75 ans (hypoglycémie = chutes, confusion). Fructosamine si hémoglobinopathie.' }
];
