const FLASHCARDS_A = [
  // ── Ch1 : Vieillissement ──
  { id: 101, chapter: 'ch1', rang: 'A', question: 'Définition du vieillissement ?', answer: 'Ensemble des processus physiologiques modifiant la structure et les fonctions des organes à partir de l\'âge mûr. Facteurs : génétiques + environnementaux + stochastiques. Processus lent, jamais responsable seul d\'une symptomatologie aiguë.', tags: ['vieillissement', 'définition'] },
  { id: 102, chapter: 'ch1', rang: 'A', question: 'Les 5 critères de Fried pour la fragilité ?', answer: '1. Perte de poids involontaire (≥4,5 kg/an ou ≥5%). 2. Fatigue (échelle de fatigue). 3. Réduction des activités physiques. 4. Vitesse de marche lente (<0,8 m/s). 5. Faible force de préhension (grip strength). ≥ 3 critères = fragile.', tags: ['Fried', 'fragilité'] },
  { id: 103, chapter: 'ch1', rang: 'A', question: 'Seuil de vitesse de marche pour le diagnostic de fragilité ?', answer: '< 0,8 m/s (soit < 4,8 s sur 4 m). Mesuré par le test de marche de 4 mètres.', tags: ['marche', 'fragilité', 'vitesse'] },
  { id: 104, chapter: 'ch1', rang: 'A', question: 'Définition de la sarcopénie ?', answer: 'Perte progressive et généralisée de la masse musculaire squelettique et de la force liée à l\'âge. Critères EWGSOP2 : masse musculaire basse + force réduite OU performance physique réduite. Prévalence : 10-27% après 60 ans.', tags: ['sarcopénie', 'muscle', 'vieillissement'] },
  { id: 105, chapter: 'ch1', rang: 'A', question: 'Quels sont les 3 mécanismes cellulaires du vieillissement ?', answer: '1. Raccourcissement des télomères (limite de Hayflick). 2. Stress oxydatif (radicaux libres, déclin mitochondries). 3. Sénescence cellulaire (arrêt de prolifération, SASP = phénotype sécrétoire).', tags: ['télomères', 'stress oxydatif', 'sénescence'] },
  { id: 106, chapter: 'ch1', rang: 'A', question: 'Définition de la fragilité selon le modèle de Rockwood ?', answer: 'Modèle cumulative de déficits : la fragilité est proportionnelle au nombre de déficits accumulés (comorbidités, incapacités, troubles). Score de Rockwood = ratio déficits/déficits possibles. Plus le score est élevé, plus le patient est fragile.', tags: ['Rockwood', 'fragilité', 'déficits'] },
  { id: 107, chapter: 'ch1', rang: 'B', question: 'Espérance de vie en France en 2020 ?', answer: 'Femmes : 85,2 ans. Hommes : 79,2 ans. Gain moyen : +1,3 an tous les 10 ans. Espérance de vie en bonne santé : 64,1 ans (femmes), 62,7 ans (hommes).', tags: ['espérance de vie', 'démographie'] },
  { id: 108, chapter: 'ch1', rang: 'B', question: 'Quelle est la différence entre vieillissement physiologique et pathologique ?', answer: 'Physiologique : déclin progressif des fonctions sans maladie, adaptation, réserve fonctionnelle diminuée mais suffisante. Pathologique : maladies chroniques accélérant le déclin, perte d\'autonomie, fragilité. Le gériatre doit distinguer les deux pour ne pas médicaliser le vieillissement normal.', tags: ['vieillissement', 'physiologique', 'pathologique'] },
  { id: 109, chapter: 'ch1', rang: 'A', question: 'Qu\'est-ce que le modèle de Bouchon en gériatrie ?', answer: 'Modèle des 3 facteurs : F1 = vieillissement normal (diminution des réserves), F2 = maladies chroniques (réduisent encore les réserves), F3 = facteur précipitant (événement aigu qui fait basculer). Priorité : traiter le F3 (réversible) en premier.', tags: ['Bouchon', 'modèle', 'raisonnement'] },

  // ── Ch2 : Raisonnement gériatrique ──
  { id: 110, chapter: 'ch2', rang: 'A', question: 'Définition de la cascade gériatrique ?', answer: 'Déséquilibre en série d\'organes et de fonctions après un facteur déclenchant. Cercle vicieux : un dysfonctionnement entraîne un autre. Spécifique au sujet âgé polymorbide.', tags: ['cascade', 'cercle vicieux'] },
  { id: 111, chapter: 'ch2', rang: 'A', question: 'Définition de la polypathologie ?', answer: 'Présence de ≥ 5 maladies chroniques chez le même patient. Fréquente chez la personne âgée. Complexifie la prise en charge. Augmente le risque iatrogénique et les interactions médicamenteuses.', tags: ['polypathologie', 'multimorbidité'] },
  { id: 112, chapter: 'ch2', rang: 'A', question: 'Définition de la polymédication ?', answer: 'Prise de ≥ 5 molécules différentes par jour. Facteur de risque iatrogénique majeur. Nécessite régulière revue médicamenteuse. Critères Beers et STOPP/START pour évaluer la pertinence.', tags: ['polymédication', 'iatrogénie'] },
  { id: 113, chapter: 'ch2', rang: 'A', question: 'Qu\'est-ce que l\'évaluation gériatrique multidimensionnelle (EGM) ?', answer: 'Évaluation globale du sujet âgé couvrant : médical (comorbidités, médicaments), fonctionnel (AVD/AVD-I), psychologique (cognition, humeur), social (isolement, aidant), nutritionnel (MNA), sensoriel (vue, audition), environnemental (domicile). Outil clé du raisonnement gériatrique.', tags: ['EGM', 'évaluation', 'multidimensionnel'] },
  { id: 114, chapter: 'ch2', rang: 'B', question: 'Qu\'est-ce que la iatrogénie ?', answer: 'Ensemble des effets indésirables liés aux actes médicaux (diagnostiques, thérapeutiques, préventifs) et aux médicaments. Chez la personne âgée : facteurs aggravants = polymédication, insuffisance rénale, polymorphisme génétique, mauvaise observance.', tags: ['iatrogénie', 'effets indésirables'] },
  { id: 115, chapter: 'ch2', rang: 'A', question: 'Principe « Start low, go slow » ?', answer: 'Principe de prescription chez la personne âgée : commencer à dose faible et augmenter progressivement. S\'explique par : diminution de la clairance rénale, modification de la distribution (lipophilie), sensibilité accrue aux effets centraux. Exception : antibiotiques (dose adaptée au poids, pas de réduction systématique).', tags: ['prescription', 'posologie', 'start low'] },

  // ── Ch3 : Autonomie ──
  { id: 116, chapter: 'ch3', rang: 'A', question: 'Qu\'est-ce que la grille AGGIR et que mesure-t-elle ?', answer: 'Grille nationale d\'évaluation de la perte d\'autonomie. Évalue 10 variables discriminantes (cohérence, orientation, toilette, habillage, alimentation, continence, transferts, déplacement intérieur, déplacement extérieur, communication à distance) et 7 variables illustratives. Détermine le GIR (1 à 6).', tags: ['AGGIR', 'GIR', 'évaluation'] },
  { id: 117, chapter: 'ch3', rang: 'A', question: 'Signification des 6 niveaux GIR ?', answer: 'GIR 1 : dépendance totale (confinement lit/fauteuil). GIR 2 : fonctions mentales altérées ou dépendance motrice importante. GIR 3 : autonomie mentale conservée, dépendance motrice partielle. GIR 4 : aide pour les AVD. GIR 5 : aide ponctuelle. GIR 6 : personne autonome.', tags: ['GIR', 'AGGIR', 'APA'] },
  { id: 118, chapter: 'ch3', rang: 'A', question: 'Différence entre AVD et AVD-I ?', answer: 'AVD (Activités de la Vie Domestique) = actes de la vie quotidienne : toilette, habillage, alimentation, continence, transferts, déplacement. AVD-I (AVD instrumentales) = activités complexes : gestion administrative, courses, cuisine, transport, téléphone. AVD-I se perdent avant les AVD.', tags: ['AVD', 'autonomie', 'dépendance'] },
  { id: 119, chapter: 'ch3', rang: 'A', question: 'Quels sont les 6 GIR et qui ouvrent droit à l\'APA ?', answer: 'GIR 1-2 : dépendance lourde → APA établissement ou domicile. GIR 3-4 : dépendance partielle → APA domicile. GIR 5-6 : peu/pas dépendant → pas d\'APA. L\'APA n\'est pas soumise à conditions de ressources mais le montant est modulé.', tags: ['GIR', 'APA', 'droit'] },
  { id: 120, chapter: 'ch3', rang: 'B', question: 'Qu\'est-ce que la dépendance iatrogène ?', answer: 'Perte d\'autonomie fonctionnelle secondaire à un acte médical ou un médicament (ex : sédation, hypotension, chutes liées aux psychotropes). Évitable. La iatrogénie est une cause majeure de perte d\'autonomie chez la personne âgée.', tags: ['iatrogénie', 'dépendance', 'AVD'] },

  // ── Ch4 : Éthique ──
  { id: 121, chapter: 'ch4', rang: 'A', question: 'Définition des directives anticipées ?', answer: 'Document écrit par une personne majeure pour exprimer ses souhaits de fin de vie au cas où elle ne pourrait plus s\'exprimer. Valables sans limitation de durée (révisables/révocables). Prises en compte si situation irréversible et pronostic engagé.', tags: ['directives anticipées', 'fin de vie'] },
  { id: 122, chapter: 'ch4', rang: 'A', question: 'Rôle de la personne de confiance ?', answer: 'Personne désignée par le patient pour l\'accompagner dans les décisions médicales. Consultée si le patient ne peut exprimer sa volonté. Avis consultatif (pas décisionnel). Désignation par écrit, en présence de 2 témoins. Peut accompagner les démarches.', tags: ['personne de confiance', 'éthique'] },
  { id: 123, chapter: 'ch4', rang: 'A', question: 'Différence entre curatelle et tutelle ?', answer: 'Curatelle : protection intermédiaire. La personne accomplit seule les actes de gestion courante ; les actes importants (vente, emprunt) nécessitent l\'assistance du curateur. Tutelle : protection renforcée. Un tuteur représente la personne dans tous les actes de la vie civile. Prononcées par le juge des tutelles.', tags: ['curatelle', 'tutelle', 'protection'] },
  { id: 124, chapter: 'ch4', rang: 'A', question: 'Qu\'est-ce que la loi Claeys-Leonetti (2016) ?', answer: 'Loi encadrant la fin de vie : 1. Droit à la sédation profonde et continue jusqu\'au décès (SPCMD). 2. Refus de traitement opposable au médecin. 3. Interdiction de l\'obstination déraisonnable. 4. Directives anticipées renforcées. 5. Personne de confiance élargie.', tags: ['Claeys-Leonetti', 'fin de vie', 'loi'] },
  { id: 125, chapter: 'ch4', rang: 'B', question: 'Qu\'est-ce que l\'obstination déraisonnable ?', answer: 'Poursuite de traitements qui n\'ont d\'autre effet que le seul maintien artificiel de la vie, lorsqu\'il n\'existe aucun espoir raisonnable de guérison. Interdite par la loi Leonetti (2005) et Claeys-Leonetti (2016). Le médecin peut arrêter ou ne pas entreprendre ces traitements.', tags: ['obstination', 'fin de vie', 'éthique'] },

  // ── Ch5 : Troubles sensoriels ──
  { id: 126, chapter: 'ch5', rang: 'A', question: 'Définition de la presbyacousie ?', answer: 'Baisse progressive et bilatérale de l\'audition liée à l\'âge. Atteinte précoce des fréquences aiguës. Cause la plus fréquente de surdité chez la personne âgée. Correction par appareillage auditif. Facteur de risque de démence si non corrigée.', tags: ['presbyacousie', 'audition'] },
  { id: 127, chapter: 'ch5', rang: 'A', question: 'Définition de la DMLA ?', answer: 'Dégénérescence Maculaire Liée à l\'Age. Atteinte de la macula (zone centrale de la rétine). Cause principale de malvoyance après 50 ans. Formes : sèche (atrophique, 80%) et humide (néovasculaire, 20%, traitable par injections intravitréennes anti-VEGF).', tags: ['DMLA', 'vision', 'ophtalmologie'] },
  { id: 128, chapter: 'ch5', rang: 'A', question: 'Quel est le lien entre troubles sensoriels et chutes ?', answer: 'Le déficit visuel (DMLA, cataracte, glaucome) et le déficit auditif (presbyacousie) sont des facteurs de risque indépendants de chute. La correction visuelle et l\'appareillage auditif réduisent le risque de chute de 30-50%.', tags: ['sensoriel', 'chute', 'prévention'] },
  { id: 129, chapter: 'ch5', rang: 'B', question: 'Définition de la presbytie ?', answer: 'Baisse progressive de l\'accommodation liée à l\'âge (perte d\'élasticité du cristallin). Apparition vers 45 ans. Gêne en vision de près. Correction par verres convexes (lentilles de lecture).', tags: ['presbytie', 'vision', 'cristallin'] },

  // ── Ch6 : Ostéoporose ──
  { id: 130, chapter: 'ch6', rang: 'A', question: 'Définition de l\'ostéoporose ?', answer: 'Maladie osseuse systémique caractérisée par une diminution de la densité minérale osseuse (DMO) et une altération de la microarchitecture osseuse, entraînant une fragilité osseuse et un risque fracturaire accru. DEXA : T-score ≤ -2,5.', tags: ['ostéoporose', 'DEXA', 'T-score'] },
  { id: 131, chapter: 'ch6', rang: 'A', question: 'Valeurs du T-score et interprétation ?', answer: 'T-score > -1 : normal. T-score entre -1 et -2,5 : ostéopénie. T-score ≤ -2,5 : ostéoporose. T-score ≤ -2,5 + fracture : ostéoporose sévère. Mesure par DEXA (absorptiométrie biphotonique) au col fémoral et rachis lombaire.', tags: ['T-score', 'DEXA', 'ostéoporose'] },
  { id: 132, chapter: 'ch6', rang: 'A', question: 'Traitement de 1ère intention de l\'ostéoporose ?', answer: '1. Bisphosphonates : alendronate 70mg/sem (per os) ou zolédronate 5mg IV/an. 2. Supplémentation : calcium 1000-1200mg/j + vitamine D 800-1000 UI/j. 3. Mesures non médicamenteuses : activité physique, prévention des chutes, arrêt tabac.', tags: ['bisphosphonates', 'traitement', 'calcium'] },
  { id: 133, chapter: 'ch6', rang: 'A', question: 'Facteurs de risque de fracture ostéoporotique ?', answer: 'Âge > 70 ans, ATCD personnel de fracture, ATCD familial de fracture du col, IMC < 19, corticothérapie prolongée, tabac, alcool, polyarthrite rhumatoïde, hypogonadisme, DEXA T-score ≤ -2,5.', tags: ['facteurs de risque', 'fracture', 'ostéoporose'] },
  { id: 134, chapter: 'ch6', rang: 'B', question: 'Qu\'est-ce que le FRAX ?', answer: 'Fracture Risk Assessment Tool. Outil de calcul du risque fracturaire à 10 ans (fracture ostéoporotique majeure + hanche). Intègre : âge, sexe, IMC, ATCD fracture, ATCD parental, tabac, alcool, corticoïdes, arthrite rhumatoïde, ostéoporose secondaire.', tags: ['FRAX', 'risque', 'fracture'] },

  // ── Ch7 : Arthrose ──
  { id: 135, chapter: 'ch7', rang: 'A', question: 'Définition de l\'arthrose ?', answer: 'Maladie dégénérative du cartilage articulaire avec remodelage osseux (ostéophytes). Atteinte préférentielle : genou (gonarthrose), hanche (coxarthrose), colonne vertébrale, pouce (rhizarthrose). Facteurs : âge, obésité, surcharge mécanique, génétique.', tags: ['arthrose', 'cartilage', 'dégénératif'] },
  { id: 136, chapter: 'ch7', rang: 'A', question: 'Traitement non pharmacologique de l\'arthrose ?', answer: '1. Activité physique adaptée (marche, natation, vélo). 2. Perte de poids si surpoids (réduction de 5% = amélioration clinique). 3. Kinésithérapie (renforcement musculaire, étirements). 4. Aides techniques (cannes, semelles). 5. Ergothérapie (adaptation du domicile).', tags: ['traitement', 'non pharmacologique', 'kinésithérapie'] },
  { id: 137, chapter: 'ch7', rang: 'A', question: 'Traitement pharmacologique de l\'arthrose ?', answer: '1. Paracétamol = 1ère intention (3g/j max). 2. AINS topiques en 1ère intention si atteinte locale. 3. AINS per os à dose minimale et durée courte (effets GI, rénaux, cardio ++ chez la PA). 4. Infiltrations de corticoïdes. 5. Acide hyaluronique (efficacité discutée). Éviter opioïdes.', tags: ['AINS', 'paracétamol', 'traitement'] },
  { id: 138, chapter: 'ch7', rang: 'B', question: 'Indication de la prothèse de hanche/genou ?', answer: 'Arthrose sévère avec douleur invalidante résistante au traitement médical optimal ≥ 6 mois, retentissement fonctionnel majeur, perte d\'autonomie. Critères : douleur au repos, limitation des AVD, échec des traitements conservateurs.', tags: ['prothèse', 'chirurgie', 'arthrose'] },
  { id: 139, chapter: 'ch7', rang: 'A', question: 'Pourquoi éviter les AINS chez la personne âgée ?', answer: 'Effets indésirables majeurs : 1. Toxique gastrique (ulcère, hémorragie). 2. Néphrotoxique (insuffisance rénale aiguë). 3. Rétention hydrosodée (décompensation cardiaque). 4. HTA. 5. Interactions (anticoagulants, antiplaquettaires). 6. Confusion (surtout les AINS centraux).', tags: ['AINS', 'iatrogénie', 'effets indésirables'] }
];
