const FLASHCARDS_C = [
  // ── Ch15 : Incontinence ──
  { id: 301, chapter: 'ch15', rang: 'A', question: 'Types d\'incontinence urinaire ?', answer: '1. IUE (effort) : fuites à l\'effort, toux, éternuement. 2. IUU (urgente) : fuites avec impériosité. 3. Mixte : IUE + IUU. 4. Fonctionnelle : liée à la mobilité/cognition. 5. Par regorgement : globe vésical. 6. Neurogène : lésion neurologique.', tags: ['types', 'IUE', 'IUU'] },
  { id: 302, chapter: 'ch15', rang: 'A', question: 'Facteurs réversibles d\'incontinence chez la PA ?', answer: 'Méthode DIAPPERS : D = Delirium, I = Infection urinaire, A = Atrophie urétrale/vaginale, P = Pharmacologique (diurétiques, anticholinergiques), P = Psychologique, E = Excessive production urinaire (diabète, insuffisance cardiaque), R = Réduction mobilité, S = Selle (constipation).', tags: ['DIAPPERS', 'réversible', 'facteurs'] },
  { id: 303, chapter: 'ch15', rang: 'A', question: 'Traitement de l\'IUE (incontinence d\'effort) ?', answer: '1. Rééducation périnéale (kinésithérapie du plancher pelvien) = 1ère intention. 2. Pessaire si cystocèle. 3. Traitement local œstrogènes vaginaux. 4. Si échec : chirurgie (bandelette sous-urétrale). 5. Perte de poids si surpoids.', tags: ['IUE', 'rééducation', 'pessaire'] },
  { id: 304, chapter: 'ch15', rang: 'A', question: 'Traitement de l\'IUU (incontinence urgente) ?', answer: '1. Rééducation vésicale (mictions programmées). 2. Anticholinergiques (solifénacine, fésotérodine) — à éviter chez la PA (confusion, constipation). 3. Bêta-3 agoniste (mirabégron) = meilleure tolérance. 4. Toltérodine si besoin.', tags: ['IUU', 'mirabégron', 'rééducation'] },
  { id: 305, chapter: 'ch15', rang: 'B', question: 'Pourquoi éviter les anticholinergiques chez la PA ?', answer: 'Effets indésirables : confusion, somnolence, constipation, sécheresse buccale, rétention urinaire, troubles de la vision, augmentation du risque de chute. Critères Beers : tous les anticholinergiques sont listés comme médicaments à éviter chez la PA.', tags: ['anticholinergiques', 'Beers', 'PA'] },

  // ── Ch16 : Prescrire ──
  { id: 306, chapter: 'ch16', rang: 'A', question: 'Critères Beers : qu\'est-ce que c\'est ?', answer: 'Liste de médicaments potentiellement inappropriés chez les personnes âgées (≥ 65 ans). Établie par l\'AGS (American Geriatrics Society). Catégories : médicaments à éviter, à éviter dans certaines conditions, associations à éviter. Mise à jour régulière.', tags: ['Beers', 'inapproprié', 'prescription'] },
  { id: 307, chapter: 'ch16', rang: 'A', question: 'Critères STOPP/START : différence ?', answer: 'STOPP (Screening Tool of Older Persons\' Prescriptions) : médicaments potentielment inappropriés à arrêter. START (Screening Tool to Alert to Right Treatment) : médicaments indiqués mais non prescrits. Plus spécifiques que Beers pour la clinique européenne.', tags: ['STOPP', 'START', 'prescription'] },
  { id: 308, chapter: 'ch16', rang: 'A', question: 'Principe « Start low, go slow » ?', answer: 'Chez la PA : commencer à dose faible et augmenter progressivement. S\'explique par : diminution clairance rénale, modification distribution (lipophilie), sensibilité accrue aux effets centraux. Exception : antibiotiques (dose adaptée au poids, pas de réduction systématique).', tags: ['start low', 'posologie', 'principe'] },
  { id: 309, chapter: 'ch16', rang: 'A', question: 'Qu\'est-ce que la cascade iatrogénique ?', answer: 'Prescription d\'un médicament pour traiter l\'effet indésirable d\'un autre médicament, créant un cercle vicieux. Exemple : anticholinergique → constipation → laxatif → diarrhée → anti-diarrhéique → confusion → neuroleptique → parkinsonisme → antiparkinsonien.', tags: ['cascade', 'iatrogénie', 'polymédication'] },
  { id: 310, chapter: 'ch16', rang: 'A', question: 'Médicaments à éviter chez la PA (critères Beers) ?', answer: '1. Benzodiazépines (chute, confusion). 2. AINS (rénal, GI, cardio). 3. Anticholinergiques (confusion, constipation). 4. Hypnotiques (zolpidem, zopiclone). 5. Antidépresseurs tricycliques. 6. Opioïdes (codéine, tramadol) à doses réduites. 7. Digoxine > 0.125mg.', tags: ['Beers', 'médicaments', 'à éviter'] },

  // ── Ch17 : Soins palliatifs ──
  { id: 311, chapter: 'ch17', rang: 'A', question: 'Définition des soins palliatifs ?', answer: 'Soins actifs et continus pratiqués par une équipe pluridisciplinaire, en institution ou à domicile. Ils visent à soulager la douleur, apporter un soutien psychologique et social, sans abrévier ni prolonger la vie. Applicables à tout âge et à toute maladie grave évolutive.', tags: ['palliatif', 'définition', 'soins'] },
  { id: 312, chapter: 'ch17', rang: 'A', question: 'Qu\'est-ce que la sédation en fin de vie ?', answer: 'Administration de médicaments à doses progressives pour diminuer la vigilance, visant à soulager une souffrance réfractaire. Types : proportionnelle (réversible), profonde et continue jusqu\'au décès (SPCMD). Conditions : souffrance réfractaire, demande patient/conseil, décision collégiale.', tags: ['sédation', 'SPCMD', 'souffrance'] },
  { id: 313, chapter: 'ch17', rang: 'A', question: 'Conditions légales de la sédation (loi Claeys-Leonetti) ?', answer: '1. Souffrance réfractaire à tous les traitements. 2. Situation en phase avancée ou terminale. 3. Demande du patient (ou directives anticipées/personne de confiance). 4. Décision collégiale (médecin + 2 confrères). 5. Information du patient et entourage. 6. Traçature dans le dossier.', tags: ['Claeys-Leonetti', 'sédation', 'conditions'] },
  { id: 314, chapter: 'ch17', rang: 'B', question: 'Différence entre sédation et euthanasie ?', answer: 'Sédation : intention de soulager la souffrance, effet secondaire = raccourcissement de la vie (accepté). Euthanasie : intention de donner la mort (interdite en France). Suicide assisté : interdit en France. La sédation est légale si les conditions sont remplies. L\'euthanasie est un délit pénal.', tags: ['sédation', 'euthanasie', 'éthique'] },
  { id: 315, chapter: 'ch17', rang: 'A', question: 'Soins de confort en fin de vie ?', answer: '1. Douleur : morphine SC titration. 2. Anxiété : midazolam SC. 3. Dyspnée : morphine, oxygène si confort. 4. Soins buccaux (bouche sèche). 5. Hydratation cutanée. 6. Positionnement. 7. Écoute, présence. 8. Accompagnement spirituel si souhaité. 9. Pas de suralimentation artificielle.', tags: ['confort', 'soins', 'fin de vie'] },

  // ── Ch18 : Mini-dossiers ──
  { id: 316, chapter: 'ch18', rang: 'A', question: 'Principes de l\'évaluation gériatrique multidimensionnelle ?', answer: 'Évaluation globale couvrant 7 domaines : 1. Médical (comorbidités, médicaments). 2. Fonctionnel (AVD/AVD-I). 3. Psychologique (cognition, humeur). 4. Social (isolement, aidant). 5. Nutritionnel (MNA). 6. Sensoriel (vue, audition). 7. Environnemental (domicile). Outil clé du gériatre.', tags: ['EGM', 'multidimensionnel', 'évaluation'] },
  { id: 317, chapter: 'ch18', rang: 'A', question: 'Comment évaluer l\'aidant ?', answer: 'Évaluer : 1. Charge de l\'aidant (échelle de Zarit). 2. État de santé de l\'aidant. 3. Qualité de la relation. 4. Ressources disponibles (aide professionnelle, famille). 5. Risque d\'épuisement. 6. Besoin de répit. L\'aidant est le « patient invisible » de la gériatrie.', tags: ['aidant', 'Zarit', 'épuisement'] },
  { id: 318, chapter: 'ch18', rang: 'A', question: 'Qu\'est-ce que le dispositif APA ?', answer: 'Allocation Personnalisée d\'Autonomie. Conditions : ≥ 60 ans, résidence stable en France, GIR 1-4. Montant : selon GIR et ressources (pas de plafond de ressources mais modulation). Utilisation : plan d\'aide (aide à domicile, accueil de jour, hébergement temporaire).', tags: ['APA', 'GIR', 'allocation'] },
  { id: 319, chapter: 'ch18', rang: 'B', question: 'Qu\'est-ce que la gérontechnologie ?', answer: 'Application des technologies au service des personnes âgées : domotique (éclairage intelligent, détection de chute), téléassistance, télémedecine, tablettes adaptées, robots compagnons, capteurs de mobilité. Objectif : maintenir l\'autonomie et la sécurité à domicile.', tags: ['gérontechnologie', 'domotique', 'technologie'] },

  // ── Ch19 : Key-features ──
  { id: 320, chapter: 'ch19', rang: 'A', question: 'Approche Bouchon pour une décompensation aiguë ?', answer: 'Toujours chercher les 3 facteurs : F1 (vieillissement), F2 (maladies chroniques), F3 (facteur précipitant). Priorité : traiter le F3 (réversible). Ne pas se contenter de traiter les symptômes. Chercher l\'intercurrent (infection, iatrogénie, déshydratation, douleur).', tags: ['Bouchon', 'décompensation', 'aigu'] },
  { id: 321, chapter: 'ch19', rang: 'A', question: 'Conduite à tenir devant une chute chez la PA ?', answer: '1. Bilan lésionnel (fracture ? TCC ?). 2. Recherche cause (cardiologique ? métabolique ? iatrogène ?). 3. Évaluation multidimensionnelle (marche, équilibre, médicaments, vision, cognition). 4. Prévention secondaire (kinésithérapie, révision médicamenteuse, adaptation domicile). 5. Signaler si récidive.', tags: ['chute', 'conduite', 'bilan'] },
  { id: 322, chapter: 'ch19', rang: 'A', question: 'Devant une confusion aiguë, quelles sont les urgences à éliminer ?', answer: '1. Hypoglycémie (< 0.5 g/L). 2. Méningite/encéphalite (fièvre, raideur). 3. AVC (signes focaux). 4. Intoxication (médicaments, alcool). 5. Hypoxie (pneumopathie, embolie). 6. Hypo/hyperthermie. 7. Hémorragie intracrânienne (traumatisme). Bilan urgent : NFS, iono, glycémie, gaz du sang, TDM cérébrale.', tags: ['confusion', 'urgences', 'bilan'] },
  { id: 323, chapter: 'ch19', rang: 'A', question: 'Comment évaluer le risque iatrogénique ?', answer: '1. Lister tous les médicaments (y compris OTC, phyto). 2. Compter le nombre de médicaments (≥ 5 = risque). 3. Appliquer critères Beers et STOPP/START. 4. Vérifier la fonction rénale (clairance). 5. Chercher les interactions. 6. Évaluer l\'observance. 7. Réévaluer régulièrement.', tags: ['iatrogénie', 'évaluation', 'polymédication'] },

  // ── Ch20 : Questions isolées ──
  { id: 324, chapter: 'ch20', rang: 'A', question: 'Quel est le seuil de DFG pour adapter les doses chez la PA ?', answer: 'DFG < 60 ml/min = adapter les doses des médicaments éliminés par voie rénale. DFG < 30 ml/min = ajustement majeur. DFG < 15 ml/min = insuffisance rénale terminale (dialyse). Formule CKD-EPI recommandée (pas Cockcroft-Gauss chez la PA).', tags: ['DFG', 'fonction rénale', 'posologie'] },
  { id: 325, chapter: 'ch20', rang: 'A', question: 'Qu\'est-ce que l\'hypotension orthostatique ?', answer: 'Chute de la PA systolique ≥ 20 mmHg ou diastolique ≥ 10 mmHg dans les 3 minutes après le passage debout. Symptômes : vertiges, lipothymie, syncope. Causes : déshydratation, médicaments (antihypertenseurs, diurétiques, psychotropes), neuropathie autonome.', tags: ['hypotension', 'orthostatique', 'chute'] },
  { id: 326, chapter: 'ch20', rang: 'A', question: 'Définition du syndrome de l\'immobilisation ?', answer: 'Ensemble des conséquences physiologiques de l\'alitement prolongé : fonte musculaire (sarcopénie d\'immobilisation), déminéralisation osseuse, escarres, pneumopathie, TVP, constipation, dépression, confusion. Prévention : mobilisation précoce, kinésithérapie.', tags: ['immobilisation', 'alitement', 'syndrome'] },
  { id: 327, chapter: 'ch20', rang: 'A', question: 'Critères de fragilité de Fried et modèle de Bouchon : lien ?', answer: 'Fried évalue la fragilité (phénotype clinique). Bouchon explique la décompensation (3 facteurs). Complémentaires : Fried identifie le patient fragile (F1), Bouchon explique pourquoi il se décompense (F3 = facteur précipitant). Le patient fragile se décompense plus facilement.', tags: ['Fried', 'Bouchon', 'fragilité'] },
  { id: 328, chapter: 'ch20', rang: 'B', question: 'Qu\'est-ce que la gérontologie et la gériatrie ?', answer: 'Gérontologie : étude du vieillissement dans toutes ses dimensions (biologique, psychologique, sociale). Gériatrie : spécialité médicale consacrée à la santé des personnes âgées. La gériatrie est une branche de la gérontologie. Approche : globale, multidimensionnelle, pluridisciplinaire.', tags: ['gérontologie', 'gériatrie', 'définition'] }
];
