const FLASHCARDS_B = [
  // ── Ch8 : Douleur ──
  { id: 201, chapter: 'ch8', rang: 'A', question: 'Échelle EVA pour la douleur ?', answer: 'Échelle Visuelle Analogique : ligne de 10 cm, 0 = pas de douleur, 10 = douleur maximale. Utilisable chez la personne âgée communicante. Si non communicante : utiliser ECPA ou DOLOPLUS-2.', tags: ['EVA', 'évaluation', 'douleur'] },
  { id: 202, chapter: 'ch8', rang: 'A', question: 'Comment évaluer la douleur chez une PA non communicante ?', answer: 'Échelle ECPA (Échelle Comportementale pour Personnes Âgées) ou DOLOPLUS-2. Observer : mimiques faciales (grimaces), vocalisations (gémissements), langage corporel (protection, retrait), modifications comportementales (agitation, repli), changement activité.', tags: ['ECPA', 'DOLOPLUS', 'non communicante'] },
  { id: 203, chapter: 'ch8', rang: 'A', question: 'Échelle OMS des paliers antalgiques ?', answer: 'Palier 1 : paracétamol (3g/j max). Palier 2 : tramadol, codéine (opioïdes faibles). Palier 3 : morphine (opioïdes forts). Chez la PA : privilégier palier 1, adapter aux fonctions rénales, éviter AINS, morphine à doses réduites.', tags: ['OMS', 'paliers', 'antalgique'] },
  { id: 204, chapter: 'ch8', rang: 'A', question: 'Qu\'est-ce que la douleur neuropathique ?', answer: 'Douleur liée à une lésion ou un dysfonctionnement du système nerveux. Description : brûlures, décharges, fourmillements, engourdissements. Traitement : antidépresseurs tricycliques (amitriptyline), IRSNA (duloxétine), antiépileptiques (gabapentine, prégabaline). Topiques : capsaïcine, lidocaïne.', tags: ['neuropathique', 'gabapentine', 'traitement'] },
  { id: 205, chapter: 'ch8', rang: 'B', question: 'Pourquoi éviter les AINS en 1ère intention pour la douleur chez la PA ?', answer: 'Risque gastrique (ulcère, hémorragie), néphrotoxicité, rétention hydrosodée, confusion, interactions avec anticoagulants. Paracétamol = antalgique de référence chez la PA. AINS topiques si atteinte locale.', tags: ['AINS', 'paracétamol', 'sujet âgé'] },

  // ── Ch9 : Troubles neurocognitifs ──
  { id: 206, chapter: 'ch9', rang: 'A', question: 'Score MMSE normal et seuil pathologique ?', answer: 'MMSE (Mini Mental State Examination) : /30. Normal : ≥ 24 (≥ 27 si niveau élevé). Trouble cognitif léger : 18-23. Démence légère : 15-17. Démence modérée : 10-14. Démence sévère : < 10. À adapter au niveau scolaire (ajouter 1-2 points si bas niveau).', tags: ['MMSE', 'score', 'démence'] },
  { id: 207, chapter: 'ch9', rang: 'A', question: 'Différence MMSE et MoCa ?', answer: 'MoCa (Montreal Cognitive Assessment) : /30, plus sensible que le MMSE pour les formes légères et les démences fronto-temporales. MoCa < 26 = suspect. Explore davantage les fonctions exécutives, l\'attention, la fluence verbale. MMSE plus largement utilisé mais moins sensible.', tags: ['MoCa', 'MMSE', 'dépistage'] },
  { id: 208, chapter: 'ch9', rang: 'A', question: 'Critères diagnostiques de la maladie d\'Alzheimer ?', answer: '1. Trouble neurocognitif majeur (≥ 2 domaines cognitifs). 2. Début progressif et déclin continu. 3. Pas de cause alternative. 4. Biomarqueurs : amyloïde (PET ou LCR), tau phosphorylé, atrophie hippocampique (IRM). Symptômes : amnésique d\'abord, puis langage, praxies, gnoses.', tags: ['Alzheimer', 'diagnostic', 'biomarqueurs'] },
  { id: 209, chapter: 'ch9', rang: 'A', question: 'Qu\'est-ce que la démence à corps de Lewy ?', answer: '2ème cause de démence dégénérative. Triade : 1. Fluctuations de la vigilance et de la cognition. 2. Hallucinations visuelles récurrentes et détaillées. 3. Signes parkinsoniens (akinésie, rigidité). Hypersensibilité aux neuroleptiques (CONTRE-INDIQUÉS). Traitement : IChE (rivastigmine).', tags: ['corps de Lewy', 'démence', 'parkinson'] },
  { id: 210, chapter: 'ch9', rang: 'A', question: 'Quels examens pour le bilan d\'une démence ?', answer: '1. Bilan biologique : NFS, glycémie, fonction rénale, TSH, vitamine B12, folates, calcémie, VSG, sérologie syphilis/VIH. 2. IRM cérébrale (atrophie hippocampique, infarctus). 3. EEG si suspicion de crise. 4. Bilan neuropsychologique complet. 5. Biomarqueurs LCR si doute.', tags: ['bilan', 'IRM', 'B12'] },
  { id: 211, chapter: 'ch9', rang: 'A', question: 'Traitement de la maladie d\'Alzheimer ?', answer: '1. IChE (inhibiteurs de cholinestérase) : donépézil 5-10mg, rivastigmine (patch 9.5-13.3mg/24h), galantamine. 2. Mémantine (antagoniste NMDA) si stade modéré-avancé. 3. Non-pharmacologique : stimulation cognitive, activité physique, socialisation. 4. Évaluer APA, aide à domicile.', tags: ['donépézil', 'mémantine', 'IChE'] },

  // ── Ch10 : Dépression ──
  { id: 212, chapter: 'ch10', rang: 'A', question: 'Score GDS pour la dépression gériatrique ?', answer: 'GDS (Geriatric Depression Scale) : 15 items. Score > 5/15 = dépistage positif pour la dépression. GDS-30 aussi disponible (> 10 = positif). Adaptée aux personnes âgées (évite les items somatiques).', tags: ['GDS', 'dépistage', 'dépression'] },
  { id: 213, chapter: 'ch10', rang: 'A', question: 'Qu\'est-ce que la pseudo-démence dépressive ?', answer: 'Troubles cognitifs secondaires à une dépression majeure, mimant une démence. Arguments pour la pseudo-démence : début brutal, plainte cognitive exagérée, humeur dépressive marquée, réponse au traitement antidépresseur, pas de signes neurologiques focaux.', tags: ['pseudo-démence', 'dépression', 'diagnostic'] },
  { id: 214, chapter: 'ch10', rang: 'A', question: 'Traitement de 1ère intention de la dépression chez la PA ?', answer: 'ISRS en 1ère intention : escitalopram 5-10mg ou sertraline 50mg (meilleur profil d\'interactions). Éviter tricycliques (effets anticholinergiques, risque chute). Psychothérapie de soutien. Activité physique. Surveillance rapprochée (risque suicidaire ++).', tags: ['ISRS', 'escitalopram', 'sertraline'] },
  { id: 215, chapter: 'ch10', rang: 'A', question: 'Taux de suicide le plus élevé chez quel groupe ?', answer: 'Hommes de plus de 75 ans. Facteurs : isolement social, veuvage, maladies chroniques, douleur, perte d\'autonomie, dépression non diagnostiquée. La dépression gériatrique est souvent sous-diagnostiquée (présentation atypique : plaintes somatiques, irritabilité).', tags: ['suicide', 'âge', 'prévention'] },

  // ── Ch11 : Syndrome confusionnel ──
  { id: 216, chapter: 'ch11', rang: 'A', question: 'Critères CAM du syndrome confusionnel ?', answer: 'CAM (Confusion Assessment Method) : 1. Début aigu et fluctuant. 2. Inattention. 3. Désorganisation de la pensée. 4. Altération du niveau de conscience. Diagnostic : 1 + 2 + (3 ou 4). Le syndrome confusionnel hypoactif est le plus fréquent et le plus sous-diagnostiqué.', tags: ['CAM', 'delirium', 'diagnostic'] },
  { id: 217, chapter: 'ch11', rang: 'A', question: 'Différence entre syndrome confusionnel hypo et hyperactif ?', answer: 'Hyperactif : agitation, hallucinations, désorientation, comportement erratique (25% des cas). Hypoactif : léthargie, retrait, somnolence, ralentissement (75% des cas). Le type hypoactif est souvent méconnu car le patient est « calme ». Mécanisme mixte possible.', tags: ['hypoactif', 'hyperactif', 'delirium'] },
  { id: 218, chapter: 'ch11', rang: 'A', question: 'Méthode des 6D pour les causes de confusion ?', answer: '1. Infection (ECP, pneumopathie). 2. Douleur. 3. Déshydratation. 4. Déséquilibre métabolique (hyponatrémie, hypoglycémie). 5. Drogues/médicaments (opioïdes, anticholinergiques, benzodiazépines, corticoïdes). 6. Désorientation (hospitalisation, immobilisation).', tags: ['6D', 'causes', 'delirium'] },
  { id: 219, chapter: 'ch11', rang: 'A', question: 'Prise en charge du syndrome confusionnel ?', answer: '1. Traiter la cause sous-jacente (priorité). 2. Mesures environnementales : chambre calme, lumière douce, repères temporo-spatiaux, horloge visible. 3. Éviter les contenants physiques. 4. Hydratation. 5. Si agitation majeure : halopéridol 0.5-1mg. 6. Éviter les benzodiazépines (sauf sevrage alcool).', tags: ['traitement', 'environnement', 'halopéridol'] },

  // ── Ch12 : Chutes ──
  { id: 220, chapter: 'ch12', rang: 'A', question: 'Facteurs de risque intrinsèques de chute ?', answer: 'Âge > 75 ans, ATCD de chutes, troubles de la marche/équilibre, troubles visuels, troubles cognitifs, hypotension orthostatique, troubles du pied, incontinence, dépression, polypharmacie (psychotropes ++), sarcopénie.', tags: ['facteurs de risque', 'intrinsèque', 'chute'] },
  { id: 221, chapter: 'ch12', rang: 'A', question: 'Test TUG : procédure et interprétation ?', answer: 'Timed Up and Go : se lever d\'une chaise, marcher 3 mètres, demi-tour, revenir s\'asseoir. Chronométrer. < 10s : normal. 10-20s : risque modéré. > 20s : risque de chute élevé. Test simple, rapide, reproductible.', tags: ['TUG', 'évaluation', 'marche'] },
  { id: 222, chapter: 'ch12', rang: 'A', question: 'Programme de prévention des chutes ?', answer: '1. Kinésithérapie (renforcement, équilibre, programme Otago). 2. Révision médicamenteuse (arrêter psychotropes). 3. Correction visuelle. 4. Adaptation domicile (éclairage, barres, tapis). 5. Vitamine D + calcium. 6. Appareillage si besoin. 7. Activité physique régulière.', tags: ['prévention', 'Otago', 'kinésithérapie'] },
  { id: 223, chapter: 'ch12', rang: 'B', question: 'Qu\'est-ce que le test de Tinetti ?', answer: 'Échelle d\'évaluation de l\'équilibre et de la marche : /28 points (équilibre /16 + marche /12). < 19 = risque de chute élevé, 19-24 = risque modéré, > 24 = faible risque. Évalue : transferts, station debout, marche, demi-tour, obstacles.', tags: ['Tinetti', 'équilibre', 'marche'] },

  // ── Ch13 : Alitement ──
  { id: 224, chapter: 'ch13', rang: 'A', question: 'Complications de l\'alitement chez la PA ?', answer: '1. Escarres. 2. Pneumopathie d\'inhalation. 3. Thrombose veineuse profonde. 4. Dénutrition. 5. Constipation. 6. Rétraction tendineuse. 7. Déminéralisation osseuse (1-2%/semaine). 8. Dépression. 9. Infection urinaire. 10. Confusion.', tags: ['alitement', 'complications', 'immobilisation'] },
  { id: 225, chapter: 'ch13', rang: 'A', question: 'Score de Waterlow pour les escarres ?', answer: 'Score de Waterlow : évalue le risque d\'escarre. Facteurs : âge, IMC, état cutané, mobilité, continence, appétit, médicaments. < 10 = risque faible. 10-14 = risque moyen. 15-19 = risque élevé. ≥ 20 = risque très élevé.', tags: ['Waterlow', 'escarre', 'risque'] },
  { id: 226, chapter: 'ch13', rang: 'A', question: 'Classification des escarres par stades ?', answer: 'Stade 1 : érythème persistant (non blanchissant). Stade 2 : décollement cutané (phlyctène, érosion). Stade 3 : nécrose du derme (perte de substance). Stade 4 : nécrose des tissus profonds (muscle, tendon, os). Stade non classifiable : escharre couvrant la plaie.', tags: ['stades', 'classification', 'escarre'] },
  { id: 227, chapter: 'ch13', rang: 'A', question: 'Prévention des escarres ?', answer: '1. Matelas anti-escarres (alternant ou à pression constante). 2. Changement de position toutes les 2h. 3. Soins cutanés (hydratation, protection humidité). 4. Supplémentation nutritionnelle. 5. Mobilisation précoce. 6. Surveillance cutanée quotidienne. 7. Réduction pression (surélevation talons).', tags: ['prévention', 'matelas', 'position'] },

  // ── Ch14 : Nutrition ──
  { id: 228, chapter: 'ch14', rang: 'A', question: 'Score MNA et interprétation ?', answer: 'MNA (Mini Nutritional Assessment) : /30 points. ≥ 24 = état nutritionnel normal. 17-23,5 = risque de dénutrition. < 17 = dénutrition constituée. Évalue : changement alimentaire, perte de poids, stress, neuropsychologie, IMC, autonomie.', tags: ['MNA', 'dénutrition', 'évaluation'] },
  { id: 229, chapter: 'ch14', rang: 'A', question: 'Critères de dénutrition chez la PA ?', answer: '1. IMC < 21 (ou < 22 si > 70 ans). 2. Perte de poids ≥ 5% en 1 mois ou ≥ 10% en 6 mois. 3. Albumine < 35 g/L. 4. Préalbumine < 0.15 g/L. 5. MNA < 17. La dénutrition augmente la mortalité, les complications chirurgicales, les escarres et les infections.', tags: ['critères', 'IMC', 'albumine'] },
  { id: 230, chapter: 'ch14', rang: 'A', question: 'Stratégie de réalimentation ?', answer: '1. Enrichissement alimentaire (crème, beurre, fromage râpé). 2. CNO (compléments nutritionnels oraux) 2-3/jour. 3. Fractionnement (5-6 repas/jour). 4. Si échec : nutrition entérale par sonde. 5. Réalimentation progressive (éviter syndrome de renutrition). 6. Surveillance poids hebdomadaire.', tags: ['réalimentation', 'CNO', 'renutrition'] },
  { id: 231, chapter: 'ch14', rang: 'A', question: 'Qu\'est-ce que le syndrome de renutrition ?', answer: 'Complication métabolique lors de la réalimentation d\'un patient dénutri. Caractérisé par : hypophosphatémie, hypokaliémie, hypomagnésémie, rétention hydrosodée. Prévention : réalimentation progressive (15-20 kcal/kg/j puis augmentation), supplémentation en vitamines et minéraux.', tags: ['renutrition', 'hypophosphatémie', 'complication'] },
  { id: 232, chapter: 'ch14', rang: 'B', question: 'Quel IMC cible chez la personne âgée ?', answer: 'IMC cible : 22-27 kg/m² chez la PA. Un IMC < 21 est associé à une surmortalité. Un IMC légèrement surpoids (25-27) est protecteur chez la PA (réserve métabolique). Ne pas chercher à faire maigrir une personne âgée en surpoids modéré.', tags: ['IMC', 'cible', 'sujet âgé'] }
];
