const FLASHCARDS_MEMOS = [
  // ── Mnémotechniques & scores — autonomie (ch3) ──
  { id: 'memo-1', chapter: 'ch3', rang: 'A',
    question: 'Mnémotechnique ADL (Katz) : les 6 activités de la vie quotidienne ?',
    answer: 'BATHING · DRESSING · TOILETING · TRANSFERRING · CONTINENCE · FEEDING. En français : toilette, habillage, continence, transferts, déplacement (marche), alimentation. Score Katz : A (autonome) à G (dépendant pour ≥ 2 AVD).',
    tags: ['ADL', 'Katz', 'mnémotechnique', 'autonomie'] },
  { id: 'memo-2', chapter: 'ch3', rang: 'A',
    question: 'Mnémotechnique IADL (Lawton) : exemples d\'AVD instrumentales à retenir ?',
    answer: 'SHOPPING · COOKING · HOUSEKEEPING · LAUNDRY · TELEPHONE · TRANSPORT · MEDICATIONS · FINANCES. Perdues AVANT les AVD de base → signe précoce de déclin fonctionnel.',
    tags: ['IADL', 'Lawton', 'mnémotechnique', 'autonomie'] },

  // ── Cognition (ch9) ──
  { id: 'memo-3', chapter: 'ch9', rang: 'A',
    question: 'MMSE (MMS) : que évalue-t-on et seuils mnémotechniques ?',
    answer: '30 points : Orientation (10) · Mémorisation/rappel (6) · Attention/calcul (5) · Langage (8) · Praxies (1). Seuils : ≥ 24 normal · 18-23 léger · < 18 sévère. Toujours corriger âge/scolarité.',
    tags: ['MMSE', 'MMS', 'cognition', 'mnémotechnique'] },

  // ── Dépression (ch10) ──
  { id: 'memo-4', chapter: 'ch10', rang: 'A',
    question: 'GDS-15 (Yesavage) : seuil et particularité mnémotechnique ?',
    answer: 'Geriatric Depression Scale — 15 questions Oui/Non, auto-administrable. Seuil : ≥ 5/15 = suspicion de dépression (≥ 10 = probable). Réponses « dépression » = OUI pour items positifs (ex : satisfaction de vie inversée). Pas besoin de psychiatre pour dépister.',
    tags: ['GDS', 'GDS-15', 'Yesavage', 'dépression'] },
  { id: 'memo-5', chapter: 'ch10', rang: 'A',
    question: 'Mnémotechnique : GDS vs PHQ-9 chez la personne âgée ?',
    answer: 'GDS = spécifique PA (somatisation, pas de culpabilité classique). PHQ-9 = DSM mais moins adapté aux plaintes somatiques. En EDN gériatrie : penser GDS-15 en 1er dépistage systématique (HAS).',
    tags: ['GDS', 'dépistage', 'mnémotechnique'] },

  // ── Confusion / delirium (ch11) ──
  { id: 'memo-6', chapter: 'ch11', rang: 'A',
    question: 'CAM : mnémotechnique des 4 critères et règle diagnostique ?',
    answer: 'A = Acute onset + fluctuation · M = Inattention · A = Altered level of consciousness OU C = Disorganized thinking. Diagnostic CAM = (1) + (2) + (3 OU 4). Delirium = urgence, cause réversible à chercher.',
    tags: ['CAM', 'delirium', 'mnémotechnique'] },
  { id: 'memo-7', chapter: 'ch11', rang: 'A',
    question: 'DIAPPERS : rappel mnémotechnique des causes réversibles de confusion ?',
    answer: 'D Delirium/Démence · I Infection · A Atrophie/lésions · P Psychiatrie · P Pharmacologie · E Endocrino/métabolique · R Réduction sensorielle · S Sommeil/Substances. Traiter la cause (surtout infection + iatrogénie).',
    tags: ['DIAPPERS', 'confusion', 'mnémotechnique'] },

  // ── Chutes (ch12) ──
  { id: 'memo-8', chapter: 'ch12', rang: 'A',
    question: 'Échelle de Tinetti (POMA) : composition et interprétation ?',
    answer: 'Performance Oriented Mobility Assessment. Équilibre (16) + Marche (12) = /28. < 19 = risque élevé de chute · 19-24 = risque modéré · 25-28 = faible. Alternative : TUG (< 10 s normal).',
    tags: ['Tinetti', 'POMA', 'chute', 'score'] },
  { id: 'memo-9', chapter: 'ch12', rang: 'A',
    question: 'Échelle d\'équilibre de Berg : seuils à retenir ?',
    answer: '/56 points (14 items, 0-4 chacun). ≤ 45 = risque élevé de chute · 46-50 = modéré · > 50 = faible. Évalue transferts, équilibre unipodal, rotation, ramassage au sol.',
    tags: ['Berg', 'équilibre', 'chute', 'score'] },
  { id: 'memo-10', chapter: 'ch12', rang: 'A',
    question: 'Mnémotechnique « Get Up and Go » vs Tinetti ?',
    answer: 'TUG = screening rapide (temps). Tinetti/Berg = évaluation fine équilibre/marche. En pratique : TUG d\'abord, si anormal → Tinetti ou Berg + bilan multifactoriel (vision, PA orthostatique, psychotropes).',
    tags: ['TUG', 'Tinetti', 'mnémotechnique', 'chute'] },

  // ── Escarres / immobilisation (ch13) ──
  { id: 'memo-11', chapter: 'ch13', rang: 'A',
    question: 'Échelle de Braden : les 6 dimensions et seuil de risque ?',
    answer: 'S = Sensory · M = Moisture · A = Activity · M = Mobility · N = Nutrition · F = Friction/shear. Score ≤ 12 = risque élevé · 13-14 modéré · 15-18 léger · 19-23 pas de risque. Plus utilisée que Norton.',
    tags: ['Braden', 'escarre', 'mnémotechnique'] },
  { id: 'memo-12', chapter: 'ch13', rang: 'A',
    question: 'Échelle de Norton : items et seuil ?',
    answer: '5 items (1-4 chacun) : État physique · État mental · Activité · Mobilité · Incontinence. Score < 14 = risque élevé d\'escarre. Score max = 20.',
    tags: ['Norton', 'escarre', 'score'] },
  { id: 'memo-13', chapter: 'ch13', rang: 'A',
    question: 'Échelle de Norton modifiée : différence avec Norton classique ?',
    answer: 'Ajoute l\'âge (> 75 ans) et l\'état nutritionnel comme items ou coefficients selon versions. Seuil souvent < 16 (vs < 14 classique). Vérifier la version utilisée dans l\'établissement (EDN : connaître les 5 items de base).',
    tags: ['Norton modifié', 'escarre', 'score'] },

  // ── Nutrition (ch14) ──
  { id: 'memo-14', chapter: 'ch14', rang: 'A',
    question: 'MNA / MNA-SF : seuils mnémotechniques ?',
    answer: 'MNA complet /30 : < 17 dénutrition · 17-23.5 risque · ≥ 24 normal. MNA-SF /14 : < 8 dénutrition · 8-11 risque · ≥ 12 normal. Dépistage systématique PA hospitalisée/institution.',
    tags: ['MNA', 'MNA-SF', 'dénutrition', 'score'] },
  { id: 'memo-15', chapter: 'ch14', rang: 'A',
    question: 'Mnémotechnique dépistage nutritionnel rapide (alertes) ?',
    answer: 'MNA-SF + « 5-10 » : perte ≥ 5% poids en 1 mois OU ≥ 10% en 6 mois · IMC < 21 (PA) · albumine basse · apport protéique < 1 g/kg. CNO : 30-35 kcal/kg · protéines 1-1,2 g/kg.',
    tags: ['nutrition', 'dépistage', 'mnémotechnique'] },

  // ── Douleur (ch8) ──
  { id: 'memo-16', chapter: 'ch8', rang: 'A',
    question: 'EVA, EN et ECPA : quand utiliser quelle échelle ?',
    answer: 'EVA = curseur 0-10 cm (communicant). EN = Échelle Numérique verbale 0-10 (simple). ECPA = Échelle Comportementale de la Douleur (PA non communicante : mimiques, gémissements, protection). Douleur ≥ 4/10 = à traiter.',
    tags: ['EVA', 'EN', 'ECPA', 'douleur'] },
  { id: 'memo-17', chapter: 'ch8', rang: 'A',
    question: 'Mnémotechnique OMS palier 1-2-3 (rappel posologie PA) ?',
    answer: 'Palier 1 : paracétamol (1ère intention PA). Palier 2 : opioïde faible ± adjuvant. Palier 3 : opioïde fort. PA : « Start low, go slow » opioïdes · surveiller constipation, confusion, chutes.',
    tags: ['douleur', 'OMS', 'mnémotechnique'] },

  // ── Ostéoporose (ch6) ──
  { id: 'memo-18', chapter: 'ch6', rang: 'A',
    question: 'T-score : mnémotechnique des 3 zones DEXA ?',
    answer: 'T ≥ -1 : NORMAL · -2,5 < T < -1 : OSTÉOPÉNIE · T ≤ -2,5 : OSTÉOPOROSE. Fracture sur os fragile + T ≤ -2,5 = ostéoporose sévère/établie. Z-score chez jeune ; T-score pour diagnostic chez PA.',
    tags: ['T-score', 'DEXA', 'ostéoporose', 'mnémotechnique'] },
  { id: 'memo-19', chapter: 'ch6', rang: 'A',
    question: 'FRAX : que retient-on pour l\'EDN (sans calculatrice) ?',
    answer: 'Risque fracturaire majeure + hanche à 10 ans. Variables : âge, sexe, IMC, ATCD fracture, parent fracture hanche, tabac, alcool, corticoïdes, AR, ostéoporose secondaire. Traitement si risque élevé même sans DEXA (selon seuils pays).',
    tags: ['FRAX', 'ostéoporose', 'score'] },

  // ── Iatrogénie / polymédication (ch2, ch20) ──
  { id: 'memo-20', chapter: 'ch2', rang: 'A',
    question: 'Critères de Beers : mnémotechnique et objectif ?',
    answer: 'Liste de médicaments potentiellement inappropriés chez la PA (≥ 65 ans). Classes à risque : anticholinergiques, benzodiazépines longues, AINS chroniques, antipsychotiques hors indication, dépresseurs myocardiques. Objectif : réduire iatrogénie — revue médicamenteuse systématique.',
    tags: ['Beers', 'iatrogénie', 'polymédication', 'mnémotechnique'] },
  { id: 'memo-21', chapter: 'ch2', rang: 'A',
    question: 'STOPP / START : complément des critères de Beers ?',
    answer: 'STOPP = médicaments à arrêter (ex : IPP sans indication, anticholinergique + démence). START = traitements à envisager (ex : statine post-IDM, vitamine D si ostéoporose). Plus orienté « prescriptions oubliées » que Beers.',
    tags: ['STOPP', 'START', 'Beers', 'iatrogénie'] },
  { id: 'memo-22', chapter: 'ch2', rang: 'A',
    question: 'Index de Charlson : à quoi sert-il et idée mnémotechnique ?',
    answer: 'Score de comorbidité pondéré (poids selon gravité : IDM, insuffisance cardiaque, démence, cancer…). Prédit mortalité à 1 et 10 ans. Plus le score est élevé, plus le pronostic somatique est engagé — utile en EGM et soins palliatifs.',
    tags: ['Charlson', 'comorbidité', 'score'] },

  // ── Éthique / droit (ch4) ──
  { id: 'memo-23', chapter: 'ch4', rang: 'A',
    question: 'Loi Leonetti (2005) : 3 points mnémotechniques ?',
    answer: '1. Droit à l\'information et au consentement (base Kouchner). 2. Refus de traitement / droit de ne pas souffrir inutilement. 3. Limitation / arrêt obstination déraisonnable (traitements « futilité »). Directives anticipées reconnues.',
    tags: ['Leonetti', 'éthique', 'fin de vie', 'mnémotechnique'] },
  { id: 'memo-24', chapter: 'ch4', rang: 'A',
    question: 'Loi Kouchner (2002) : droits du patient à retenir ?',
    answer: 'Droit à l\'information loyale, claire et appropriée · Consentement libre et éclairé · Accès au dossier médical · Personne de confiance · Secret médical. Fondement des lois Leonetti puis Claeys-Leonetti (2016).',
    tags: ['Kouchner', 'droits du patient', 'éthique'] },
  { id: 'memo-25', chapter: 'ch4', rang: 'A',
    question: 'Claeys-Leonetti (2016) : ajouts par rapport à Leonetti ?',
    answer: 'Sédation profonde et continue jusqu\'au décès (SPCMD) si souffrance réfractaire · Renforcement directives anticipées · Personne de confiance élargie. Ne legalise PAS l\'euthanasie active.',
    tags: ['Claeys-Leonetti', 'SPCMD', 'fin de vie'] },

  // ── Soins palliatifs (ch17) ──
  { id: 'memo-26', chapter: 'ch17', rang: 'A',
    question: 'Palliative Prognostic Score (PaP) : variables mnémotechniques ?',
    answer: 'PPS (performance) · Dyspnée au repos · Œdèmes · Perte de poids · Albumine · Leucocytose · Lymphopénie. Score élevé = survie courte (semaines). Aide à décider lieu de soins et intensité accompagnement — pas seul critère.',
    tags: ['PaP', 'palliatif', 'pronostic', 'score'] },
  { id: 'memo-27', chapter: 'ch17', rang: 'A',
    question: 'PPS (Palliative Performance Scale) : seuils usuels ?',
    answer: '0-100 % en 10 % d\'incréments (activité, intake, conscience). ≤ 30 % : fin de vie proche · 40-50 % : dépendance majeure · ≥ 70 % : encore autonome partiel. Complète le PaP et l\'échelle de Karnofsky en oncologie.',
    tags: ['PPS', 'palliatif', 'mnémotechnique'] },

  // ── Synthèse scores EDN ──
  { id: 'memo-28', chapter: 'ch20', rang: 'A',
    question: 'Tableau mnémotechnique : quel score pour quel problème ?',
    answer: 'Cognition MMSE · Dépression GDS-15 · Delirium CAM · Nutrition MNA-SF · Escarre Braden/Norton · Chute Tinetti/Berg/TUG · Douleur EVA/ECPA · Autonomie Katz/AGGIR · Ostéoporose T-score/FRAX · Iatrogénie Beers/STOPP-START.',
    tags: ['scores', 'synthèse', 'mnémotechnique', 'EDN'] },
  { id: 'memo-29', chapter: 'ch20', rang: 'B',
    question: 'Mnémotechnique « anticholinergique » et confusion ?',
    answer: 'Médicaments à charge anticholinergique élevée (cf. Anticholinergic Burden Scale) : confusion, rétention urinaire, constipation, chutes. Classes : antihistaminiques H1 1ère gen, tricycliques, antispasmodiques, certains antipsychotiques.',
    tags: ['anticholinergique', 'iatrogénie', 'mnémotechnique'] },
  { id: 'memo-30', chapter: 'ch11', rang: 'A',
    question: '4AT : alternative rapide au CAM ?',
    answer: '4 items (/12) : Alertness · AMT4 (orientation) · Attention · Acute change. ≥ 4 = possible delirium → confirmer par CAM. Dépistage < 2 min en urgence/USR.',
    tags: ['4AT', 'CAM', 'delirium', 'dépistage'] },
];