// Guides soins des plaies — Gériatrie, EHPAD et soins à domicile
const GUIDES_PLAIES = [
  {
    id: 'plaies-1',
    titre: 'Escarres (ulcères de pression) — stades I à IV',
    contenu: 'L\'escarre est une lésion localisée des tissus mous par pression prolongée, friction et/ou cisaillement, souvent sur proéminence osseuse (sacrum, talons, trochanters, omoplates). Chez le sujet âgé, l\'immobilité, la dénutrition, l\'incontinence et les vasculopathies augmentent fortement l\'incidence en institution.\n\nCLASSIFICATION NPUAP/EPUAP (stades) :\n- Stade I : érythème persistant non blanchissant sur peau intacte ; signe d\'alerte — décharge immédiate.\n- Stade II : perte partielle d\'épaisseur cutanée ; derme exposé, lit de plaie rose/rouge, sans adhérence visible ; pas de graisse, muscle ou os.\n- Stade III : perte pleine épaisseur ; tissu sous-cutané visible, adhérence possible ; os/tendon/muscle non exposés.\n- Stade IV : perte pleine épaisseur avec os, tendon ou muscle exposés ; risque ostéite élevé.\n- Stades complémentaires : non classifiable (couverte par escarre nécrotique) ; suspicion profondeur tissulaire (DPSI) — hématome ou croûte sur zone à risque.\n\nPRÉVENTION (priorité absolue) :\n- Scores Braden ou Norton ; plan de repositionnement 2–4 h, inclinaison 30°.\n- Matelas et coussins de décharge (talons surtout) ; lit clinique si besoin.\n- Nutrition : protéines 1,2–1,5 g/kg/j si toléré, calories adaptées, hydratation.\n- Gestion incontinence, peau propre et sèche sans sur-hydratation.\n\nTRAITEMENT :\n- Décharge totale de la zone (ne jamais traiter la plaie sans décharge).\n- Nettoyage eau tiède ou sérum physiologique ; détersion douce du tissu nécrotique selon filière.\n- Pansements maintenant milieu humide (voir guide pansements) ; stade 2 souvent hydrocolloïde/hydrofibre ; stades 3–4 alginate, mousse, interface si besoin.\n- Infection : érythème étendu, chaleur, purulence, odeur, retard cicatrisation, douleur nouvelle ; prélèvement si doute ; ATB si cellulite ou ostéite (IRM si profondeur).\n- Douleur : antalgie systématique avant pansement, souvent sous-estimée.\n\nGÉRIATRIE :\n- Escarre en fin de vie (Kennedy) : objectif confort, pas de curage agressif disproportionné.\n- Documentation, photos datées, signalement qualité ; enquête si négligence suspectée.',
    points_cles: ['Stade I = érythème non blanchissant', 'Décharge avant tout pansement', 'Braden/Norton + nutrition protéique', 'Stade IV = risque ostéite, IRM si doute']
  },
  {
    id: 'plaies-2',
    titre: 'Ulcère veineux des jambes',
    contenu: 'L\'ulcère veineux représente 70–80 % des ulcères de jambe ; il résulte de l\'insuffisance veineuse chronique et de l\'hypertension veineuse. Localisation typique : région malléolaire interne (medial gaiter). Chez le sujet âgé, l\'immobilité, l\'oedème et les comorbidités cardiaques compliquent la prise en charge.\n\nDIAGNOSTIC :\n- Signes associés : varices, lipodermatosclérose, dermite ocre, oedème chronique, eczéma de stase.\n- IPS (index pression systolique cheville/bras) obligatoire avant compression : IPS < 0,8 = composante artérielle — compression forte dangereuse.\n- Ulcère mixte fréquent ; écho-doppler si chirurgie veineuse ou doute anatomique.\n- Différentiels : artériel, vasculite, pyoderma gangrenosum, cancer (ulcère de Marjolin sur plaie chronique).\n\nTRAITEMENT LOCAL :\n- Nettoyage doux ; débridement du fibrine si nécessaire (autolytique ou mécanique doux).\n- Pansement absorbant adapté à l\'exsudat (hydrofibre, alginate, mousse) ; milieu humide sans macération péri-lésionnelle.\n- Traiter infection péri- ou intra-lésionnelle (topique ou systémique selon signes systémiques et cellulite).\n\nTRAITEMENT DE FOND :\n- Compression multicomposante (bandes ou bas de contention) si IPS ≥ 0,8 et tolérance cardiaque/pulmonaire ; adapter si insuffisance cardiaque droite sévère.\n- Élévation des jambes, marche et exercices de pompe musculaire si possible.\n- Traiter eczema de stase : dermocorticoïdes courts + émollients sur peau périphérique.\n\nCHRONICITÉ ET ORIENTATION :\n- Causes d\'échec : compression insuffisante, oedème non traité, infection, mobilité nulle.\n- Chirurgie veineuse ou greffe cutanée si échec 3–6 mois bien conduit et patient candidat.\n\nGÉRIATRIE :\n- Apprentissage aidants : pansement, compression, signes d\'alerte.\n- IPS systématique — confusion fréquente avec escarre ou ulcère artériel.',
    points_cles: ['Malléole interne = veineux typique', 'IPS avant toute compression', 'Compression + pansement absorbant', 'IPS < 0,8 : pas de contention forte']
  },
  {
    id: 'plaies-3',
    titre: 'Ulcère artériel des membres inférieurs',
    contenu: 'L\'ulcère artériel survient sur territoire ischémique (artériopathie oblitérante des membres inférieurs, AOMI). Il représente environ 10–20 % des ulcères de jambe ; pronostic local et membre dépend du débit sanguin restaurable.\n\nCLINIQUE :\n- Localisation : extrémités, orteils, face antéro-externe jambe, zones de frottement chaussure.\n- Bords souvent nets, fond pâle ou nécrotique, peu d\'exsudat au début ; douleur intense au repos, aggravée par dépendance.\n- Peau froide, pâle, pouls pédieux/fémoraux diminués ou absents.\n- IPS < 0,8 (souvent < 0,5 si ischémie sévère) ; TcPO2 bas au pied si disponible.\n\nPRINCIPES DE SOINS :\n- Ne pas compresser l\'ischémie ; pas de bandes contention sur ulcère artériel pur.\n- Position : membre en déclive modérée au repos selon confort ; éviter élévation prolongée comme pour ulcère veineux.\n- Douleur : antalgie adaptée (parfois opioïdes) ; éviter AINS si ischémie sévère et DFG bas sans surveillance.\n- Plaie : nettoyage doux ; détersion nécrose sèche prudente ; pansements non adhérents, protection bords ; pas de produits cytotoxiques.\n- Infection : risque de progression rapide ; ATB précoce si signes locaux ou systémiques ; imagerie si profondeur.\n\nREVASCULARISATION :\n- Avis chirurgien vasculaire / angioplastie si ischémie critique, douleur repos, plaie non cicatrisante, IPS très bas.\n- Amputation partielle ou palliation si non revascularisable — projet de soins partagé.\n\nFACTEURS DE RISQUE GÉRIATRIQUES :\n- Tabac, diabète, HTA, dyslipidémie, insuffisance cardiaque.\n- Confusion avec neuropathique ou veineux : IPS et pouls essentiels.\n\nSUIVI :\n- Contrôle douleur, signes de gangrène, état membre controlatéral ; prévention nouvelles plaies (chaussures, podologie).',
    points_cles: ['IPS < 0,8 : penser artériel', 'Pas de compression forte', 'Douleur repos = ischémie', 'Revascularisation si possible']
  },
  {
    id: 'plaies-4',
    titre: 'Ulcère neuropathique (pied diabétique et neuropathie)',
    contenu: 'L\'ulcère neuropathique résulte d\'une perte de sensibilité protectrice (neuropathie périphérique, le plus souvent diabétique) combinée à des déformations (hallux valgus, pied creux) et à des contraintes mécaniques répétées. L\'ischémie peut coexister (ulcère neuro-ischémique) : évaluation vasculaire systématique.\n\nMÉCANISMES :\n- Microtraumatismes répétés (chaussures inadaptées, marche pied insensible).\n- Callosités → rupture sous-jacente → plaie sous callosité.\n- Charcot neuro-ostéoarthropathie : pied chaud, tuméfié, déformé — immobilisation urgente.\n\nCLASSIFICATION UTILE (Wagner simplifiée) :\n- Superficiel / profond / avec abcès, ostéite ou gangrène — oriente urgence et imagerie.\n\nEXAMEN :\n- Inspection pieds à chaque consultation soins ; monofilament 10 g, pouls, IPS.\n- Radiographie pied si plaie profonde, os visible, infection ou suspicion ostéite ; IRM si doute.\n\nTRAITEMENT :\n- Décharge totale : botte plâtrée, chaussure post-opératoire, orthèse — selon filière et tolérance.\n- Détersion bords et callosités par personnel formé ; pas de curage agressif sans vascularisation.\n- Pansements adaptés exsudat ; traitement infection (souvent polymicrobienne) selon gravité.\n- Équilibre glycémique, nutrition, sevrage tabac.\n- Podologie, chaussures thérapeutiques, éducation patient et aidants.\n\nGÉRIATRIE :\n- Plaie parfois peu douloureuse malgré gravité — ne pas sous-estimer.\n- Chutes et transferts : coordination kiné, ergo, soins plaies.\n- Récidive fréquente sans suivi podologique et chaussage.',
    points_cles: ['IPS + pouls à chaque plaie pied', 'Décharge = clé de voûte', 'Callosité = masquer profondeur', 'Charcot = immobiliser, pas marcher']
  },
  {
    id: 'plaies-5',
    titre: 'Plaie chirurgicale et cicatrisation post-opératoire',
    contenu: 'Les plaies chirurgicales chez le sujet âgé cicatrisent plus lentement (peau fine, immunosénescence, comorbidités, polymédication). Le risque de déhiscence, d\'hématome, d\'infection et de surinfection nosocomiale est majoré.\n\nPHASES DE CICATRISATION :\n- Inflammation (J0–J4), prolifération (angiogenèse, granulation), remodelage (collagène) — plus longues après 75 ans.\n\nSOINS IMMÉDIATS POST-OP :\n- Respect protocole chirurgical : pansement stérile, date de premier changement selon filière (cicatrisation par première ou seconde intention).\n- Surveillance : rougeur excessive, écoulement purulent, déhiscence, fièvre, douleur disproportionnée.\n- Anticoagulation courante : surveiller hématome sous-cutané ; pas d\'arrêt sans avis médical.\n\nCICATRISATION PAR SECONDE INTENTION :\n- Déhiscence partielle ou totale, infection, nécrose de lambeau : nettoyage, détersion progressive, pansements milieu humide.\n- Éviter fermeture tendue ; nutrition protéique et vitamine C si carence suspectée.\n\nFACTEURS DE RISQUE D\'ÉCHEC :\n- Diabète mal équilibré, tabac, corticoïdes prolongés, malnutrition (albumine basse), hypoxie, chimiothérapie récente.\n- Tension sur suture : mobilisation adaptée, kinésithérapie selon indication.\n\nDOULEUR ET CONFORT :\n- Antalgie avant soins ; liaison avec équipe chirurgicale si douleur réfractaire (collection, infection profonde).\n\nGÉRIATRIE :\n- Projet de soins : réintervention parfois non souhaitée en fin de vie — soins locaux confort.\n- Documentation type de fermeture, date intervention, matériel (fil résorbable ou non).',
    points_cles: ['Surveiller déhiscence et hématome', 'Nutrition et glycémie influencent délai', 'Détersion progressive si 2e intention', 'Coordination avec chirurgien si doute']
  },
  {
    id: 'plaies-6',
    titre: 'Brûlures chez le sujet âgé',
    contenu: 'Les brûlures du sujet âgé surviennent souvent à domicile ou en EHPAD (bains trop chauds, cuisine, radiateurs, tabac). La peau fine, la perte de réflexes de retrait, la polypharmacie et les troubles cognitifs augmentent gravité et retard de prise en charge.\n\nÉVALUATION INITIALE :\n- Surface corporelle brûlée (règle des 9 ou palmaire) ; profondeur : superficielle (érythème), partielle (cloques), pleine épaisseur (cuir tanné, insensible).\n- Localisation à risque : face, mains, pieds, plis, zones circulées.\n- Critères de gravité : âge > 60 ans souvent facteur de transfert centre brûlés selon filière ; inhalation, électrique, chimique = urgences spécifiques.\n\nPREMIERS SOINS :\n- Refroidissement 15–20 °C, 20 min si < 3 h et brûlure thermique sans risque hypothermie (prudence sujet âgé frêle).\n- Retirer vêtements non adhérents ; ne pas percer cloques intactes en première ligne.\n- Couvrir proprement, antalgie, hydratation si grande surface.\n\nTRAITEMENT LOCAL :\n- Brûlures partielles superficielles : pansements non adhérents, argent sulfadiazine selon protocole, changements réguliers.\n- Brûlures profondes : avis spécialisé ; excision-greffe selon indication ; cicatrisation dirigée possible en attente.\n\nCOMPLICATIONS GÉRIATRIQUES :\n- Infection, déshydratation, décompensation cardiaque, délirium, dénutrition prolongée.\n- Rétraction cicatricielle et mobilité réduite — kinésithérapie précoce si indication.\n\nPRÉVENTION EHPAD / DOMICILE :\n- Température eau thermostatée, protecteurs radiateurs, supervision cuisine, détecteurs fumée.\n- Révision médicaments sédatifs et alcool.',
    points_cles: ['Âge = gravité et transfert à discuter', 'Refroidissement modéré, éviter hypothermie', 'Cloques intactes : ne pas percer', 'Prévention domestique et EHPAD']
  },
  {
    id: 'plaies-7',
    titre: 'Plaie oncologique et soins de support',
    contenu: 'Les plaies tumorales (cutanées, fistules, masses ulcérées, points de drainage) touchent une part croissante des patients âgés en soins palliatifs ou sous traitements oncologiques. L\'objectif principal est le confort, l\'odeur, l\'exsudat et la dignité — pas toujours la cicatrisation.\n\nTYPES DE PLAIES ONCOLOGIQUES :\n- Ulcération directe du tumor (sein, tête et cou, mélanome, sarcome).\n- Fistule (entero-cutanée, pleuro-cutanée) : exsudat parfois très abondant et irritant.\n- Plaie iatrogène post-radiothérapie : radiodermite aiguë ou chronique, nécrose.\n- Maligne fistulizing wound / cancer wound — saignements possibles.\n\nÉVALUATION :\n- Douleur, saignement, odeur, exsudat, infection, retentissement psychosocial et isolement.\n- Projet de soins et directives anticipées ; discussion chimiothérapie/RT si plaie en contexte curatif restant.\n\nSOINS LOCAUX :\n- Nettoyage doux ; pansements super-absorbants, charbon actif pour odeur, interfaces non adhérentes.\n- Saignements : hémostase locale (acide tranexamique topique, adrenaline diluée selon protocole), pansements hémostatiques ; radiothérapie hémostatique parfois.\n- Infection : traiter si gêne majeure ; parfois approche proportionnée en fin de vie.\n- Métronidazole topique ou systémique pour odeur anaérobie (selon indication et tolérance).\n\nACCOMPAGNEMENT :\n- Équipe pluridisciplinaire, psychologie, contrôle douleur (opioïdes, anesthésiques locaux avant pansement).\n- Aidants : formation gestes, gestion odeur, soutien.\n\nGÉRIATRIE :\n- Ne pas imposer pansements fréquents douloureux ; privilégier autonomie et esthétique acceptable (vêtements, position).',
    points_cles: ['Objectif confort > cicatrisation', 'Odeur : charbon + métronidazole si indiqué', 'Antalgie avant chaque soin', 'Projet de soins et saignements anticipés']
  },
  {
    id: 'plaies-8',
    titre: 'Dermatite associée à l\'humidité (MASD / IAD)',
    contenu: 'La dermatite associée regroupe les lésions cutanées causées par l\'humidité prolongée : incontinence (IAD — incontinence-associated dermatitis), transpiration, fuites stomales, muqueuse ou salivaire. En gériatrie, l\'IAD majore le risque d\'escarre et complique le traitement des plaies du siège.\n\nCLINIQUE :\n- Érythème, macération, érosion superficielle, papules satellites parfois ; douleur et brûlure au contact ; limites mal définies dans les plis.\n- Différencier : candidose (satellites), pression (escarre stade I–II), herpès, psoriasis inversé.\n\nFACTEURS DE RISQUE :\n- Incontinence urinaire et fécale, diarrhée, immobilité, malnutrition, sonde urinaire avec fuites péri-méat, double incontinence.\n\nPRÉVENTION ET TRAITEMENT :\n- Programme continence : changes fréquents, produits absorbants adaptés, toilette au liniment ou eau + syndet sans friction.\n- Barrières cutanées (oxyde de zinc, diméthicone, acrylates) sur peau intacte ou légèrement irritée.\n- Sécher sans frotter ; aération de la zone quand possible.\n- Si candidose associée : antifongique topique + traiter macération.\n- Pas de ruban adhésif sur peau macérée ; pansements qui n\'entraînent pas à l\'enlèvement.\n\nLIEN AVEC PLAIES CHRONIQUES :\n- IAD non traitée → rupture barrière → escarre stade II en quelques heures sur sacrum.\n- Intégrer IAD dans tout plan anti-escarre et tout protocole ulcère péri-anal.\n\nGÉRIATRIE :\n- Évaluer capacité cognitive pour demande de change ; protéger dignité.\n- Réviser laxatifs, antibiotiques (diarrhée C. difficile) si dermatite récurrente.',
    points_cles: ['IAD ≠ escarre mais précède souvent', 'Liniment + barrière + changes', 'Limiter friction et adhésifs', 'Traiter diarrhée et candidose']
  },
  {
    id: 'plaies-9',
    titre: 'Cicatrisation dirigée (TIME / détersion)',
    contenu: 'La cicatrisation dirigée structure l\'évaluation et le traitement des plaies chroniques selon le modèle TIME : Tissue (tissu), Infection/Inflammation, Moisture (humidité), Edge (bords). Elle vise à convertir une plaie chronique en milieu favorable à la réparation.\n\nT — TISSU (détersion) :\n- Identifier nécrose sèche (eschar), fibrine, biopellicule, tissu de granulation sain, hypergranulation.\n- Méthodes : autolytique (pansements hydrocolloïdes, hydrofibres, tulle gras), enzymatique (collagénase si indiqué), mécanique douce, biosurgery (asticots) selon filière et acceptabilité.\n- Éviter détersion agressive sur ischémie ou sans décharge (escarre).\n\nI — INFECTION / INFLAMMATION :\n- Signes locaux et critères inflammation chronique ; biofilm suspecté si stagnation malgré soins adaptés.\n- Prélèvement tissulaire profond si antibiothérapie envisagée ; pas d\'ECBU pour plaie superficielle seule.\n- Antiseptiques topiques courte durée parfois (PHMB, iodés modérés) — pas en routine prolongée cytotoxique.\n\nM — MOISTURE (exsudat) :\n- Trop sec : retard ; trop humide : macération. Adapter absorbance du pansement.\n- Péri-lésion : barrière cutanée si exsudat modéré à important.\n\nE — EDGE (bords) :\n- Bords non progressants : cause sous-jacente (pression, ischémie, oedème) à traiter ; parfois stimulation bords ou avis chirurgical.\n\nGÉRIATRIE :\n- Réévaluer proportionnalité en fin de vie : détersion enzymatique douce ou confort uniquement.\n- Photos et mensurations (surface) pour suivi objectif.',
    points_cles: ['TIME = structure l\'évaluation', 'Détersion sans décharge = échec', 'Biofilm si plaie stagnante', 'Traiter cause (ischémie, pression)']
  },
  {
    id: 'plaies-10',
    titre: 'Pansements modernes et choix thérapeutique',
    contenu: 'Les pansements modernes modulent l\'humidité, protègent, absorbent et parfois délivrent des principes actifs. Le choix dépend de la phase de cicatrisation, de l\'exsudat, de la profondeur, de l\'infection et du site — pas d\'un pansement unique pour toutes les plaies.\n\nPANSEMENTS MAINTIEN D\'HUMIDITÉ / PROTECTION :\n- Hydrocolloïdes : stades escarre II peu exsudatives, protection stade I ; éviter si infection profonde ou escarre III–IV creuse sans suivi.\n- Hydrogels : plaies sèches, nécrose autolytique ; ne pas utiliser sur plaie très exsudative sans couverture absorbante.\n- Films polyuréthane : friction, stade I, fixations ; peu absorbants.\n\nPANSEMENTS ABSORBANTS :\n- Alginates (calcium) : exsudat modéré à abondant, cavités, hémorragies mineures localisées.\n- Hydrofibres (carboxyméthylcellulose) : exsudat vertical wicking, cavités peu profondes.\n- Mousses polyuréthane (PU) : exsudat modéré, protection talon, escarres III avec interface.\n\nINTERFACE ET FIXATION :\n- Contact layer silicone (Mepitel-type) : réduit trauma au changement, hypergranulation.\n- Éviter rubans sur peau fragile ; fixation alternée.\n\nPANSEMENTS ACTIFS / SPÉCIALISÉS :\n- Charbon pour odeur (plaies oncologiques, nécrose).\n- Argent (nanocristallin) : discuter infection locale, durée limitée, coût et cytotoxicité argent.\n- Protéases topiques, matrices collagène : selon protocole établissement.\n\nRÈGLES GÉRIATRIQUES :\n- Moins de changements douloureux si même efficacité (autolyse).\n- Coût et remboursement : documenter indication.\n- Allergie colophane, latex, certains adhésifs — peau fragile.\n\nERREURS FRÉQUENTES :\n- Mousse sur plaie sèche ; hydrocolloïde sur escarre infectée profonde ; compression sur artériel ; pansement occlus sur IAD macérée.',
    points_cles: ['Exsudat dicte absorbant vs hydrogel', 'Interface silicone = peau fragile', 'Pas d\'argent prolongé sans indication', 'Réévaluer à chaque changement']
  }
];