// Guides aidants — Soutien, droits et pratiques pour les proches aidants
const GUIDES_AIDANTS = [
  {
    id: 'aidant-1',
    titre: 'Comprendre la maladie de son proche',
    contenu: 'Comprendre la pathologie aide à anticiper l\'évolution, adapter l\'aide et réduire la culpabilité. L\'information doit être fiable et progressive.\n\nSOURCES FIABLES :\n- Médecin traitant, gériatre, neurologue selon la maladie.\n- Documents écrits remis à l\'hôpital (compte rendu de sortie, ordonnances).\n- Associations reconnues (France Alzheimer, APF, France Parkinson, etc.).\n- Éviter forums non modérés pour les décisions médicales.\n\nQUESTIONS UTILES AU MÉDECIN :\n- Diagnostic précis et stade actuel.\n- Évolution attendue à 6 mois, 1 an, 5 ans (fourchettes, pas certitudes absolues).\n- Traitements : bénéfices, effets secondaires, signes d\'alerte.\n- Qui contacter en urgence et quels examens suivre.\n\nMALADIES FRÉQUENTES CHEZ L\'AIDÉ :\n- Démence (Alzheimer et autres) : troubles mémoire, comportement, dépendance progressive.\n- AVC : séquelles motrices, langage, fatigue.\n- Parkinson : mobilité, chutes, fluctuations.\n- Insuffisance cardiaque, BPCO : essoufflement, œdèmes, fatigue.\n- Cancer : traitements, fatigue, douleur, fin de vie.\n\nIMPACT SUR LA RELATION :\n- La maladie n\'efface pas la personne ; capacités résiduelles à valoriser.\n- Acceptation progressive (deuil anticipé) souvent nécessaire.\n- Tenir un carnet de santé partagé (symptômes, poids, incidents).',
    points_cles: ['Médecin + associations = sources sûres', 'Poser questions sur évolution et urgences', 'Carnet de suivi des symptômes', 'Capacités résiduelles à valoriser']
  },
  {
    id: 'aidant-2',
    titre: 'Gérer les troubles du comportement',
    contenu: 'Agitation, refus de soins, errance et agressivité verbale touchent souvent les aidants. Ce ne sont pas des « caprices » mais des symptômes à décoder.\n\nRECHERCHER UNE CAUSE MÉDICALE :\n- Douleur, constipation, infection (urinaire fréquente), déshydratation.\n- Delirium aigu (fièvre, médicament nouveau).\n- Surdosage ou effet paradoxal de sédatifs, anticholinergiques.\n\nCOMMUNICATION :\n- Voix calme, phrases courtes, contact visuel.\n- Valider l\'émotion (« Je vois que vous êtes inquiet ») avant de proposer une action.\n- Éviter contradiction frontale et argumentation longue en démence.\n\nENVIRONNEMENT :\n- Bruit et foule réduits ; repères visuels (horloge, calendrier).\n- Routine stable ; annoncer les changements à l\'avance.\n- Activités occupationnelles aux moments à risque (fin d\'après-midi).\n\nSÉCURITÉ :\n- Retirer armes, allumettes, produits toxiques accessibles.\n- Verrous hauts si errance dangereuse (respecter code déontologique et libertés).\n- Plan d\'action si agression : se protéger, temporiser, appeler secours si danger.\n\nQUAND DEMANDER DE L\'AIDE :\n- Comportement nouveau ou brutal → consultation rapide.\n- Épuisement de l\'aidant → répit, avis spécialisé (gériatre, psychogériatrie).',
    points_cles: ['Toujours chercher douleur / infection', 'Valider l\'émotion avant d\'agir', 'Routine et moins de bruit', 'Comportement brutal = avis médical']
  },
  {
    id: 'aidant-3',
    titre: 'Prévenir l\'épuisement de l\'aidant',
    contenu: 'L\'épuisement (burn-out de l\'aidant) nuit à votre santé et à la qualité des soins. La prévention est un devoir, pas un luxe.\n\nSIGNES D\'ALERTE :\n- Fatigue chronique, troubles du sommeil, irritabilité.\n- Tristesse durable, sentiment d\'enfermement, colère contre le proche.\n- Négliger sa propre santé (repas, consultations).\n- Isolement social, culpabilité permanente.\n\nSTRATÉGIES CONCRÈTES :\n- Micro-pauses quotidiennes (10 min respiration, marche, thé).\n- Déléguer au moins une tâche récurrente (courses, ménage, nuit).\n- Fixer des limites réalistes (« je ne peux pas être disponible 24 h/24 »).\n- Maintenir un lien social hebdomadaire (ami, groupe aidants).\n\nORGANISATION :\n- Planning visible des soins et rendez-vous.\n- Liste des personnes pouvant intervenir en urgence.\n- Accepter l\'aide quand on la propose (pas seulement en crise).\n\nSANTÉ DE L\'AIDANT :\n- Consultation annuelle chez le médecin traitant.\n- Dépister dépression (PHQ-2 / PHQ-9 en consultation).\n- Activité physique régulière même légère.\n\nSI CRISE :\n- Numéros d\'écoute aidants, Maison des aidants, assistante sociale MDPH.\n- Hospitalisation temporaire du proche si vous êtes malade vous-même.',
    points_cles: ['10 min pour soi chaque jour', 'Déléguer une tâche récurrente', 'Accepter l\'aide proposée', 'Consultation annuelle pour l\'aidant']
  },
  {
    id: 'aidant-4',
    titre: 'Droits de l\'aidant en France',
    contenu: 'Les aidants disposent de droits reconnus par la loi. Les connaître permet de concilier vie professionnelle, personnelle et accompagnement.\n\nSTATUT ET RECONNAISSANCE :\n- Pas de « statut unique » mais cumul de dispositifs selon situation.\n- Déclaration en MDPH pour évaluation des besoins du proche (APA, etc.).\n- Carte « Mobilité inclusion » stationnement si handicap du proche accompagné.\n\nCONGÉS ET TRAVAIL :\n- Congé de proche aidant : jusqu\'à 3 mois renouvelable (conditions CNAV / employeur).\n- Congé de soutien familial (fin de vie) : dispositifs spécifiques selon conventions.\n- Aménagement du temps de travail : entretien avec employeur, télétravail partiel si accord.\n- Protection contre licenciement dans certains cas de congé aidant (se renseigner CCN).\n\nFORMATION :\n- Droit à la formation de l\'aidant (cours, ateliers MDPH, associations).\n- Repos sécurité si aidant conducteur professionnel (réglementation spécifique).\n\nDOCUMENTS UTILES :\n- Procurations pour démarches administratives et bancaires.\n- Personne de confiance : rôle distinct de l\'aidant quotidien.\n- Mesure de protection (curatelle, tutelle) si incapacité juridique : ne pas confondre avec simple aide.\n\nOÙ S\'INFORMER :\n- MDPH du département, France Alzheimer, site service-public.fr « aidant ».',
    points_cles: ['Congé proche aidant jusqu\'à 3 mois', 'MDPH pour APA et évaluation', 'Personne de confiance ≠ aidant', 'service-public.fr / MDPH']
  },
  {
    id: 'aidant-5',
    titre: 'Soutien psychologique pour l\'aidant',
    contenu: 'Accompagner un proche âgé malade impacte la santé mentale. Le soutien psychologique n\'est pas une faiblesse mais un outil de pérennité.\n\nRÉACTIONS NORMALES :\n- Deuil anticipé, anxiété sur l\'avenir, colère, sentiment d\'injustice.\n- Conflits familiaux sur les décisions de soins.\n- Charge mentale (organisation, culpabilité si placement envisagé).\n\nFORMES DE SOUTIEN :\n- Entretiens avec psychologue (médecin traitant peut orienter).\n- Groupes de parole aidants (associations, hôpitaux).\n- Lignes d\'écoute anonymes.\n- Thérapies brèves focalisées stress (TCC, mindfulness adaptée).\n\nENFANTS ET PETITS-ENFANTS :\n- Expliquer la maladie à l\'âge de l\'enfant avec mots simples.\n- Ne pas tout faire porter sur un adolescent seul.\n\nCOUPLE :\n- La maladie d\'un parent peut réactiver tensions conjugales.\n- Temps à deux à préserver même brièvement.\n\nSIGNES POUR CONSULTER RAPIDEMENT :\n- Idées noires, sentiment d\'être « à bout » avec peur de ne plus contrôler.\n- Automédication alcool / anxiolytiques.\n- Troubles du sommeil ou de l\'appétit prolongés (> 3 semaines).\n\nPRISE EN CHARGE :\n- Remboursement séances psychologue sur orientation médecin (MonPsy selon critères).\n- Dispositifs locaux parfois gratuits via associations.',
    points_cles: ['Groupes de parole aidants', 'Deuil anticipé est fréquent', 'Consulter si idées noires', 'MonPsy / orientation médecin']
  },
  {
    id: 'aidant-6',
    titre: 'Aides financières et démarches',
    contenu: 'Les démarches administratives sont lourdes mais des aides existent pour le proche aidé et parfois pour l\'aidant. Anticiper et centraliser les documents.\n\nPOUR LA PERSONNE ÂGÉE DÉPENDANTE :\n- APA (Allocation personnalisée d\'autonomie) : via MDPH, selon GIR.\n- ASPA (ex-minimum vieillesse) si ressources modestes.\n- Majorations retraite, complémentaire santé, exonérations ticket modérateur selon situation.\n- Crédit d\'impôt emploi à domicile (aide ménagère, auxiliaire de vie).\n\nAIDE AU LOGEMENT ET ADAPTATION :\n- Anah, agences locales : subventions adaptation domicile (rampe, barres, douche).\n- Téléassistance, portage repas : tarifs variables, aides locales.\n\nINDEMNISATION ARRÊT DE TRAVAIL AIDANT :\n- Indemnités journalières si arrêt maladie de l\'aidant (conditions Assurance maladie).\n- Congés sans solde vs congé proche aidant : comparer impact revenus.\n\nDOCUMENTS À RASSEMBLER :\n- Pièce d\'identité, livret de famille, avis d\'imposition, RIB.\n- Certificats médicaux (GIR, ALD si applicable).\n- Devis pour travaux ou devis prestataires à domicile.\n\nCONSEILS PRATIQUES :\n- Un classeur ou dossier numérique par thème (santé, MDPH, banque).\n- Assistante sociale hospitalière ou CCAS pour premier niveau d\'aide aux dossiers.\n- Vérifier éligibilité chaque année (ressources, situation).',
    points_cles: ['APA via MDPH selon GIR', 'Crédit impôt emploi à domicile', 'Dossier documents centralisé', 'CCAS / assistante sociale']
  },
  {
    id: 'aidant-7',
    titre: 'Le répit : s\'absenter sans culpabilité',
    contenu: 'Le répit permet à l\'aidant de récupérer et au proche de bénéficier d\'autres interlocuteurs. C\'est une composante du parcours de soins, pas un abandon.\n\nFORMES DE RÉPIT :\n- Accueil de jour (centre, association) quelques demi-journées par semaine.\n- Hébergement temporaire (EHPAD, unité répit) quelques jours à quelques semaines.\n- Auxiliaire de vie ou aide à domicile à domicile pendant que l\'aidant sort.\n- Famille ou voisin formé aux gestes de base.\n\nPRÉPARER UNE ABSENCE :\n- Fiche médicale : traitements, allergies, contacts médecin.\n- Habitudes (repas, sommeil, objets rassurants).\n- Consentement du proche si possible ; explication simple si démence.\n\nFINANCEMENT :\n- APA peut financer une partie des heures à domicile ou accueil.\n- Certaines mutuelles ou fonds locaux (répit Alzheimer).\n- Participation familiale selon budget.\n\nGÉRER LA CULPABILITÉ :\n- Un aidant reposé offre de meilleurs soins sur la durée.\n- Anticiper le répit avant la crise (plan annuel).\n\nRETOUR APRÈS RÉPIT :\n- Échanger avec les professionnels (comportement, alimentation).\n- Ajuster le plan si besoin.',
    points_cles: ['Répit planifié avant la crise', 'Fiche médicale + habitudes', 'APA peut financer heures', 'Aidant reposé = meilleurs soins']
  },
  {
    id: 'aidant-8',
    titre: 'Communiquer avec le proche et l\'équipe soignante',
    contenu: 'Une communication claire limite les malentendus, protège la relation et améliore la continuité des soins entre domicile, hôpital et ville.\n\nAVEC LE PROCHE :\n- Adapter le langage (auditif, cognitif) ; patience, silences.\n- Éviter de parler « à la place » de la personne si elle est présente.\n- Décisions médicales : impliquer selon capacité de discernement (protection juridique si incapacité).\n\nAVEC LES PROFESSIONNELS :\n- Préparer les consultations : liste de questions, carnet de symptômes, ordonnances.\n- Un interlocuteur familial désigné pour éviter messages contradictoires.\n- Demander compte rendu écrit après hospitalisation.\n\nENTRE FRÈRES ET SŒURS :\n- Répartition des tâches écrite (même simple tableau).\n- Réunions familiales courtes et factuelles ; médiation si blocage.\n- Reconnaître que l\'aidant principal supporte une charge invisible.\n\nANNONCES DIFFICILES :\n- Placement, arrêt de traitement : concertation médicale, plusieurs temps de discussion.\n- Ne pas imposer une vérité brutale si le proche ne la demande pas (personnalisation).\n\nOUTILS :\n- Cahier de liaison domicile / EHPAD.\n- Applications de messagerie avec IDE si proposé par la structure.\n- Compte Ameli proche si procuration acceptée.',
    points_cles: ['Carnet pour les consultations', 'Un porte-parole famille', 'Répartition écrite des tâches', 'Cahier de liaison si EHPAD']
  },
  {
    id: 'aidant-9',
    titre: 'Sécurité du domicile et prévention des chutes',
    contenu: 'Les chutes sont la première cause d\'accident domestique chez les seniors. L\'aidant joue un rôle clé dans l\'adaptation du logement et la surveillance des risques.\n\nAMÉNAGEMENT :\n- Supprimer tapis mobiles, fils au sol, encombrement couloirs.\n- Éclairage suffisant (interrupteurs accessibles, veilleuses).\n- Barres d\'appui salle de bain, siège douche, antidérapant baignoire/douche.\n- Escaliers : main courante des deux côtés, marquage des nez de marche.\n\nÉQUIPEMENTS :\n- Déambulateur ou canne réglés à la bonne hauteur (orthésiste, kiné).\n- Lit à bonne hauteur pour transferts ; potence si prescrite.\n- Chaussures fermées, antidérapantes, pas de chaussons lisses.\n\nCOMPORTEMENTS À RISQUE :\n- Se lever la nuit sans aide ; précipitation aux toilettes.\n- Poly médication sédatrice, alcool, hypotension orthostatique.\n- Essoufflement, jambe faible post-AVC.\n\nPLAN D\'ACTION CHUTE :\n- Si chute : ne pas déplacer brutalement si douleur membre ; appeler 15 si trauma tête, douleur intense, incapacité à se lever.\n- Téléassistance ou bracelet d\'appel.\n- Numéros urgence affichés près du téléphone.\n\nPRÉVENTION PASSIVE :\n- Révision annuelle du logement avec ergothérapeute ou OT si possible.\n- Lunettes à jour, éclairage adapté, traitement de l\'incontinence (courses nocturnes).',
    points_cles: ['Couloirs dégagés + éclairage', 'Chaussures fermées antidérapantes', '15 si trauma crânien', 'Déambulateur bien réglé']
  },
  {
    id: 'aidant-10',
    titre: 'Accompagner la fin de vie à domicile',
    contenu: 'La fin de vie peut se dérouler à domicile avec un réseau de soins. L\'aidant a besoin d\'anticipation, de soutien et d\'un cadre légal clair.\n\nANTICIPATION :\n- Directives anticipées et personne de confiance à jour.\n- Discussion avec le médecin : objectifs de soins (palliatif, limitation thérapeutique).\n- Choix du lieu (domicile, EHPAD, unité de soins palliatifs) réévaluable.\n\nÉQUIPE MOBILE :\n- Médecin traitant, IDE libérale, structure palliative (SAAD, équipe mobile).\n- Pharmacie pour morphine et antalgiques majeurs (ordonnances sécurisées).\n- Numéros d\'urgence et plan médicalisé affiché.\n\nSOINS DE CONFORT :\n- Douleur, dyspnée, nausées, bouche sèche : signalement rapide, pas d\'héroïsme silencieux.\n- Position, hygiène douce, présence, rituels spirituels ou culturels.\n- Alimentation : plaisir si possible ; pas forcer si refus en phase terminale (cadre médical).\n\nSOUS LE STRESS :\n- Permanence téléphonique palliatifs.\n- Répit pour l\'aidant même en fin de vie (nuit sécurisée).\n- Enfants : accompagnement adapté à l\'âge.\n\nAPRÈS LE DÉCÈS :\n- Médecin pour constat ; pas de précipitation.\n- Démarches administratives (CPAM, caisse retraite) : liste sur service-public.\n- Deuil de l\'aidant : suivis prolongés souvent nécessaires.',
    points_cles: ['Directives anticipées à jour', 'Équipe palliative + IDE', 'Signaler douleur et dyspnée', 'Deuil aidant souvent long']
  }
];