// Guides troubles du sommeil gériatrique — Évaluation et prise en charge clinique
const GUIDES_SOMMEIL = [
  {
    id: 'gs-1',
    titre: 'Insomnie du sujet âgé',
    contenu: 'L\'insomnie touche 30 à 50 % des personnes de plus de 65 ans. Elle augmente chutes, confusion, dépression et usage excessif d\'hypnotiques. Le diagnostic repose sur l\'anamnèse (aidant utile) et l\'exclusion des causes organiques ou iatrogènes.\n\nDÉFINITION ET SOUS-TYPES :\n- Difficulté d\'endormissement, réveils nocturnes, réveil précoce ou sommeil non réparateur ≥ 3 nuits/semaine depuis ≥ 3 mois avec retentissement diurne.\n- Insomnie d\'endormissement : anxiété, douleur, environnement, sieste tardive.\n- Réveils nocturnes : nycturie, SAOS, douleur, démence, délirium.\n- Réveil matinal précoce : dépression, avancée de phase (vieillissement).\n\nCAUSES FRÉQUENTES CHEZ LE SENIOR :\n- Médicamenteuses : corticoïdes, diurétiques en soirée, théophylline, psychotropes en sevrage.\n- Polypathologie : arthrose, BPCO, reflux, IC, démence, dépression.\n- Facteurs comportementaux : alcool, caféine tardive, écrans, lit utilisé pour activités non sommeil.\n- Environnement EHPAD : bruit, lumière, changements d\'équipe.\n\nÉVALUATION :\n- Agenda du sommeil 2 semaines ; échelles ISI, Pittsburgh adaptée.\n- Recherche SAOS, RLS, dépression (GDS), douleur, nycturie.\n- Revue médicamenteuse systématique (anticholinergiques, BZD).\n\nPRISE EN CHARGE (cascade HAS) :\n- 1re ligne : hygiène du sommeil, TCC-I brève (stimulus control, restriction du temps au lit), traiter cause (douleur, reflux).\n- Mélatonine LP 2 mg si avancée de phase ; éviter BZD et Z-drugs au long cours (chutes, dépendance, cognition).\n- Orexin antagonistes (lemborexant) : prudence chutes et conduite ; pas 1re intention chez fragile.\n- En EHPAD : horaires stables, réduction stimulations nocturnes, toilettes programmées.',
    points_cles: ['Agenda sommeil + revue médicaments', 'TCC-I et hygiène avant hypnotique', 'Réveil précoce = dépression?', 'Éviter BZD chroniques après 65 ans']
  },
  {
    id: 'gs-2',
    titre: 'Apnées du sommeil (SAOS) chez le sujet âgé',
    contenu: 'Le syndrome d\'apnées-hypopnées obstructives du sommeil (SAOS) concerne 20 à 70 % des seniors selon les critères ; il est sous-diagnostiqué car les symptômes sont attribués au « vieillissement normal ».\n\nMÉCANISME ET CONSÉQUENCES :\n- Collapsus pharyngé répété → hypoxies, micro-éveils, fragmentation du sommeil.\n- HTA résistante, FA, IC, AVC, diabète type 2, troubles cognitifs et démence.\n- Somnolence diurne → chutes, accidents ; risque peropératoire.\n\nTABLEAU CLINIQUE GÉRIATRIQUE :\n- Ronflement (témoin), pauses respiratoires observées, réveils en sursaut.\n- Somnolence passive (sieste longue, somnolence devant télévision) plus que somnolence active.\n- Nycturie, céphalées matinales, irritabilité, baisse concentration.\n- Obésité moins constante qu\'à l\'âge moyen ; IMC normal n\'exclut pas SAOS.\n\nDÉPISTAGE ET DIAGNOSTIC :\n- Questionnaires STOP-BANG, NoSAS ; oxymétrie nocturne si accès limité (SpO2 < 90 % ≥ 30 % du temps = forte suspicion).\n- Polysomnographie ou polygraphie ventilatoire selon contexte.\n- Apnée centrale et Cheyne-Stokes : IC, opioïdes ; adaptation PPC différente.\n\nTRAITEMENT :\n- PPC (pression positive continue) = référence si IAH ≥ 15 avec symptômes ou comorbidités CV.\n- Adhésion : masques légers, humidificateur, suivi régulier ; aidant pour mise en place.\n- Perte de poids si surpoids ; éviter alcool et sédatifs nocturnes.\n- OAM (orthèse d\'avancée mandibulaire) si SAOS léger ou refus PPC.\n- Chirurgie rarement chez le très âgé ; évaluer bénéfice/risque individuel.',
    points_cles: ['STOP-BANG même si IMC normal', 'SAOS = HTA et cognition', 'PPC avec suivi adhésion', 'Opioïdes et IC = apnée centrale']
  },
  {
    id: 'gs-3',
    titre: 'Syndrome des jambes sans repos (SJSR)',
    contenu: 'Le SJSR (restless legs syndrome) touche 10 à 20 % des sujets de plus de 65 ans. Il se manifeste par une urge impérieuse à bouger les jambes, le soir et la nuit, avec retentissement majeur sur l\'insomnie et la qualité de vie.\n\nCRITÈRES DIAGNOSTIQUES :\n- Envie de bouger les jambes, souvent avec sensations désagréables (fourmillements, brûlures, « courant électrique »).\n- Aggravation au repos, amélioration partielle par le mouvement.\n- Circadien : pire en soirée/nuit.\n- Exclusion : crampes, neuropathie pure, claudication, douleur positionnelle.\n\nÉTIOLOGIES CHEZ L\'ÂGÉ :\n- Forme secondaire fréquente : carence fer (ferritine < 75 µg/L ou TSAT bas), IRC, diabète, neuropathie, grossesse (rare).\n- Médicaments : antiémétiques, antidépresseurs, antihistaminiques H1, lithium, inhibiteurs calcineurine.\n- Forme idiopathique avec antécédents familiaux possibles.\n\nBILAN :\n- Ferritine, coefficient saturation transferrine ; corriger même si Hb normale.\n- DFG, glycémie ; revue traitements ; PLMS sur polysomnographie si doute.\n\nTRAITEMENT :\n- Supplémentation fer per os (ou IV si malabsorption) si carence ; réévaluer symptômes à 2–3 mois.\n- Agonistes dopaminergiques (pramipexole, ropinirole) : doses minimales efficaces ; risque augmentation symptômes (augmentation) à long terme chez l\'âgé.\n- Gabapentine ou prégabaline (doses adaptées DFG) : souvent 1re ligne si neuropathie associée ou risque dopaminergique.\n- Éviter caféine et alcool le soir ; marche légère, étirements ; traiter douleur et anxiété contributives.\n- En EHPAD : noter agitation jambes comme SJSR traitable, pas seulement « comportement ».',
    points_cles: ['Ferritine < 75 = essai fer', 'Gabapentine si DFG ou neuropathie', 'Revoir antiémétiques et AD', 'Agitation nocturne jambes = SJSR']
  },
  {
    id: 'gs-4',
    titre: 'Hypersomnie et somnolence diurne excessive',
    contenu: 'La somnolence diurne excessive (SDE) n\'est pas normale avec l\'âge. Elle signale souvent SAOS, privation de sommeil, médicaments, dépression ou pathologie neurologique.\n\nDIFFÉRENCIATION CLINIQUE :\n- Fatigue : effort pour activité, pas de somnolence involontaire.\n- Somnolence : lutte contre le sommeil, micro-sommeils, siestes non planifiées.\n- Léthargie aiguë : délirium, infection, métabolique — urgence.\n\nCAUSES MAJEURES GÉRIATRIQUES :\n- Privation/fragmentation : insomnie, SAOS, douleur, soins nocturnes.\n- Médicamenteuses : BZD, opioïdes, antihistaminiques, antipsychotiques, gabapentinoïdes.\n- Neurologiques : MP, corps de Lewy, narcolepsie tardive (rare), séquelles AVC.\n- Psychiatriques : dépression masquée (« je dors tout le temps »).\n- Métaboliques : hypothyroïdie, hyponatrémie, hypercapnie (BPCO + SAOS).\n\nÉVALUATION :\n- Epworth Sleepiness Scale ; entretien aidant (siestes, somnolence au volant ou aux repas).\n- Polysomnographie si SAOS ou PLMS suspectés.\n- TSH, NFS, DFG ; dépistage dépression ; revue complète des psychotropes.\n\nTRAITEMENT :\n- Traiter la cause : PPC, hygiène sommeil, déprescription sédatifs, antidépresseur si dépression.\n- Modafinil ou pitolisant : réservés narcolepsie ou SDE résiduelle documentée après optimisation ; interactions et arythmie — prudence cardiaque.\n- Planifier sieste courte (20 min) si culturelle et sans impact nocturne.\n- Sécurité : conduite, cuisine, chutes ; évaluer capacité à rester seul.\n- Ne pas masquer SDE par stimulants sans diagnostic étiologique.',
    points_cles: ['SDE n\'est pas « normal » à 80 ans', 'Epworth + polysomnographie si besoin', 'Déprescription sédatifs prioritaire', 'Modafinil seulement étiologie clarifiée']
  },
  {
    id: 'gs-5',
    titre: 'Parasomnies du sujet âgé',
    contenu: 'Les parasomnies regroupent comportements anormaux en sommeil (éveil partiel, REM). Chez le senior, elles posent problème de sécurité (chutes du lit, violence envers le conjoint) et de diagnostic différentiel avec délirium nocturne.\n\nPRINCIPALES ENTITÉS :\n- Terreurs nocturnes : cri, peur, tachycardie, amnésie ; surtout début de nuit (N3). Enfant classique mais possible à tout âge ; stress, SAOS.\n- Somnambulisme et confusional arousals : lever du lit, gestes automatiques ; antécédents jeunesse, privation sommeil, BZD, SAOS.\n- RBD (trouble comportemental du sommeil REM) : enactment des rêves, coups, chutes ; lien fort MP, corps de Lewy, atrophie multisystématisée.\n- Cauchemars fréquents : PTSD, dépression, médicaments (bêta-bloquants, dopaminergiques).\n\nDIAGNOSTIC DIFFÉRENTIEL :\n- Épilepsie nocturne frontale : stéréotypé, court, plusieurs fois par nuit.\n- Délirium nocturne : fluctuation, attention altérée le jour, cause aiguë.\n- Agitation psychiatrique ou douleur non traitée en institution.\n\nEXPLORATION :\n- Témoin indispensable ; vidéo smartphone utile.\n- Polysomnographie avec vidéo si RBD ou épilepsie suspectée.\n- IRM cérébrale si atypie neurologique ; DATscan si parkinsonisme.\n\nTRAITEMENT ET SÉCURITÉ :\n- RBD : mélatonine 3–12 mg ou clonazépam 0,5 mg (prudence chutes, SAOS) ; retirer lit conjoint si danger ; protéger fenêtres, objets tranchants.\n- Traiter SAOS souvent associé.\n- Éviter antidépresseurs ISRS aggravant RBD si alternative possible.\n- Somnambulisme : sécuriser domicile, réveil programmé parfois ; pas de contention sans cadre légal.\n- Informer aidants : ce n\'est pas volontaire ; risque transition démence à corps de Lewy.',
    points_cles: ['RBD = Lewy/Parkinson jusqu\'à preuve contraire', 'Vidéo + témoin pour diagnostic', 'Sécuriser chambre avant médicament', 'Délirium vs parasomnie = attention diurne']
  },
  {
    id: 'gs-6',
    titre: 'Troubles du rythme circadien chez le sujet âgé',
    contenu: 'Le vieillissement avance la phase de sommeil (couche-tôt / lève-tôt) et affaiblit l\'amplitude circadienne. Les troubles du rythme aggravent insomnie, confusion et agitation en EHPAD.\n\nPHYSIOLOGIE DU VIEILLISSEMENT :\n- Avancée de phase : pic mélatonine plus tôt, réveil 4h–5h difficile à compenser.\n- Siestes multiples → fragmentation et baisse pression de sommeil nocturne.\n- Réduction sensibilité à la lumière → horloge interne moins synchronisée.\n\nSYNDROMES CLINIQUES :\n- Syndrome de l\'oiseau matinal (advanced sleep phase) : endormissement 19h–21h, réveil 3h–5h.\n- Rythme irrégulier : démence, institution, absence d\'activité structurée.\n- Non-24h rare ; confusion jour/nuit en démence sévère.\n- Travail posté ou voyages : moins fréquent mais mal toléré.\n\nÉVALUATION :\n- Actigraphie 1–2 semaines ou agenda horaires coucher/levé/siestes.\n- Rechercher dépression (réveil précoce), douleur, SAOS.\n\nINTERVENTIONS :\n- Lumière vive le matin (30–45 min, 2500–10000 lux selon tolérance) ; éviter lumière bleue forte le soir.\n- Activité physique matinale ; stimulation sociale diurne.\n- Limiter sieste > 30 min et après 15 h.\n- Mélatonine faible dose le soir (0,5–2 mg) si phase avancée invalidante ; horaire fixe.\n- Chronothérapie légère (reculer progressivement heure coucher) sous suivi.\n- EHPAD : éclairage corridor modéré la nuit, activités diurnes, minimiser soins à 2h sauf nécessité.',
    points_cles: ['Lumière matinale = synchronisation', 'Sieste courte et avant 15 h', 'Réveil 4h : avancée phase vs dépression', 'Actigraphie si doute sur rythme']
  },
  {
    id: 'gs-7',
    titre: 'Hygiène du sommeil en gériatrie',
    contenu: 'L\'hygiène du sommeil est le socle de toute prise en charge des troubles du sommeil chez le senior. Elle est efficace, sans effet indésirable iatrogène, et doit être réévaluée à chaque consultation.\n\nENVIRONNEMENT :\n- Chambre fraîche (18–20 °C), sombre, calme ; boules quies, rideaux occultants.\n- Matelas adapté douleurs ; literie uniquement pour sommeil et intimité (pas télévision prolongée au lit).\n- Veilleuses vers toilettes ; tapis antidérapants.\n\nHORAIRES ET STIMULUS CONTROL :\n- Lever et coucher à heures fixes ± 30 min, y compris week-end.\n- Se coucher seulement si somnolence ; si éveil > 20 min, lever pour activité calme puis retour quand somnolent.\n- Pas de « sieste de rattrapage » longue en fin d\'après-midi.\n\nALIMENTATION ET SUBSTANCES :\n- Dîner léger 2–3 h avant coucher ; éviter repas copieux et reflux.\n- Limiter café, thé, cola après 14 h ; alcool fragmente le sommeil (éviter comme sédatif).\n- Hydratation diurne ; moduler liquides soir si nycturie (accord médical).\n\nACTIVITÉ ET LUMIÈRE :\n- Exposition lumière naturelle le matin ; marche ou exercice modéré en journée (pas intense tard le soir).\n- Routine coucher 30–45 min : toilettes, soins, lecture, musique douce — mêmes étapes chaque soir.\n\nDÉMENCE ET EHPAD :\n- Même routine verbale et spatiale ; réduire bruit et lumière forte la nuit.\n- Valoriser calme sans isolement excessif le jour.\n- Former équipes : ne pas réveiller systématiquement pour soins non urgents.',
    points_cles: ['Heures fixes coucher/lever', 'Lit = sommeil seulement', 'Lumière le matin, obscurité le soir', 'Routine identique chaque nuit']
  },
  {
    id: 'gs-8',
    titre: 'Médicaments et sommeil chez le sujet âgé',
    contenu: 'La polymédication perturbe l\'architecture du sommeil et augmente chutes, confusion et dépendance. Chaque prescription hypnotique ou sédatif doit être justifiée et réévaluée.\n\nMÉDICAMENTS QUI DÉGRADENT LE SOMMEIL :\n- Diurétiques en soirée → nycturie ; corticoïdes → insomnie.\n- Sympathomimétiques, théophylline, certains anti-PDE5.\n- ISRS, psychostimulants, bupropion → retard d\'endormissement.\n- Opioïdes : fragmentation, apnées centrales.\n\nMÉDICAMENTS SÉDATIFS À RISQUE :\n- Benzodiazépines et Z-drugs (zolpidem, zopiclone) : chutes, fractures, délirium, conduite ; demi-vie courte préférable si usage bref (< 4 semaines).\n- Antihistaminiques H1 1re génération, anticholinergiques : somnolence diurne et cognition.\n- Antipsychotiques « pour dormir » : non indiqués, effets métaboliques et mortels.\n\nTRAITEMENTS CIBLÉS DU SOMMEIL :\n- Mélatonine LP 2 mg : avancée de phase, institution ; interactions faibles.\n- Trazodone faible dose : parfois utilisée off-label ; orthostatisme et chutes.\n- Lemborexant/daridorexant : efficacité insomnie ; surveillance chutes chez fragile.\n- Gabapentinoïdes : douleur + sommeil mais sédation et dépendance possibles.\n\nDÉMARCHE STOPP / ANTICHOLINERGIC BURDEN :\n- Raisonner chaque psychotrope nocturne ; taper progressif BZD (diazépam équivalent lent).\n- Remplacer par TCC-I, hygiène, traitement douleur/SAOS/SJSR.\n- En EHPAD : audit prescriptions nocturnes lors de chaque entrée et réunion de synthèse.',
    points_cles: ['Revue médicamenteuse à chaque insomnie', 'BZD < 4 semaines si indispensable', 'Diurétique le matin pas le soir', 'Antipsychotique ≠ hypnotique']
  },
  {
    id: 'gs-9',
    titre: 'Sommeil et cognition chez le sujet âgé',
    contenu: 'Le sommeil participe à la consolidation mnésique et au clearance métabolique cérébrale. Chez le senior, troubles du sommeil et déclin cognitif s\'entretiennent mutuellement ; le SAOS est un facteur de risque modifiable de démence.\n\nMÉCANISMES :\n- Sommeil lent profond et REM diminués avec l\'âge → mémoire déclarative et procédurale moins consolidées.\n- Hypoxies nocturnes répétées (SAOS) : atteinte hippocampique, microstructuralle, biomarqueurs amyloïde.\n- Privation aiguë : attention, exécutif, humeur le lendemain ; chronique : risque démence accru.\n\nCLINIQUE :\n- Patient ou aidant : « brouillard », oublis, lenteur diurne après nuits fragmentées.\n- Confusion matinale vs délirium : temporalité et fluctuation.\n- Corps de Lewy : RBD peut précéder démence de années.\n\nÉVALUATION COORDONNÉE :\n- MMS/MoCA + agenda sommeil ; dépistage SAOS si HTA + ronflement + plis cutanés cognitifs.\n- Médicaments anticholinergiques et BZD à réduire (effet cognitif documenté).\n\nINTERVENTIONS :\n- Traiter SAOS (PPC) : amélioration attention et qualité de vie ; études sur progression cognitive en cours.\n- Hygiène sommeil et activité physique diurne.\n- Stabiliser horaires en démence légère (réduire agitation et errance nocturne).\n- Éviter hypnosedatives au long cours ; privilégier mélatonine et approches non médicamenteuses.\n- Recherche : sommeil comme cible prévention démence (optimisation durée 7–8 h chez senior en bonne santé).',
    points_cles: ['SAOS traité = cognition potentiellement préservée', 'RBD avant Lewy de plusieurs années', 'Anticholinergiques aggravent mémoire', 'Nuit fragmentée = brouillard diurne']
  },
  {
    id: 'gs-10',
    titre: 'Sommeil et vieillissement physiologique',
    contenu: 'Le sommeil change avec l\'âge sans qu\'un trouble pathologique soit toujours présent. Distinguer vieillissement normal, habitudes défavorables et maladie évite la surmédicalisation et oriente les soins pertinents.\n\nMODIFICATIONS PHYSIOLOGIQUES :\n- Augmentation éveils spontanés, diminution sommeil lent profond et REM (pourcentages, pas toujours durée totale).\n- Latence d\'endormissement légèrement plus longue ; efficacité sommeil parfois < 85 % sans symptôme diurne.\n- Avancée de phase et baisse amplitude circadienne (voir guide rythme).\n\nCE QUI N\'EST PAS « NORMAL » :\n- Ronflement avec pauses, somnolence involontaire, suffocation nocturne.\n- Insomnie sévère persistante, agitation nocturne violente, perte de 2 h de sommeil avec handicap.\n- Hypersomnie diurne > 1 h involontaire ou micro-sommeils dangereux.\n\nBESOINS EN SOMMEIL :\n- Recommandations souvent 7–8 h pour senior en bonne santé ; interindividuel.\n- Qualité et continuité plus importantes que chiffre obsessionnel d\'heures.\n\nAPPROCHE GLOBALE GÉRIATRIQUE :\n- Intégrer sommeil dans évaluation gériatrique (chutes, autonomie, humeur).\n- Adapter attentes : objectif fonction diurne, pas perfection nocturne.\n- Soutien aidants : réveils nocturnes et épuisement ; répit, formation hygiène sommeil.\n- Fin de vie : priorités confort, douleur, agitation ; simplifier objectifs sommeil.\n\nPRÉVENTION :\n- Activité physique régulière, lien social, gestion CV et métabolique.\n- Dépistage SAOS si facteurs de risque avant déclin majeur.\n- Limiter iatrogénie somnolence dès le début de la prise en charge gériatrique.',
    points_cles: ['Éveils légers peuvent être physiologiques', 'Ronflement + pauses = pathologique', 'Objectif = journée fonctionnelle', 'Sommeil dans évaluation gériatrique globale']
  }
];