// Items EVC — Liste complète des items de gériatrie avec objectifs
const ITEMS_EVC = [
  { id: 'item-121', titre: 'Évaluation de l\'autonomie', chapitre: 'ch3', rang: 'A',
    objectifs: ['Connaître les échelles ADL et IADL', 'Évaluer l\'autonomie fonctionnelle', 'Identifier les facteurs de perte d\'autonomie'] },
  { id: 'item-123', titre: 'Comprendre le vieillissement', chapitre: 'ch1', rang: 'A',
    objectifs: ['Définir le vieillissement physiologique vs pathologique', 'Connaître les mécanismes cellulaires', 'Comprendre la vulnérabilité liée à l\'âge'] },
  { id: 'item-128', titre: 'Ostéoporose et fractures', chapitre: 'ch6', rang: 'A',
    objectifs: ['Diagnostiquer l\'ostéoporose (DEXA, T-score)', 'Connaître le FRAX', 'Prescrire un traitement adapté', 'Prévenir les fractures'] },
  { id: 'item-130', titre: 'Troubles sensoriels', chapitre: 'ch5', rang: 'A',
    objectifs: ['Diagnostiquer presbyacousie et presbytie', 'Connaître l\'impact sur l\'autonomie', 'Prescrire appareillage adapté'] },
  { id: 'item-131', titre: 'Chutes et marche', chapitre: 'ch12', rang: 'A',
    objectifs: ['Évaluer le risque de chute (Tinetti)', 'Identifier les facteurs de risque', 'Mettre en place une prévention complète'] },
  { id: 'item-133', titre: 'Incontinence urinaire', chapitre: 'ch15', rang: 'A',
    objectifs: ['Identifier le type d\'incontinence', 'Prescrire le traitement adapté', 'Connaître la rééducation périnéale'] },
  { id: 'item-139', titre: 'Soins palliatifs', chapitre: 'ch17', rang: 'A',
    objectifs: ['Connaître la loi Claeys-Leonetti', 'Identifier les indications de soins palliatifs', 'Prescrire une sédation terminale'] },
  { id: 'item-228', titre: 'Arthrose', chapitre: 'ch7', rang: 'A',
    objectifs: ['Diagnostiquer l\'arthrose', 'Prescrire un traitement adapté au sujet âgé', 'Connaître les indications chirurgicales'] },
  { id: 'item-230', titre: 'Nutrition', chapitre: 'ch14', rang: 'A',
    objectifs: ['Évaluer l\'état nutritionnel (MNA)', 'Diagnostiquer la dénutrition', 'Prescrire une renutrition adaptée'] },
  { id: 'item-23', titre: 'Troubles neurocognitifs', chapitre: 'ch9', rang: 'A',
    objectifs: ['Diagnostiquer les démences (MMS, bilan)', 'Connaître les types de démences', 'Prescrire un traitement adapté'] },
  { id: 'item-108', titre: 'Confusion', chapitre: 'ch11', rang: 'A',
    objectifs: ['Diagnostiquer le delirium (CAM)', 'Identifier les causes', 'Prescrire un traitement adapté'] },
  { id: 'item-109', titre: 'Douleur', chapitre: 'ch8', rang: 'A',
    objectifs: ['Évaluer la douleur (EVA, ECPA)', 'Prescrire une antalgie adaptée', 'Connaître les spécificités gériatriques'] },
  { id: 'item-9', titre: 'Éthique et protection', chapitre: 'ch4', rang: 'A',
    objectifs: ['Connaître les lois Kouchner et Leonetti', 'Identifier les situations éthiques', 'Respecter l\'autonomie du patient'] },
  { id: 'item-322', titre: 'Prescription chez le sujet âgé', chapitre: 'ch16', rang: 'A',
    objectifs: ['Connaître les critères de Beers', 'Identifier la cascade iatrogénique', 'Déprescrire les médicaments inappropriés'] },
  { id: 'item-325', titre: 'Polymédication', chapitre: 'ch16', rang: 'A',
    objectifs: ['Évaluer la polymédication', 'Identifier les interactions', 'Simplifier les traitements'] }
];
