// Items EVC — Liste complète des items de gériatrie avec objectifs (alignés sur le programme officiel EDN/R2C et le livre CEN)
const ITEMS_EVC = [
  { id: 'item-123', titre: 'Vieillissement normal', chapitre: 'ch1', rang: 'A',
    objectifs: ['Définir le vieillissement physiologique vs pathologique', 'Connaître les mécanismes cellulaires (télomères, protéostasie)', 'Comprendre la vulnérabilité liée à l\'âge'] },
  { id: 'item-130', titre: 'La personne âgée malade : particularités sémiologiques', chapitre: 'ch2', rang: 'A',
    objectifs: ['Comprendre le modèle de décompensation de Bouchon (1+2+3)', 'Connaître le concept de cascade gériatrique', 'Identifier les particularités de la sémiologie d\'emprunt'] },
  { id: 'item-121', titre: 'Évaluation de l\'autonomie et de la fragilité', chapitre: 'ch3', rang: 'A',
    objectifs: ['Connaître les échelles ADL et IADL', 'Évaluer la fragilité selon les critères de Fried (≥ 3 = fragile)', 'Mettre en place une évaluation gériatrique standardisée (EGS)'] },
  { id: 'item-9', titre: 'Éthique et protection', chapitre: 'ch4', rang: 'A',
    objectifs: ['Connaître les notions de directives anticipées et de personne de confiance', 'Connaître les cadres des lois Kouchner et Leonetti', 'Respecter l\'autonomie du patient vulnérable'] },
  { id: 'item-81', titre: 'Troubles sensoriels : Audition', chapitre: 'ch5', rang: 'A',
    objectifs: ['Diagnostiquer la presbyacousie', 'Connaître l\'impact de la surdité sur l\'autonomie et l\'isolement social', 'Prescrire un appareillage auditif adapté'] },
  { id: 'item-89', titre: 'Troubles sensoriels : Vision', chapitre: 'ch5', rang: 'A',
    objectifs: ['Diagnostiquer la presbytie et la cataracte', 'Évaluer le retentissement visuel sur le risque de chute', 'Connaître les principes de correction optique et chirurgicale'] },
  { id: 'item-128', titre: 'Ostéoporose et fractures', chapitre: 'ch6', rang: 'A',
    objectifs: ['Diagnostiquer l\'ostéoporose (DEXA, T-score ≤ -2,5)', 'Utiliser et interpréter le score FRAX', 'Prescrire un traitement adapté et prévenir les fractures'] },
  { id: 'item-228', titre: 'Arthrose', chapitre: 'ch7', rang: 'A',
    objectifs: ['Diagnostiquer la gonarthrose et la coxarthrose', 'Prescrire un traitement antalgique adapté (éviter les AINS)', 'Connaître les indications de prise en charge chirurgicale (prothèses)'] },
  { id: 'item-134', titre: 'Douleur chez le sujet âgé', chapitre: 'ch8', rang: 'A',
    objectifs: ['Évaluer la douleur chez le sujet communicant (EVA) et non communicant (ECPA)', 'Prescrire une antalgie adaptée aux spécificités gériatriques', 'Éviter les effets iatrogènes majeurs des antalgiques'] },
  { id: 'item-108-cog', titre: 'Troubles neurocognitifs (Démences)', chapitre: 'ch9', rang: 'A',
    objectifs: ['Diagnostiquer les démences (Alzheimer, Lewy, vasculaire)', 'Connaître les examens complémentaires clés (MMS, MoCA, IRM)', 'Prescrire une prise en charge médico-sociale adaptée'] },
  { id: 'item-122', titre: 'Dépression chez le sujet âgé', chapitre: 'ch10', rang: 'A',
    objectifs: ['Dépister la dépression gériatrique avec l\'échelle GDS-15 (Yesavage)', 'Différencier dépression et pseudo-démence dépressive', 'Prescrire un traitement antidépresseur adapté (ISRS)'] },
  { id: 'item-108-conf', titre: 'Confusion et syndrome confusionnel', chapitre: 'ch11', rang: 'A',
    objectifs: ['Diagnostiquer le delirium aigu (critères de la CAM)', 'Identifier les causes médicales sous-jacentes (DIAPPERS)', 'Prescrire un traitement étiologique et éviter les contentions physiques'] },
  { id: 'item-131', titre: 'Chutes chez le sujet âgé', chapitre: 'ch12', rang: 'A',
    objectifs: ['Évaluer le risque de chute (Tinetti < 19, test TUG > 20s)', 'Identifier les facteurs de risque intrinsèques et extrinsèques', 'Mettre en place une prévention secondaire pluridisciplinaire'] },
  { id: 'item-124', titre: 'Syndrome d\'immobilisation et escarres', chapitre: 'ch13', rang: 'A',
    objectifs: ['Connaître les complications aiguës et chroniques de l\'alitement (thromboemboliques, escarres)', 'Prévenir le syndrome d\'immobilisation', 'Mettre en place des mesures de prévention des escarres (échelle de Braden)'] },
  { id: 'item-230', titre: 'Dénutrition et évaluation nutritionnelle', chapitre: 'ch14', rang: 'A',
    objectifs: ['Évaluer l\'état nutritionnel gériatrique avec l\'échelle MNA (< 17 = dénutrition)', 'Diagnostiquer la dénutrition selon les critères HAS (albumine, perte de poids)', 'Prescrire une renutrition orale ou entérale adaptée'] },
  { id: 'item-125', titre: 'Incontinence urinaire', chapitre: 'ch15', rang: 'A',
    objectifs: ['Identifier le type d\'incontinence (effort, impériosité, mixte)', 'Prescrire le traitement adapté (rééducation, anticholinergiques à surveiller)', 'Connaître les facteurs favorisants gériatriques'] },
  { id: 'item-322', titre: 'Particularités prescriptives chez le sujet âgé', chapitre: 'ch16', rang: 'A',
    objectifs: ['Connaître les critères de Beers et les listes STOPP/START', 'Identifier la cascade iatrogénique', 'Déprescrire les molécules potentiellement inappropriées'] },
  { id: 'item-325', titre: 'Polymédication et déprescription', chapitre: 'ch16', rang: 'A',
    objectifs: ['Évaluer la polymédication (≥ 5 molécules quotidiennes)', 'Réduire le risque iatrogène par la conciliation médicamenteuse', 'Simplifier les schémas thérapeutiques chez la personne âgée vulnérable'] },
  { id: 'item-141', titre: 'Soins palliatifs et fin de vie', chapitre: 'ch17', rang: 'A',
    objectifs: ['Connaître le cadre de la loi Claeys-Leonetti', 'Désigner la personne de confiance et rédiger des directives anticipées', 'Prescrire une sédation profonde et continue jusqu\'au décès (SPCMD)'] }
];
