// Médicaments d'urgence — Référence rapide pour gardes
const MEDICAMENTS_URGENCE = [
  { id: 'mu-1', medicament: 'Adrénaline', indication: 'Arrêt cardiaque, anaphylaxie', dose_adulte: '1mg IV q3-5min (arrêt), 0.5mg IM (anaphylaxie)', dose_sujet_age: 'Même dose', voie: 'IV/IO/IM', effets_secondaires: 'Tachycardie, HTA, arythmie', contre_indications: 'Aucune en urgence', surveillance: 'ECG, PA, FC' },
  { id: 'mu-2', medicament: 'Atropine', indication: 'Bradycardie symptomatique', dose_adulte: '0.5mg IV q3-5min (max 3mg)', dose_sujet_age: '0.5mg IV (même dose)', voie: 'IV', effets_secondaires: 'Tachycardie, sécheresse buccale, rétention urinaire', contre_indications: 'Glaucome, adénome prostate', surveillance: 'ECG, FC' },
  { id: 'mu-3', medicament: 'Amiodarone', indication: 'FV/TV sans pouls', dose_adulte: '300mg IV bolus → 150mg si récidive', dose_sujet_age: 'Même dose', voie: 'IV', effets_secondaires: 'Hypotension, bradycardie, thyroïde', contre_indications: 'Bloc AV de haut degré', surveillance: 'ECG, PA, TSH' },
  { id: 'mu-4', medicament: 'Noradrénaline', indication: 'Choc septique', dose_adulte: '0.1-0.5 µg/kg/min IV', dose_sujet_age: 'Démarrer plus bas (0.05 µg/kg/min)', voie: 'IV continue', effets_secondaires: 'Vasoconstriction, nécrose si extravasation', contre_indications: 'Hypovolémie non corrigée', surveillance: 'PA artérielle, débit urinaire' },
  { id: 'mu-5', medicament: 'Morphine', indication: 'Douleur sévère, OAP', dose_adulte: '0.1mg/kg SC/IV (douleur), 2-4mg IV (OAP)', dose_sujet_age: '0.05mg/kg SC/IV (réduire de 50%)', voie: 'SC/IV', effets_secondaires: 'Dépression respiratoire, nausées, constipation', contre_indications: 'FR < 12, GCS < 13', surveillance: 'FR, SpO2, conscience, douleur' },
  { id: 'mu-6', medicament: 'Midazolam', indication: 'Convulsions, agitation sévère', dose_adulte: '5mg IM (agitation), 2.5mg IV (convulsions)', dose_sujet_age: '2.5mg IM (réduire de 50%)', voie: 'IM/IV', effets_secondaires: 'Sédation, dépression respiratoire', contre_indications: 'FR < 10', surveillance: 'FR, SpO2, conscience' },
  { id: 'mu-7', medicament: 'Diazépam', indication: 'Convulsions', dose_adulte: '10mg IV lente ou rectal', dose_sujet_age: '5mg IV (réduire de 50%)', voie: 'IV/PR', effets_secondaires: 'Sédation, apnée', contre_indications: 'Myasthénie, insuffisance respiratoire', surveillance: 'FR, SpO2, conscience' },
  { id: 'mu-8', medicament: 'Furosémide', indication: 'OAP, hyperkaliémie', dose_adulte: '40-80mg IV', dose_sujet_age: '20-40mg IV (réduire)', voie: 'IV', effets_secondaires: 'Hypokaliémie, déshydratation, hypotension', contre_indications: 'Anurie, hypovolémie', surveillance: 'Diurèse, K, créatinine, PA' },
  { id: 'mu-9', medicament: 'Gluconate de calcium', indication: 'Hyperkaliémie, intoxication calcique', dose_adulte: '10mL de 10% IV en 2-5min', dose_sujet_age: 'Même dose', voie: 'IV', effets_secondaires: 'Bradycardie, nécrose si extravasation', contre_indications: 'Digitalique (précaution)', surveillance: 'ECG, Ca' },
  { id: 'mu-10', medicament: 'Insuline rapide', indication: 'Hyperkaliémie, acidocétose', dose_adulte: '10UI IV + glucose 50% 50mL', dose_sujet_age: '5-10UI IV + glucose', voie: 'IV', effets_secondaires: 'Hypoglycémie', contre_indications: 'Hypoglycémie', surveillance: 'Glycémie H1, H2, H4, K' },
  { id: 'mu-11', medicament: 'Hydrocortisone', indication: 'Choc surrénalien, anaphylaxie', dose_adulte: '200mg IV bolus', dose_sujet_age: '100mg IV (réduire)', voie: 'IV', effets_secondaires: 'Hyperglycémie, rétention hydrique', contre_indications: 'Aucune en urgence', surveillance: 'Glycémie, PA, Na' },
  { id: 'mu-12', medicament: 'Salbutamol', indication: 'Crise d\'asthme, BPCO', dose_adulte: '2.5mg nébulisation q20min', dose_sujet_age: '2.5mg (même dose)', voie: 'nébulisation', effets_secondaires: 'Tachycardie, tremblements', contre_indications: 'Aucune en urgence', surveillance: 'FC, SpO2, FR' },
  { id: 'mu-13', medicament: 'Naloxone', indication: 'Surdosage opioïde', dose_adulte: '0.4mg IV q2-3min (max 2mg)', dose_sujet_age: '0.1-0.2mg IV (dose réduite)', voie: 'IV', effets_secondaires: 'Douleur, agitation, sevrage', contre_indications: 'Aucune en urgence', surveillance: 'FR, conscience, douleur' },
  { id: 'mu-14', medicament: 'Vancomycine', indication: 'Infection à Gram+', dose_adulte: '1g IV q12h', dose_sujet_age: '15-20mg/kg IV q12h (adapter DFG)', voie: 'IV', effets_secondaires: 'Néphrotoxicité, rougeur (red man)', contre_indications: 'Allergie', surveillance: 'Créatinine, trough 15-20 µg/mL' },
  { id: 'mu-15', medicament: 'Ceftriaxone', indication: 'Infection grave', dose_adulte: '2g IV q24h', dose_sujet_age: '1-2g IV q24h (adapter DFG)', voie: 'IV', effets_secondaires: 'Allergie, diarrhée C. difficile', contre_indications: 'Allergie céphalosporines', surveillance: 'NFS, CRP, fonction rénale' },
  { id: 'mu-16', medicament: 'Amoxicilline-clavulanate', indication: 'Infection communautaire', dose_adulte: '2g IV q8h', dose_sujet_age: '1g IV q8h (adapter DFG)', voie: 'IV/PO', effets_secondaires: 'Diarrhée, allergie', contre_indications: 'Allergie pénicilline', surveillance: 'NFS, CRP, transit' },
  { id: 'mu-17', medicament: 'Paracétamol IV', indication: 'Douleur, fièvre', dose_adulte: '1g IV q6h (max 4g/j)', dose_sujet_age: '1g IV q6h (max 3g/j si < 50kg)', voie: 'IV', effets_secondaires: 'Hépatotoxicité si surdosage', contre_indications: 'Insuffisance hépatique sévère', surveillance: 'ALAT, ASAT, bilan hépatique' },
  { id: 'mu-18', medicament: 'Kétamine', indication: 'Sédation procédurale, douleur réfractaire', dose_adulte: '0.25mg/kg IV (douleur), 1-2mg/kg IV (sédation)', dose_sujet_age: 'Réduire de 50%', voie: 'IV', effets_secondaires: 'Hallucinations, hypertension, nausées', contre_indications: 'HTA non contrôlée, psychiatrie', surveillance: 'PA, FC, conscience, SpO2' },
  { id: 'mu-19', medicament: 'Énoxaparine', indication: 'Thrombose, EP, prophylaxie', dose_adulte: '1mg/kg SC q12h (curatif), 40mg SC q24h (prophylaxie)', dose_sujet_age: '0.5mg/kg SC q12h si DFG 15-30', voie: 'SC', effets_secondaires: 'Saignement, thrombopénie', contre_indications: 'Saignement actif, thrombopénie', surveillance: 'anti-Xa, NFS, signes saignement' },
  { id: 'mu-20', medicament: 'Ciprofloxacine', indication: 'Infection à Gram-, ITU compliquée', dose_adulte: '400mg IV q12h ou 500mg PO q12h', dose_sujet_age: '200-400mg IV q12h (adapter DFG)', voie: 'IV/PO', effets_secondaires: 'Tendinopathie, QT long, confusion', contre_indications: 'Myasthénie, QT long', surveillance: 'ECG, fonction tendineuse, confusion' }
];
