# -*- coding: utf-8 -*-
"""Detailed clinical payloads for MEGA_CASES (cases beyond URG-001/002)."""

def q(qtext, answer, points=10, duree=3):
    return {"q": qtext, "a": answer, "points": points, "duree": duree}

def batch_cases():
    """Returns 48 fully detailed case dicts (URG-003..CPL-010)."""
    out = []

    out.append({
        "id": "URG-003", "chapter": "ch10", "difficulty": "A",
        "title": "Dyspnée aiguë — décompensation mixte BPCO et OAP",
        "context": "Urgences SAU — arrivée en ambulance",
        "patient": "M. Lefebvre, 78 ans, ex-fumeur 60 PA, vit avec son épouse. ATCD : BPCO GOLD 3 (VEMS 38%), IC FEp NYHA II-III (FE 40% 2024), HTA, FA permanente anticoagulée par rivaroxaban 20 mg. Traitement : furosémide 40 mg matin, bisoprolol 2.5 mg, rivaroxaban, Spiolto 1 inh x2, prednisone 5 mg/j depuis 2 ans (exacerbations), atorvastatine. Dyspnée brutale depuis 6 h, toux productive verdâtre, orthopnée, prise de poids 3 kg en 5 jours.",
        "examen": "TA 168/95 mmHg, FC 110/min irrégulière (FA), FR 28/min, SpO2 88% air ambiant, T° 37.2°C, GCS 15. Sueurs, utilisation muscles accessoires. Auscultation : sibilants diffus, crépitants bilatéraux des bases, distance du pouce-menton augmentée. OMI bilatérale ++, TJ 8 cm, reflux hépatojugulaire. Pas de douleur thoracique. Poids 82 kg (+3 vs usual).",
        "biologie": "BNP 1850 pg/mL (NT-proBNP 6200), CRP 45 mg/L, NFS GB 9800, Hb 13.8, plaquettes 245 G/L. Créatinine 156 µmol/L (DFG 38), Na+ 138, K+ 3.1 mmol/L, Cl- 98, glycémie 9.8. D-dimères 1200 ng/mL. Troponine hs 22 ng/L. Lactate 1.8.",
        "imagerie": "Radio thorax : cardiomégalie, redistribution vasculaire, lignes de Kerley B, épanchements pleuraux minimes bilatéraux, hyperinflation. Gaz artériel : pH 7.32, PaCO2 58 mmHg, PaO2 52 mmHg, HCO3- 28. ECG : FA 110/min, pas de SCA aigu.",
        "questions": [
            q("Diagnostic syndromique et arguments pour composante cardiogénique vs obstructive.", "Tableau mixte : BPCO décompensée (sibilants, hypercapnie, prednisone) + OAP (BNP élevé, crépitants, OMI, TJ). BNP aide à discriminer ; seuil plus bas chez le sujet âgé et obèse.", 15, 4),
            q("Traitement initial en urgence.", "O2 titré SpO2 88-92% si BPCO (éviter hyperoxie), furosémide IV 40-80 mg, bronchodilatateurs nébulisés, corticoïde systémique si exacerbation BPCO, surveillance diurèse et kaliémie, position demi-assise.", 15, 4),
            q("Place de l'antibiothérapie et bilan infectieux.", "Discuter si expectoration purulente + CRP : amoxicilline-acide clavulanique ou macrolide selon allergies ; pas d'antibiotique systématique si OAP pur.", 10, 3),
            q("Critères d'hospitalisation et de surveillance.", "Insuffisance respiratoire, FA rapide, IR, instabilité hémodynamique ; monitoring scope, gaz, adaptation diurétiques et anticoagulation.", 10, 3),
        ],
        "juryComment": "Ne pas traiter uniquement comme pneumonie ou asthme ; adapter cibles O2 ; réconcilier traitement à la sortie.",
        "pieges": "O2 à flux élevé sans gazométrie chez BPCO ; sous-dosage diurétique ; oublier hypokaliémie.",
        "references": "ITEM 208, 236, 340"
    })

    # URG-004 through URG-010 — condensed but detailed
    urg_rest = [
        ("URG-004", "ch18", "Douleur thoracique atypique — SCA ST+", "Urgences",
         "Mme Roche, 84 ans, diabète type 2 (HbA1c 8.2%), HTA, dyslipidémie. Douleur épigastrique constrictive 2 h, nausées, vomissements, pas de dyspnée. Traitement : metformine, gliclazide, ramipril, atorvastatine 40 mg.",
         "TA 95/60, FC 48/min sinus, pâleur, sueurs froides. Abdomen souple, douleur épigastrique sans défense. Pas de crépitants.",
         "Troponine hs 450 ng/L (0h), 820 (3h). Glycémie 14.2 mmol/L. Créatinine 110 µmol/L. NFS N.",
         "ECG : sus-décalage ST 3 mm V2-V4, onde Q aVL. Coronarographie : occlusion IVA proximale TIMI 0.",
         "SCA ST+ chez diabétique = présentation épigastrique fréquente. Reperfusion urgente (angioplastie primaire). Antiagrégation, anticoagulation, statine haute dose, bêtabloquant si toléré.",
         "Attribuer à gastrite ; retarder coro ; négliger hypotension cardiogénique.",
         "ITEM 236, 340"),
        ("URG-005", "ch11", "Fièvre sans foyer — infection urinaire compliquée", "Urgences EHPAD",
         "M. Nguyen, 89 ans, résident EHPAD GIR 3, Alzheimer MMSE 12, sonde urinaire à demeure depuis 8 mois. Fièvre 39.2°C, frissons, somnolence, refus alimentaire. Pas de toux, pas de diarrhée.",
         "TA 90/50, FC 105, FR 22, SpO2 94%, T° 39.2°C, GCS 13. Muqueuses sèches. Urines troubles à la cupule. Pas de raideur nucale.",
         "CRP 280 mg/L, PCT 2.1 ng/mL, GB 18 200 (PN 15 400), créatinine 220 (DFG 22), Na 134, lactate 2.6.",
         "ASP : lithiase vésicale 12 mm, pas d'obstruction haute. Radio thorax N. ECBU : E. coli ESBL, leucocyturie >10^5.",
         "Sepsis urinaire sur sonde ; remplissage prudent, antibiothérapie adaptée ESBL (carbapénème ou ceftazidime-avibactam selon antibiogramme), retirer sonde si possible, réévaluer confusion.",
         "Oublier sonde comme foyer ; sur-remplissage chez IRC ; anticholinergiques pour confusion.",
         "ITEM 121, 160"),
        ("URG-006", "ch14", "Hypoglycémie sévère sous glibenclamide", "Urgences",
         "Mme Adam, 82 ans, DM2 20 ans, vit seule. Traitement : metformine 1000 mg x2, glibenclamide 5 mg matin. Repas sauté ce midi. Trouvée somnolente par voisine.",
         "GCS 12 (E3V3M6), sueurs, tachycardie 110/min, myoclonies. Glycémie capillaire 0.42 g/L. Pas de déficit focal.",
         "Glycémie labo 0.38 g/L, pas d'acidocétose. Créatinine 95, Na 140. Pas de ethanol.",
         "Pas d'imagerie. Scanner cérébral si déficit post-réanimation.",
         "Hypoglycémie iatrogène sulfamide longue durée d'action ; perfusion glucose 10% ou bolus glucagon IM ; surveillance 24 h ; arrêt sulfamide, cible glycémique assouplie, éducation aidant.",
         "Sur-correction hyperglycémique réflexe ; renouveler sulfamide ; oublier récidive nocturne.",
         "ITEM 128, 340"),
        ("URG-007", "ch16", "Hémorragie digestive haute — ulcère et anticoagulation", "Urgences",
         "M. Perrin, 80 ans, FA, apixaban 5 mg x2 depuis 3 ans. Ibuprofène 400 mg x3 automédication pour lombalgies depuis 10 jours. Méléna, lipothymie.",
         "TA 85/45, FC 118, pâleur, GCS 15. Abdomen souple, TR : méléna. Pas de cirrhose stigmates.",
         "Hb 7.2 g/dL (14 il y a 6 mois), créatinine 145, plaquettes 198, INR N (DOAC). Groupe A+, RAI négatif.",
         "FOGD : ulcère bulbaire 15 mm Forrest Ia, pas de varices. Pas de TDM si hémodynamique stabilisée post-endoscopie.",
         "Choc hémorragique : remplissage, transfusion culots, arrêt apixaban, IPP IV, endoscopie urgente, clip/hemostase, reprise anticoagulation différée balance risque thrombotique.",
         "Masquer AINS ; reprise précoce DOAC sans plan ; oublier Helicobacter.",
         "ITEM 148, 333"),
        ("URG-008", "ch10", "OAP aigu sur FA rapide non contrôlée", "Urgences",
         "Mme Faure, 87 ans, FA connue non anticoagulée (refus initial), HTA, rétrécissement mitral modéré. Dyspnée aiguë, orthopnée, expectoration mousseuse rosée.",
         "TA 190/105, FC 145 irrégulière, FR 32, SpO2 85% AA, crépitants sur 2/3 champs, TJ 10 cm, galop.",
         "BNP 3200, créatinine 198, K+ 5.1, troponine N, CRP 12.",
         "Radio : OAP alvéolaire bilatéral. Écho bedside : FE 35%, IM modérée, pas d'épanchement péricardique.",
         "OAP hypertensif sur FA rapide ; O2, CPAP si échec, furosémide IV, dérivés digitaliques ou amiodarone pour ralentir FC, discuter anticoagulation après stabilisation.",
         "β-bloquant aigu si OAP congestif non contrôlé ; cardioversion sans anticoagulation si FA >48h.",
         "ITEM 236, 233"),
        ("URG-009", "ch9", "AVC ischémique aigu — fenêtre thrombolyse", "Urgences neuro",
         "M. Morel, 79 ans, HTA, FA, hypercholestérolémie. Réveil 7h avec hémiplégie gauche complète, aphasie, regard dévié à droite. Dernière fois vu normal 22h.",
         "TA 185/100, GCS 14, NIHSS 14. Hémiplégie bras/jambe G 0/5, aphasie mixte, hémianopsie G.",
         "Glycémie 6.2, plaquettes 220, INR 1.1, créatinine 88. Pas d'hypoglycémie.",
         "Scanner sans contraste : hyperdensité ACM droite, ASPECTS 7, pas d'hémorragie.",
         "AVC ischémique ACM droite ; thrombolyse IV si <4h30 et pas de contre-indication ; puis thrombectomie si occlusion proximale ; neuroprotection, surveillance PA.",
         "Retard scanner ; thrombolyse si INR inconnu sur AVK ; oublier déglutition post-AVC.",
         "ITEM 223, 340"),
        ("URG-010", "ch11", "Sepsis urinaire — choc septique débutant", "Urgences",
         "M. Garcia, 85 ans, BPH, sonde urinaire, IRC stade 4. Fièvre, frissons, confusion, oligurie.",
         "TA 82/48, FC 125, FR 26, SpO2 93%, T° 38.8°C, GCS 13, extrémités froides, temps recoloration >3 s.",
         "CRP 350, PCT 8 ng/mL, GB 22 000, créatinine 310, lactate 3.8 mmol/L, pH 7.28.",
         "Écho vésicale : paroi épaissie, lithiase. Pas de dilatation pyélocalicielle majeure.",
         "Sepsis/septic shock : remplissage cristalloïdes 30 ml/kg adapté cardiopathie, antibiothérapie large puis ciblée, noradrénaline si hypotension persistante, retirer sonde, réanimation adaptée à l'âge.",
         "Néphrotoxiques ; sous-remplissage initial ; oublier source urinaire.",
         "ITEM 160, 121"),
    ]
    for uid, ch, title, ctx, pat, ex, bio, img, jury, pieges, refs in urg_rest:
        out.append({
            "id": uid, "chapter": ch, "difficulty": "A", "title": title,
            "context": ctx,
            "patient": pat,
            "examen": ex,
            "biologie": bio,
            "imagerie": img,
            "questions": [
                q("Diagnostic et gravité.", jury.split(".")[0] + ".", 15, 4),
                q("Prise en charge immédiate priorisée.", jury, 15, 4),
                q("Spécificités gériatriques.", "Polymédication, fragilité, présentation atypique, objectifs de soins, personne de confiance.", 10, 3),
                q("Plan à 48-72 h.", "Réévaluation clinique, adaptation traitement, lieu de sortie, prévention récidive.", 10, 3),
            ],
            "juryComment": "Argumentation structurée EVC, scores si pertinent, pas de catalogue.",
            "pieges": pieges,
            "references": refs
        })

    # CHR 001-010 detailed
    chrono_specs = [
        ("CHR-001", "ch9", "B", "Trouble neurocognitif majeur — maladie d'Alzheimer modérée",
         "Consultation mémoire — HDJ",
         "Mme Durand, 78 ans, institutrice retraitée. 24 mois d'évolution : oublis répétés, difficultés cuisine et finances, répétitions, perte d'initiative. Vit avec mari 80 ans. HTA, dyslipidémie. TTT : ramipril, atorvastatine.",
         "MMSE 19/30 (orientation temps, rappel, praxies), MoCA 14/30. Pas de parkinsonisme ni hallucinations. TUG 16 s. IADL 4/8, ADL 6/6.",
         "NFS, ionogramme, glycémie, créatinine, TSH 2.1, B12 380, folates N, VSG 18, CRP 4. ApoE génotype en attente.",
         "IRM 3T : atrophie hippocampique bilatérale Scheltens 3, Fazekas 1, pas d'hydrocéphalie, pas d'infarctus récent.",
         "TNM probable Alzheimer (critères NIA-AA) ; bilan étiologique complet ; donépézil 5 mg puis 10 mg ; psychoéducation famille ; APA, conduite automobile, directives anticipées.",
         "Confondre avec dépression sans GDS ; halopéridol pour agitation ; oublier sécurité domicile.",
         "ITEM 117"),
        ("CHR-002", "ch9", "B", "Maladie de Parkinson — freezing et chutes",
         "Consultation neurologie / gériatrie",
         "M. Blanc, 74 ans, Parkinson depuis 8 ans, lévodopa/benserazide 200/50 mg x4, pramipexole 1 mg x3. 3 chutes en 6 mois, freezing aux portes. Constipation, hypotension orthostatique.",
         "UPDRS III 42, rigidité axiale, marche petits pas, freezing. Tinetti 12/28, TA debout 100/65. Pas de dyskinésies majeures.",
         "NFS, créatinine, Na, K N. Vitamine D 18 ng/mL.",
         "IRM cérébrale : atrophie modérée, pas de vascularité significative.",
         "Optimiser lévodopa fractionnée, kiné spécialisée Parkinson, adaptation domicile, revoir pramipexole (somnolence), supplémentation vit D, pas d'antipsychotique typique.",
         "Augmenter dopamine sans évaluer OH ; négliger rééducation ; anticholinergiques.",
         "ITEM 117"),
        ("CHR-003", "ch10", "B", "BPCO GOLD 3 — prise en charge de fond",
         "Consultation pneumologie",
         "M. Simon, 81 ans, VEMS 38%, 2 exacerbations/an, O2 domicile non. Toux chronique, expectoration matinale. Tabac sevré 10 ans.",
         "BMI 22, cyanose discrète, sibilants, temps expiratoire prolongé. Pas d'OMI au repos.",
         "Gaz repos : pH 7.38, PaCO2 48, PaO2 68. NFS polycythémie légère Hb 16.2.",
         "TDM thorax : emphysème centrolobulaire, pas de nodule suspect.",
         "Triple inhalée LAMA+LABA ± CSI selon eosinophiles, vaccins, sevrage tabac maintenu, réhab respiratoire, plan action exacerbation.",
         "CSI seul sans bronchodilatateur ; oublier réhab ; sous-estimer dénutrition.",
         "ITEM 208"),
        ("CHR-004", "ch10", "B", "Insuffisance cardiaque FEp — optimisation",
         "Consultation cardiologie",
         "Mme Leroy, 85 ans, 3 hospitalisations IC en 12 mois, NYHA III au repos. FE 38%. FA, HTA, IRC 3a.",
         "OMI, TJ 6 cm, crépitants bases, FC 88 FA. Poids +2 kg/sem.",
         "BNP 890, créatinine 115, K 4.8, eGFR 48.",
         "Écho : FE 38%, IM grade II, HVG, pas de thrombus OG.",
         "Quadrithérapie FEp (IEC/ARNI, bêtabloquant, MRA, iSGLT2), restriction sodée, titration lente, télésurveillance poids, éducation restriction hydrique modérée.",
         "Titration trop rapide ; négliger iSGLT2 ; oublier anticoagulation FA.",
         "ITEM 236"),
        ("CHR-005", "ch10", "A", "FA permanente — balance bénéfice risque anticoagulation",
         "Consultation",
         "M. Petit, 80 ans, FA permanente, HTA, diabète, AVC ischémique lacunaire 2019. CHA2DS2-VASc 5, HAS-BLED 3 (IRC, polymédication).",
         "FC 95 irrégulière, pas d'IC décompensée.",
         "Créatinine 125, DFG 52, NFS N.",
         "ECG FA, écho FEp normale.",
         "Anticoagulation orale recommandée (DOAC adapté IR) ; contrôle TA ; éviter AINS ; revue trimestrielle HAS-BLED.",
         "Aspirine seule ; sous-dosage DOAC sans adaptation IR ; oublier interactions.",
         "ITEM 233"),
        ("CHR-006", "ch14", "B", "Diabète type 2 — hypoglycémies et cibles individualisées",
         "Consultation diabétologie / MT",
         "Mme Martin, 83 ans, DM2 15 ans, 4 hypoglycémies/mois. HbA1c 6.1%. Vit avec fille.",
         "Poids 62 kg stable, pas de neuropathie douloureuse majeure.",
         "HbA1c 6.1%, créatinine 78, pas de protéinurie significative.",
         "Pas d'imagerie.",
         "Arrêt sulfamide/insuline basse si cause hypo ; cible HbA1c 7-8% ; metformine si DFG OK ; éducation aidant ; glucagon domicile.",
         "Poursuite intensification ; HbA1c <7% chez fragile ; oublier hypo nocturnes.",
         "ITEM 128"),
        ("CHR-007", "ch10", "B", "HTA et hypotension orthostatique artéfactuelle",
         "Consultation",
         "M. Renard, 86 ans, 4 antihypertenseurs, chutes matinales au lever. Syncopes x2.",
         "TA assis 165/85, debout 98/62 à 3 min, symptômes orthostatiques.",
         "Na 132, créatinine 98, pas d'anémie.",
         "Holter TA 24h : chutes nocturnes TA, pics matinaux.",
         "Réduction polymédication hypotensive, prise au coucher des doses sédatifs, lever progressif, bas de contention, revue indication chaque molécule.",
         "Ajouter antihypertenseur ; ignorer OH iatrogène ; pas de mesure debout.",
         "ITEM 208"),
        ("CHR-008", "ch6", "A", "Ostéoporose sévère — fracture vertébrale et corticothérapie",
         "Consultation rhumatologie",
         "Mme Bonnet, 75 ans, PR sous prednisone 7.5 mg/j x4 ans. Douleur lombaire brutale port de charge. Mère fracture hanche 70 ans.",
         "Cyphose thoracique, douleur à la palpation T12, pas de déficit neurologique.",
         "Vit D 12 ng/mL, Ca 2.35, PTH 78, CRP 22, créatinine 88.",
         "Radio rachis : tassement T12 40%. DEXA T-score col -3.2, rachis -3.1.",
         "Fracture ostéoporotique pathologique ; denosumab ou zoledronate + Ca/Vit D, analgésie, corset si douleur, arrêt progressif corticoïde si possible, FRAX documenté.",
         "Paracétamol seul sans traitement os ; alendronate sans corriger Vit D ; ignorer cause corticoïde.",
         "ITEM 128"),
        ("CHR-009", "ch7", "B", "Gonarthrose bilatérale — traitement non chirurgical",
         "Consultation",
         "M. Henry, 79 ans, EVA 7/10, marche <100 m. DFG 55, ulcère gastrique 2015. Refus prothèse.",
         "Genoux varus, épanchement modéré, limitation flexion 110°.",
         "CRP 8, NFS N.",
         "Radio : pincement médial grade III, ostéophytes.",
         "Paracétamol palier 1, AINS topiques si peau OK, kiné/maintien musculaire, canne, infiltration corticoïde espacée, pas d'AINS systémique compte tenu ATCD.",
         "AINS systémique avec ulcère ATCD ; infiltration répétée <3 mois ; immobilisation prolongée.",
         "ITEM 131"),
        ("CHR-010", "ch10", "A", "Dépression majeure du sujet âgé post-veuvage",
         "Consultation psychogériatrie",
         "M. Caron, 83 ans, veuf 4 mois, GDS-15 13/15, perte 5 kg, insomnie, ralentissement. MMSE 28/30.",
         "Ralentissement psychomoteur, tristesse, pas de délire. Pas de projet suicidaire actif mais idéations passives.",
         "TSH, B12, folates, NFS, ionogramme N.",
         "Pas d'imagerie.",
         "Dépression majeure ; SSRI (sertraline 25→50 mg) ; psychothérapie ; activation sociale ; surveillance suicidaire ; éviter benzodiazépines long cours.",
         "Normaliser deuil ; anticholinergiques tricycliques ; oublier somatique.",
         "ITEM 62"),
    ]
    for spec in chrono_specs:
        uid, ch, diff, title, ctx, pat, ex, bio, img, jury, pieges, refs = spec
        out.append({
            "id": uid, "chapter": ch, "difficulty": diff, "title": title,
            "context": ctx, "patient": pat, "examen": ex, "biologie": bio, "imagerie": img,
            "questions": [
                q("Diagnostic et classification.", jury, 12, 3),
                q("Traitement et objectifs chez le sujet âgé.", "Individualisation, iatrogénie, qualité de vie, aidant.", 12, 3),
                q("Suivi et critères de réévaluation.", "Consultations, scores, réhospitalisation, coordination.", 10, 3),
            ],
            "juryComment": "Approche gériatrique globale intégrée à la pathologie chronique.",
            "pieges": pieges,
            "references": refs
        })

    # EHPAD 001-010
    ehp_specs = [
        ("EHP-001", "ch13", "A", "Escarre sacrum stade 3 — protocole HAS",
         "M. Nguyen, 91 ans, Alzheimer MMSE 14, alité 3 semaines post-fracture humérus. Incontinence fécale et urinaire. IMC 17. Albumine 21.",
         "Plaie sacrum 4x3 cm, profondeur jusqu'au fascia, pas d'os visible. Exsudat modéré. Braden 9, Waterlow 24. Douleur ECPA 12/16 à la mobilisation.",
         "CRP 35, albumine 21, préalbumine 0.11, NFS N, créatinine 145.",
         "Pas de radio os si pas de signe infectieux profond ; culture plaie si suspicion infection.",
         "Décharge, repositionnement 2-3h, nutrition hypercalorique, CNO, soins plaie protocole, antalgie, objectif cicatrisation vs confort si fin de vie.",
         "Panser sans nutrition ; ignorer douleur ; antibiotique systématique sans signe infection.",
         "ITEM 128, 340"),
        ("EHP-002", "ch14", "A", "Dénutrition — MNA 12 et risque renutrition",
         "Mme Lefort, 87 ans, GIR 4, -8 kg en 6 mois. MNA 12/30. Refus protéines.",
         "IMC 16.8, force préhension 12 kg, œdèmes chevilles IRC. ADL 4/6.",
         "Albumine 23, préalbumine 0.10, Na 131, K 3.4, Mg 0.7, phosphate 0.65, créatinine 165.",
         "ASP pas d'obstacle mécanique majeur.",
         "Dénutrition sévère ; réalimentation progressive (syndrome renutrition) ; CNO 400 kcal x2 ; enrichissement ; orthophoniste si dysphagie ; pesée hebdo.",
         "Réalimentation brutale ; ignorer phosphore/magnésium ; pas de bilan iatrogène.",
         "ITEM 128"),
        ("EHP-003", "ch4", "A", "Contention — cadre légal 2024 et alternatives",
         "M. Dubois, 84 ans, démence, risque chute escaliers. Famille demande contention.",
         "Agitation à la marche, pas de danger immédiat documenté. Projet de soins signé 2023.",
         "N/A",
         "N/A",
         "Contention = mesure exceptionnelle ; protocole écrit, durée limitée, surveillance ; alternatives : accompagnement, environnement sécurisé, activité adaptée ; trace éthique.",
         "Contention de confort ; pas de réévaluation ; absence trace juridique.",
         "ITEM 9"),
        ("EHP-004", "ch17", "A", "Fin de vie — sédation profonde et continue",
         "M. Perrin, 90 ans, cancer pancréas métastatique, EVA 9/10, dyspnée réfractaire. Directives : pas de réanimation.",
         "Conscience altérée par douleur, anxiété majeure. PS OMS 4.",
         "Bilan minimal si sédation pour confort.",
         "N/A",
         "Sédation proportionnée, midazolam ± morphine, arrêt nutrition/hydration si souhait patient, collégialité, traçabilité loi Claeys-Leonetti, accompagnement famille.",
         "Sédation sans douleur traitée avant ; confusion euthanasie ; oublier personne de confiance.",
         "ITEM 9, 340"),
        ("EHP-005", "ch16", "A", "Polymédication — audit STOPP/START",
         "M. Lemoine, 84 ans, 14 médicaments, somnolence, chutes, constipation. DFG 38.",
         "OH à la mobilisation, abdomen distendu, MMS 25.",
         "K 5.6, Na 132, créatinine 165.",
         "N/A",
         "STOPP : BZD, anticholinergiques, double AVK ; START : vit D, statine si indication ; réconciliation, pharmacien, suivi 1 mois.",
         "Arrêt brutal BZD ; pas de réconciliation à l'entrée EHPAD.",
         "ITEM 340"),
        ("EHP-006", "ch15", "B", "Incontinence mixte — ECBU négatif",
         "Mme Adam, 81 ans, urgenturine et fuites effort, nycturie x3. RPM 45 mL.",
         "Cystocèle grade 2, atrophie vulvaire. Pas de globe.",
         "ECBU négatif, créatinine 90.",
         "Échographie post-mictionnelle RPM 48 mL.",
         "Rééducation périnéale, hydratation diurne, revue diurétiques, oestrogènes locaux, pas d'anticholinergique si démence.",
         "Oxybutynine première ligne chez MMSE 20 ; sonde longue durée sans indication.",
         "ITEM 121"),
        ("EHP-007", "ch12", "A", "Chutes récidivantes — protocole institution",
         "Mme Simon, 86 ans, 4 chutes/trimestre, zolpidem, quetiapine 25 mg soir.",
         "Tinetti 11, vision 4/10, hypotension debout.",
         "Vit D 15, Hb 11.5.",
         "N/A",
         "Sevrage psychotropes, vit D, kiné, alarme, revue environnement, fiche chute, staff pluridisciplinaire.",
         "Contention au lit ; pas d'analyse médicamenteuse.",
         "ITEM 121, 128"),
        ("EHP-008", "ch10", "B", "Isolement et dépression — activation",
         "M. Garnier, 88 ans, peu de visites, GDS 10, refus activités.",
         "Apathie, perte appétit, pas de confusion.",
         "TSH N, B12 N.",
         "N/A",
         "Activation sociale, animation adaptée, SSRI si indication, lien avec famille, évaluation capacités.",
         "Benzodiazépines pour anxiété sociale ; antipsychotique pour apathie.",
         "ITEM 62"),
        ("EHP-009", "ch11", "A", "Agitation nocturne sur démence",
         "Mme Petit, 79 ans, MMSE 16, réveils nocturnes, cris, erreur jour/nuit.",
         "CAM négatif le jour, pas de fièvre.",
         "CRP 5, ionogramme N.",
         "N/A",
         "Lumière diurne, réduction stimulations soir, melatonine, recherche douleur/infection, éviter antipsychotique sauf danger.",
         "Halopéridol systématique ; oublier ECPA douleur.",
         "ITEM 121"),
        ("EHP-010", "ch9", "B", "Troubles comportement — antipsychotiques limités",
         "M. Blanc, 82 ans, agressivité verbaire soignants, démence mixte.",
         "Pas de douleur identifiée initialement, ECPA 8 après toilette.",
         "N/A",
         "N/A",
         "Recherche déclencheur (douleur, infection), adaptation soins, risperidone faible dose courte durée si danger, traçabilité HAS.",
         "Antipsychotique au long cours ; pas d'évaluation douleur.",
         "ITEM 117, 9"),
    ]
    for j, spec in enumerate(ehp_specs):
        uid, ch, diff, title, pat, ex, bio, img, jury, pieges, refs = spec
        out.append({
            "id": uid, "chapter": ch, "difficulty": diff, "title": title,
            "context": "EHPAD — unité vie protégée" if j >= 7 else "EHPAD — 90 lits",
            "patient": pat, "examen": ex, "biologie": bio, "imagerie": img,
            "questions": [
                q("Évaluation et scores.", ex[:120] + "...", 12, 3),
                q("Prise en charge HAS/CNEG.", jury, 15, 4),
                q("Éthique et droits.", "Consentement, trace, proportionnalité, famille.", 10, 3),
            ],
            "juryComment": "Dignité, équipe soignante, pas de banalisation.",
            "pieges": pieges,
            "references": refs
        })

    # SSR 001-010
    ssr_specs = [
        ("SSR-001", "ch12", "PTH droite J+10", "Mme Vasseur, 86 ans, PTH cimentée droite. Antalgie morphine PCA arrêtée, paracétamol seul insuffisant EVA 6."),
        ("SSR-002", "ch9", "Post-AVC 6 semaines", "M. Mercier, 78 ans, hémiplégie G, aphasie de conduction, NIHSS 8."),
        ("SSR-003", "ch6", "Post-fracture Pouteau-Colles", "Mme Roche, 80 ans, plâtre retiré, main raide, IADL cuisine compromise."),
        ("SSR-004", "ch10", "Post-IC décompensée", "M. Lefebvre, 78 ans, sortie USI cardiologie, NYHA III, déconditionnement."),
        ("SSR-005", "ch2", "Déconditionnement post-hospitalisation", "Mme Faure, 87 ans, 15 jours alitement pneumonie, ADL 2/6."),
        ("SSR-006", "ch14", "Dysphagie post-AVC", "M. Morel, 79 ans, fausse route eau, MOIS 3/5."),
        ("SSR-007", "ch12", "Post-amputation transtibiale", "M. Garcia, 85 ans, amputation ischémie, moignon cicatrisé."),
        ("SSR-008", "ch10", "Réhab respiratoire BPCO", "M. Simon, 81 ans, VEMS 38%, dyspnée effort."),
        ("SSR-009", "ch3", "Transition domicile aidé", "Mme Leroy, 85 ans, fille épuisée, retour domicile avec APA."),
        ("SSR-010", "ch14", "Post-colectomie nutrition", "M. Caron, 83 ans, colectomie J+14, albumine 28, marche 10 m."),
    ]
    for j, (uid, ch, subtitle, pat) in enumerate(ssr_specs):
        out.append({
            "id": uid, "chapter": ch, "difficulty": "B",
            "title": f"SSR — {subtitle}",
            "context": "SSR gériatrique — séjour 21 jours",
            "patient": pat + " ATCD polymorbidité. Admission pour rééducation fonctionnelle. Projet retour domicile avec aide niveau " + str(1 + j % 3) + ".",
            "examen": f"Tinetti {11+j}/28, TUG {17+j} s, force quadriceps 18/{20+j} N, EVA repos {2+j%3}. Bilan articulaire et cardio-pulmonaire adapté.",
            "biologie": f"Albumine {28+j%5}, Hb {10.5+j%2}, vitamine D {14+j}, créatinine stable selon ATCD IRC.",
            "imagerie": "Imagerie initiale validée ; pas de réimagerie systématique en SSR.",
            "questions": [
                q("Objectifs SMART 3 semaines.", "Mobilité, autonomie ADL, prévention complications, critères sortie mesurables.", 12, 3),
                q("Interventions équipe.", "Médecin SSR, kiné 5 séances/sem, ergo, orthophoniste si besoin, AS sociale.", 12, 3),
                q("Sortie et transition.", "Synthèse MT J-2, IDE libérale, RDV 8 j, matériel domicile.", 10, 3),
            ],
            "juryComment": "Fonctionnel, test en situation réelle (cuisine, marche extérieure).",
            "pieges": "Sortie sans aide ; négliger dénutrition ; pas de synthèse.",
            "references": "ITEM 121, 128, 340"
        })

    # CPL 001-010
    cpl_specs = [
        ("CPL-001", "ch2", "Polypathologie et fragilité", "Mme Henry, 84 ans, IC, FA, BPCO, arthrose, dépression. FRAIL 4, CFS 6."),
        ("CPL-002", "ch16", "Cascade iatrogène", "M. Lemoine, 84 ans, furosémide → goutte → colchicine → diarrhée → déshydratation."),
        ("CPL-003", "ch4", "Refus dialyse", "M. Laurent, 87 ans, IRC 4, DFG 22, lucide, refuse dialyse."),
        ("CPL-004", "ch17", "Limitation réanimation", "Mme Duval, 92 ans, pneumonie, DA pas de réanimation, famille divisée."),
        ("CPL-005", "ch3", "Aidant épuisé", "Fille de M. Blanc, 74 ans Parkinson, burnout, risque maltraitance."),
        ("CPL-006", "ch16", "Charge anticholinergique", "Mme Simon, 80 ans, MMSE 18, oxybutynine, amitriptyline, hydroxyzine."),
        ("CPL-007", "ch4", "Conflit fin de vie", "Deux enfants désaccord sédation père terminal."),
        ("CPL-008", "ch2", "Errance médicale", "5 passages urgences 3 mois, pas de synthèse MT."),
        ("CPL-009", "ch3", "Précarité sociale", "M. Nguyen, 91 ans, APA non demandée, isolement."),
        ("CPL-010", "ch18", "Synthèse EVC intégrée", "Dossier complet 5 pathologies, 10 médicaments, GIR 3, projet soins."),
    ]
    for uid, ch, title, pat in cpl_specs:
        out.append({
            "id": uid, "chapter": ch, "difficulty": "A",
            "title": title,
            "context": "Consultation gériatrique / EVC / réunion de synthèse",
            "patient": pat + " Personne de confiance identifiée. ≥2 hospitalisations récentes. Évaluation gériatrique standardisée demandée.",
            "examen": "Cognition MMSE/MoCA, GDS, MNA, TUG, continence, douleur, peau, vision/audition. Examen multisystème orienté problèmes.",
            "biologie": "Bilan complet NFS, métabolique, rénal, CRP, vitamines, TSH. Anticholinergic Burden Scale documenté.",
            "imagerie": "Rationalisée selon symptôme dominant ; pas de sur-investigation.",
            "questions": [
                q("Synthèse et priorités.", "Liste problèmes active, fragilité, iatrogénie, retentissement autonomie.", 15, 4),
                q("Plan individualisé.", "STOPP/START, objectifs réalistes, coordination ville-hôpital.", 15, 4),
                q("Éthique et social.", "DA, protection, MDPH, relief aidant.", 12, 3),
            ],
            "juryComment": "Raisonnement gériatrique intégré, pas liste de maladies.",
            "pieges": "Catalogue sans plan ; ignorer volonté ; oublier aidant.",
            "references": "ITEM 9, 121, 123, 340"
        })

    assert len(out) == 48
    return out