// Mémos rapides — Aide-mémoire pour révision express
const MEMOS_RAPIDES = [
  { id: 'mr-1', titre: 'GDS (Gravité démence)', emoji: '🧠',
    contenu: 'GDS 1 = normal · GDS 2 = déclin très léger · GDS 3 = déclin léger · GDS 4 = déclin modéré · GDS 5 = déclin modéré-sévère · GDS 6 = déclin sévère · GDS 7 = déclin très sévère',
    mnemo: 'GDS = Geriatric Depression Scale ≠ GDS Global Deterioration Scale (confusion fréquente !)' },
  { id: 'mr-2', titre: 'ADL (Katz) — les 6', emoji: '📋',
    contenu: 'A = Baignade · D = Dressing (habillage) · L = Locomotion (transferts) · Toilette · Continence · Alimentation',
    mnemo: 'BADLTC → Baignage, Alimentation, Dressing, Locomotion, Toilette, Continence' },
  { id: 'mr-3', titre: 'IADL (Lawton) — les 8', emoji: '📋',
    contenu: 'Courses · Cuisine · Ménage · Lessive · Téléphone · Transport · Médicaments · Argent',
    mnemo: 'CCLMTTMA → Courses, Cuisine, Lessive, Ménage, Téléphone, Transport, Médicaments, Argent' },
  { id: 'mr-4', titre: 'Critères de Fried (fragilité)', emoji: '⚡',
    contenu: '1. Perte poids ≥ 4.5 kg/an · 2. Épuisement (CES-D) · 3. Faiblesse (grip) · 4. Lenteur marche (< 0.8 m/s) · 5. Inactivité (IPAQ bas quintile)',
    mnemo: 'PEFLI → Perte, Épuisement, Faiblesse, Lenteur, Inactivité. ≥ 3 = fragile' },
  { id: 'mr-5', titre: 'Beers — classes à éviter', emoji: '💊',
    contenu: 'BZD (diazépam, lorazepam) · Anticholinergiques (amitriptyline, diphénhydramine) · AINS (ibuprofène, diclofénac) · Opioïdes longue durée · Antipsychotiques (halopéridol risque AVC) · Digoxine > 0.125mg',
    mnemo: 'BAOAAD → BZD, AINS, Opioïdes, Anticholinergiques, Antipsychotiques, Digoxine' },
  { id: 'mr-6', titre: 'CAM — diagnostic confusion', emoji: '🧠',
    contenu: '(1) Début aigu + fluctuation · (2) Inattention · (3) Pensée désorganisée · (4) Niveau conscience altéré',
    mnemo: 'CAM+ = (1) OBLIGATOIRE + (2) OU (3+4). Se souvenir : "DINA" = Début, Inattention, N-conscience, Altération pensée' },
  { id: 'mr-7', titre: 'Braden — 6 facteurs escarre', emoji: '🏥',
    contenu: '1. Perception sensorielle · 2. Humidité · 3. Activité · 4. Mobilité · 5. Nutrition · 6. Friction/cisaillement',
    mnemo: 'PHAMNF → Perception, Humidité, Activité, Mobilité, Nutrition, Friction' },
  { id: 'mr-8', titre: 'Échelle d\'ECPA (douleur non communicant)', emoji: '💊',
    contenu: '1. Respiration · 2. Vocalisation · 3. Expression facale · 4. Corps · 5. Consolabilité',
    mnemo: 'RVEBC → Respiration, Vocalisation, Expression, Body, Consolabilité' },
  { id: 'mr-9', titre: 'Tinetti — équilibre + marche', emoji: '🚶',
    contenu: 'Équilibre (9 items/16) : assis, debout, poussé, yeux fermés, pivot, siège. Marche (7 items/12) : initiation, longueur, hauteur, symérie, continuité, trajectoire, tronc.',
    mnemo: '< 19 risque élevé · 19-24 modéré · ≥ 25 faible' },
  { id: 'mr-10', titre: 'MNA — seuils nutritionnels', emoji: '🍽️',
    contenu: '≥ 24 = normal · 17-23.5 = risque de dénutrition · < 17 = dénutrition',
    mnemo: 'MNA = Mini Nutritional Assessment. 24+ = OK. 17-23 = attention. < 17 = alarme' },
  { id: 'mr-11', titre: 'FRAX — facteurs de risque', emoji: '🦴',
    contenu: 'Âge · Sexe · IMC < 19 · Fracture antérieure · Parent fracturé · Tabac · Corticoïdes · Arthrite rhumatoïde · Ostéoporose secondaire · Alcool ≥ 3 doses/j',
    mnemo: 'FRAX = Fracture Risk Assessment Tool. Score à 10 ans → décide du traitement' },
  { id: 'mr-12', titre: 'Norton modifié — escarre', emoji: '🏥',
    contenu: 'État physique (1-4) · État mental (1-4) · Activité (1-4) · Mobilité (1-4) · Incontinence (1-4)',
    mnemo: '< 14 = risque élevé. 5 items × 4 = 20 max. Seuil = 14.' }
];
