// Pièges d'examen EVC — Les questions qui trompent
const PIEGES_EXAM_EXT = [
  { id: 'piege-1', chapitre: 'ch9',
    piege: 'Confondre démence et dépression (pseudodémence)',
    reponse: 'La pseudodémence dépressive a : plainte mnésique exagérée, début daté, affect triste, GDS élevé, MMS qui s\'améliore avec traitement antidépresseur. La démence a : plainte minimale/négation, début insidieux, affect plat, MMS stable/déclinant.',
    conseil: 'Toujours doser GDS-15 devant un trouble cognitif. Si > 11 → traiter la dépression AVANT de conclure à une démence.' },
  { id: 'piege-2', chapitre: 'ch11',
    piege: 'Confondre delirium et démence',
    reponse: 'Delirium = aigu (heures/jours), fluctuant, inattention, horaire nocturne. Démence = chronique (mois/années), stable, mémoire atteinte en premier, pas de fluctuation marquée. Un delirium peut se greffer SUR une démence (delirium superposé).',
    conseil: 'La CAM diagnostique le delirium. Le MMS évalue la démence. Faire les DEUX.' },
  { id: 'piege-3', chapitre: 'ch16',
    piege: 'Prescrire un AINS chez le sujet âgé',
    reponse: 'CONTRE-INDIQUÉ systématiquement. Risque : insuffisance rénale aiguë, hémorragie digestive, HTA, décompensation cardiaque, confusion. Alternative : paracétamol → tramadol → morphine.',
    conseil: 'Tout AINS chez un > 75 ans = perte de points automatique. Paracétamol = réponse universelle.' },
  { id: 'piege-4', chapitre: 'ch12',
    piege: 'Oublier les médicaments comme cause de chute',
    reponse: '50% des chutes ont une cause médicamenteuse. Les principaux : BZD (sédation, ataxie), antihypertenseurs (hypotension orthostatique), anticholinergiques (confusion), opioïdes (sédation), diurétiques (déshydratation).',
    conseil: 'Toute chute = révision médicamenteuse systématique. Citer les classes à risque = points faciles.' },
  { id: 'piege-5', chapitre: 'ch14',
    piege: 'Utiliser l\'IMC classique chez le sujet âgé',
    reponse: 'L\'IMC est moins fiable chez le sujet âgé (perte de masse maigre, tassement vertébral). L\'albumine (< 35 g/L = dénutrition) et le MNA sont plus fables. IMC < 21 = alerte nutritionnelle (pas 18.5 comme chez l\'adulte jeune).',
    conseil: 'Ne pas se fier uniquement à l\'IMC. Toujours citer albumine + MNA + perte de poids.' },
  { id: 'piege-6', chapitre: 'ch17',
    piege: 'Confondre sédation et euthanasie',
    reponse: 'La sédation terminale (loi Claeys-Leonetti 2016) = soulager la souffrance par des médicaments qui diminuent la conscience, avec pour effet secondaire potentiel d\'abréger la vie. L\'euthanasie = acte intentionnel de donner la mort. En France, la sédation est LÉGALE, l\'euthanasie est INTERDITE.',
    conseil: 'Toujours distinguer intention (soulager vs tuer). La loi Leonetti autorise la sédation profonde et continue.' },
  { id: 'piege-7', chapitre: 'ch6',
    piege: 'Attendre une fracture pour traiter l\'ostéoporose',
    reponse: 'L\'ostéoporose doit être traitée AVANT la fracture (prévention primaire). DEXA si facteurs de risque (âge > 70, corticothérapie, fracture antérieure). T-score < -2.5 = traitement. FRAX > seuil = traitement même si T-score > -2.5.',
    conseil: 'Citer le FRAX comme outil de décision = montrer que vous connaissez les recommandations.' },
  { id: 'piege-8', chapitre: 'ch15',
    piege: 'Prescrire des anticholinergiques pour toute incontinence',
    reponse: 'Les anticholinergiques ne sont efficaces QUE sur l\'incontinence par hyperactivité vésicale (urge-incontinence). Ils sont INEFFICACES sur l\'incontinence d\'effort (traitement = rééducation périnéale/chirurgie). Ils sont DANGEREUX chez le sujet âgé (confusion, constipation, rétention).',
    conseil: 'Toujours préciser le TYPE d\'incontinence avant de prescrire. Rééducation périnéale = 1ère ligne pour effort.' },
  { id: 'piege-9', chapitre: 'ch3',
    piege: 'Évaluer l\'autonomie avec le MMS seul',
    reponse: 'Le MMS évalue la COGNITION, pas l\'AUTONOMIE. Un patient peut avoir un MMS normal et être dépendant (arthrose sévère). L\'autonomie s\'évalue avec ADL (Katz) pour les AVD de base et IADL (Lawton) pour les AVD instrumentales.',
    conseil: 'MMS + ADL + IADL = le trio de base de l\'évaluation gériatrique. Ne jamais citer un sans les autres.' },
  { id: 'piege-10', chapitre: 'ch10',
    piege: 'Diagnostiquer une dépression sur les seuls symptômes somatiques',
    reponse: 'Chez le sujet âgé, la dépression se manifeste souvent par des plaintes SOMATIQUES (douleurs, fatigue, troubles digestifs) plutôt que par la tristesse. Les critères DSM-5 excluent les symptômes somatiques liés à une maladie médicale. Utiliser la GDS-15 (exclut les symptômes somatiques).',
    conseil: 'GDS-15 > 11 = dépression même sans plainte de tristesse. La plainte somatique inexpliquée = chercher une dépression.' }
];
