// Protocoles de soins infirmiers — Procédures techniques
const PROTOCOLES_SOINS = [
  { id: 'ps-1', soin: 'Injection sous-cutanée (insuline, HBPM)', technique: '1. Choisir site: abdomen (2cm du nombril), cuisse, bras. 2. Désinfecter. 3. Pincer la peau. 4. Injecter à 45° ou 90° selon aiguille. 5. Ne pas aspirer (HBPM). 6. Retirer aiguille, appuyer sans masser. 7. Alterner les sites.',
    surveillance: 'Hématome au site, glycémie (insuline), signes d\'héparinisation (saignements)',
    pieges: 'Ne pas masser après injection HBPM. Ne pas utiliser même site consécutivement.' },
  { id: 'ps-2', soin: 'Pose de sonde urinaire', technique: '1. Position décubitus. 2. Désinfection périnéale. 3. Lubrification sonde. 4. Insertion douce (15-20cm femme, 20-25cm homme). 5. Gonfler ballonnet (10mL eau stérile). 6. Raccorder poche. 7. Fixer à la cuisse.',
    surveillance: 'Diurèse, coloration urines, signes infection, état méat urinaire',
    pieges: 'Ne pas forcer si résistance (blocage prostatique → avis uro). Utiliser CH16-18.' },
  { id: 'ps-3', soin: 'Perfusion intraveineuse', technique: '1. Choisir veine (dos de la main, avant-bras). 2. Garrot. 3. Désinfection. 4. Ponction à 15-30°. 5. Vérifier retour veineux. 6. Fixer aiguille. 7. Raccorder tubulure. 8. Régler débit.',
    surveillance: 'Site d\'injection (phlébite, infiltration), débit, constantes, bilan hydrique',
    pieges: 'Ne pas utiliser bras côté mastectomie. Changer site tous les 72h.' },
  { id: 'ps-4', soin: 'Administration de morphine SC', technique: '1. Vérifier ordonnance et identité patient. 2. Préparer seringue (concentration selon protocole). 3. Choisir site SC (abdomen, cuisse). 4. Désinfection. 5. Injection SC. 6. Surveillance conscience et respiration H1.',
    surveillance: 'Conscience (GCS), FR (< 12 = alarme), SpO2, douleur (EVA), nausées, constipation',
    pieges: 'Avoir naloxone 0.4mg à portée. Si FR < 10: naloxone 0.4mg IV.' },
  { id: 'ps-5', soin: 'Change de position anti-escarre', technique: '1. Identifier points d\'appui (sacrum, talons, trochanters). 2. Positionner coussin/oreiller. 3. Changer toutes les 2 heures. 4. Position 30° latérale (pas 90°). 5. Surveiller peau à chaque change.',
    surveillance: 'État cutané (rougeur, induration, ulcération), points d\'appui, confort',
    pieges: 'Position 30° pas 90° (90° = cisaillement). Ne jamais laisser sur le sacrum > 2h.' },
  { id: 'ps-6', soin: 'Sonde naso-gastrique (SNG)', technique: '1. Mesurer distance (nez → oreil → xiphoïde). 2. Lubrifier sonde. 3. Insertion par narine vers l\'arrière-gorge. 4. Demander de déglutir. 5. Vérifier position (pH < 5, Rx). 6. Fixer au nez.',
    surveillance: 'pH aspirat, débit, signes d\'inhalation, état nez, nutrition',
    pieges: 'Toujours vérifier position AVANT nutrition. Rx si doute. Ne jamais forcer.' },
  { id: 'ps-7', soin: 'Oxygénothérapie', technique: '1. Vérifier SpO2 (cible 92-96% sauf BPCO 88-92%). 2. Choix dispositif: lunettes 1-6L/min, masque 6-10L/min, masque haute concentration > 10L/min. 3. Installer. 4. Surveiller SpO2 toutes les 4h.',
    surveillance: 'SpO2, FR, conscience, sécheresse nasale, cutanée CO2 si BPCO',
    pieges: 'BPCO: O2 lentules 2-4L/min (cible 88-92%). O2 haut débit = risque hypercapnie.' },
  { id: 'ps-8', soin: 'Pansement d\'escarre', technique: '1. Nettoyer sérum physiologique. 2. Évaluer taille et profondeur. 3. Choisir pansement: hydrocolloïde (stade I-II), hydrocellulaire (stade III-IV), alginate (exsudat). 4. Appliquer. 5. Fixer. 6. Noter évolution.',
    surveillance: 'Taille escarre, fond (granulation, nécrose, fibrine), exsudat, douleur',
    pieges: 'Ne jamais utiliser désinfectant agressif (Bétadine) dans l\'escarre. Sérum physiologique uniquement.' }
];
