// Questions vives — Sujets controversés et fréquents à l'examen EVC
const QUESTIONS_VIVES = [
  { id: 'qv-1', theme: 'Dénutrition', question: 'Faut-il nourrir de force un patient dément qui ne mange plus ?', reponse: 'Non. La nutrition forcée aggrave l\'agitation et les risques d\'inhalation. L\'approche est d\'offrir des repas adaptés, enrichis, fractionnés. La nutrition entérale (PEG) n\'améliore pas la qualité de vie ni la survie dans la démence avancée (recommandations HAS). L\'accompagnement prime sur l\'alimentation artificielle.', source: 'HAS' },
  { id: 'qv-2', theme: 'Contention', question: 'La contention physique est-elle justifiée chez le sujet âgé agité ?', reponse: 'Presque jamais. La contention AGGRAVE la confusion, augmente le risque d\'escarre, de chute (en se levant avec le lit), et de décès. Alternatives : présence humaine, réorientation, traitement de la cause (douleur, infection), environnement calme. La contention n\'est qu\'en dernier recours et pour une durée minimale.', source: 'CNEG' },
  { id: 'qv-3', theme: 'Anticoagulation', question: 'Doit-on anticoaguler un patient de 95 ans en FA ?', reponse: 'Oui, si CHA2DS2-VASc ≥ 2 et pas de contre-indication. L\'âge seul n\'est PAS une contre-indication. Le risque AVC (5-15%/an) dépasse le risque hémorragique sous anticoagulant. Préférer les AOD (apixaban, rivaroxaban) aux AVK chez le sujet âgé (moins d\'interactions, pas de monitoring INR). Adapter dose si DFG < 30.', source: 'HAS' },
  { id: 'qv-4', theme: 'Fin de vie', question: 'Peut-on arrêter une dialyse chez un patient en fin de vie ?', reponse: 'Oui. L\'arrêt de la dialyse est une décision médicale collégiale quand elle devient une obstination déraisonnable. La loi Claeys-Leonetti le permet. Le patient doit être informé (si capable) et une sédation profonde et continue peut être mise en place pour le confort. L\'accompagnement palliatif commence dès la décision.', source: 'Expert' },
  { id: 'qv-5', theme: 'Neuroleptiques', question: 'Peut-on donner un neuroleptique à un patient avec démence à corps de Lewy ?', reponse: 'NON. Les neuroleptiques sont CONTRE-INDIQUÉS dans la DLB. Ils provoquent une hypersensibilité sévère : syndrome malin des neuroleptiques, aggravation extrapyramidale, confusion, coma. Alternatives : inhibiteurs cholinestérasiques (donépézil, rivastigmine), quetiapine à très faible dose si absolument nécessaire.', source: 'CNEG' },
  { id: 'qv-6', theme: 'Chutes', question: 'Faut-il arrêter tous les médicaments après une chute ?', reponse: 'Non, mais il faut les réviser systématiquement. Priorité : arrêter/réduire les BZD, antihypertenseurs (surtout si hypotension orthostatique), anticholinergiques, opioïdes. Ne pas arrêter brutalement les médicaments essentiels (anticoagulants, antiépileptiques). Réduire progressivement et surveiller.', source: 'HAS' },
  { id: 'qv-7', theme: 'Dépistage', question: 'Faut-il dépister systématiquement la démence chez les > 65 ans ?', reponse: 'Non selon la HAS (2008) et l\'USPSTF. Le dépistage systématique n\'a pas montré de bénéfice en population générale. Par contre, le DÉPISTAGE CIBLÉ est recommandé : toute plainte mnésique, tout changement comportemental, toute perte d\'autonomie inexpliquée doit déclencher une évaluation cognitive.', source: 'HAS' },
  { id: 'qv-8', theme: 'Vitamine D', question: 'La Vit D prévient-elle les chutes et les fractures ?', reponse: 'Oui, la supplémentation en Vit D (800-1000 UI/j) réduit le risque de chute de 19% et de fracture de hanche de 18% (méta-analyses). Recommandée chez tout sujet âgé à risque de chute ou d\'ostéoporose. Pas de bénéfice prouvé pour des doses > 1000 UI/j.', source: 'HAS' },
  { id: 'qv-9', theme: 'Dépression', question: 'Les antidépresseurs augmentent-ils le risque de chute ?', reponse: 'Oui. Les ISRS (sertraline, escitalopram) augmentent le risque de chute de 40-60% (hyponatrémie, sédation, syndrome extrapyramidal). Mais la dépression non traitée augmente aussi le risque (inactivité, dénutrition). Il faut traiter mais à dose minimale et surveiller. Mirtazapine = moins de chutes que les ISRS (données limitées).', source: 'Expert' },
  { id: 'qv-10', theme: 'Alzheimer', question: 'Les inhibiteurs de cholinestérasiques sont-ils efficaces ?', reponse: 'Efficacité modeste mais réelle : amélioration de 2-3 points au MMS sur 6-12 mois, stabilisation des AVD, réduction des troubles du comportement. Bénéfice prouvé pour Alzheimer léger à modéré. Pas de bénéfice dans la démence avancée. Effets secondaires : nausées, diarrhée, bradycardie.', source: 'CNEG' },
  { id: 'qv-11', theme: 'Alitement', question: 'Combien de temps un sujet âgé peut-il rester alité sans risque ?', reponse: '48h suffisent pour commencer la fonte musculaire (-1.5% de masse maigre/j). 5 jours = perte de 10% de force musculaire. 10 jours = risque d\'escarre, TVP, dénutrition, confusion. Tout sujet âgé doit être mobilisé dans les 24h suivant une hospitalisation, sauf contre-indication formelle.', source: 'CNEG' },
  { id: 'qv-12', theme: 'Polypharmacie', question: 'À partir de combien de médicaments parle-t-on de polymédication ?', reponse: '≥ 5 médicaments = polymédication (définition consensus). Le risque d\'interaction augmente exponentiellement : 5 médicaments = 50% de risque d\'interaction, 8 médicaments = 100%. La revue médicamenteuse trimestrielle est recommandée. Déprescrire = acte thérapeutique à part entière.', source: 'HAS' }
];
