// Quiz d'urgence — Questions rapides pour gardes et révisions
const QUIZ_URGENCE = [
  { id: 'qu-1', question: 'Seuil de glycémie définissant une hypoglycémie ?', reponse: '< 0.7 g/L (3.9 mmol/L)', categorie: 'urgence', diffculte: 'A' },
  { id: 'qu-2', question: 'Délai max pour la thrombolyse dans l\'AVC ischémique ?', reponse: '4.5 heures (fenêtre thérapeutique)', categorie: 'urgence', diffculte: 'A' },
  { id: 'qu-3', question: 'Que faire EN PREMIER en cas d\'hyperkaliémie avec ECG anormal ?', reponse: 'Gluconate de calcium 10% 10mL IV (protection myocardique)', categorie: 'urgence', diffculte: 'A' },
  { id: 'qu-4', question: 'Quelle limite de correction retenir devant une hyponatrémie chronique ?', reponse: 'Ne pas dépasser 8 mmol/L sur 24 h, avec une cible souvent plus basse chez les patients à haut risque de démyélinisation osmotique et une surveillance biologique rapprochée.', categorie: 'urgence', diffculte: 'A' },
  { id: 'qu-5', question: 'Comment choisir l\'antibiothérapie probabiliste d\'un sepsis chez une personne âgée ?', reponse: 'La débuter rapidement après les prélèvements sans retarder le traitement, puis l\'adapter au foyer suspecté, à la gravité, à l\'écologie locale, aux allergies, au poids et à la fonction rénale. Il n\'existe pas un schéma unique pour tous les sepsis.', categorie: 'urgence', diffculte: 'A' },
  { id: 'qu-6', question: 'SpO2 cible chez un BPCO exacerbé ?', reponse: '88-92% (éviter l\'hypercapnie avec O2 haut débit)', categorie: 'urgence', diffculte: 'A' },
  { id: 'qu-7', question: 'Quel outil clinique est le plus utilisé pour dépister un delirium ?', reponse: 'La CAM (Confusion Assessment Method) : 1 + 2 + (3 ou 4), soit début aigu/fluctuation ET inattention, associés à une pensée désorganisée OU une vigilance altérée.', categorie: 'geriatrie', diffculte: 'A' },
  { id: 'qu-8', question: 'Comment interpréter un MMS inférieur à 24/30 ?', reponse: 'C\'est un signal d\'alerte cognitif, pas un diagnostic à lui seul. Interpréter selon l\'âge, la scolarité, la langue, les déficits sensoriels, l\'état aigu et le retentissement fonctionnel.', categorie: 'geriatrie', diffculte: 'A' },
  { id: 'qu-9', question: 'Critères de Fried de la fragilité ?', reponse: 'Perte poids, Épuisement, Faiblesse, Lenteur, Inactivité. ≥ 3 = fragile.', categorie: 'geriatrie', diffculte: 'A' },
  { id: 'qu-10', question: 'Quel est le principe de première intention devant une douleur chez une personne âgée ?', reponse: 'Caractériser et traiter la cause, choisir une antalgie adaptée au type de douleur, au poids, au foie et au rein, puis réévaluer rapidement efficacité et tolérance. Le paracétamol peut convenir à certaines douleurs nociceptives, à dose individualisée.', categorie: 'geriatrie', diffculte: 'A' },
  { id: 'qu-11', question: 'Quelle conduite tenir après une chute sous anticoagulant avec traumatisme crânien possible ?', reponse: 'Évaluer sans délai les signes neurologiques et la cinétique, vérifier le traitement anticoagulant et appliquer le protocole de traumatisme crânien, avec indication large de scanner cérébral si impact crânien avéré ou incertain.', categorie: 'urgence', diffculte: 'A' },
  { id: 'qu-12', question: 'Combien de points au Tinetti pour un risque élevé de chute ?', reponse: '< 19 = risque élevé. 19-24 = modéré. ≥ 25 = faible.', categorie: 'geriatrie', diffculte: 'A' },
  { id: 'qu-13', question: 'Quelle échelle brève utiliser pour une douleur aiguë chez un patient non communicant ?', reponse: 'ALGOPLUS : 5 items binaires (visage, regard, plaintes, corps, comportements), avec un seuil validé à 2/5.', categorie: 'geriatrie', diffculte: 'A' },
  { id: 'qu-14', question: 'Comment raisonner l\'usage d\'un diurétique IV devant un OAP ?', reponse: 'Confirmer la congestion et la gravité, tenir compte du traitement diurétique habituel, de la pression artérielle et de la fonction rénale, puis surveiller diurèse, ionogramme et réponse clinique. La dose n\'est pas universelle.', categorie: 'urgence', diffculte: 'A' },
  { id: 'qu-15', question: 'Quels antihypertenseurs rechercher en priorité dans une chute avec hypotension orthostatique ?', reponse: 'Revoir l\'ensemble du traitement ; diurétiques, alpha-bloquants et vasodilatateurs peuvent contribuer selon le terrain. La décision repose sur les mesures couchée/debout et le rapport bénéfice-risque individuel.', categorie: 'geriatrie', diffculte: 'A' },
  { id: 'qu-16', question: 'L\'albuminémie suffit-elle à diagnostiquer une dénutrition ?', reponse: 'Non. Le diagnostic repose sur des critères phénotypiques et étiologiques ; l\'albuminémie aide surtout à apprécier la gravité et doit être interprétée avec l\'inflammation, l\'hydratation et les comorbidités.', categorie: 'geriatrie', diffculte: 'A' },
  { id: 'qu-17', question: 'Quelles sont les premières priorités devant un sepsis ?', reponse: 'Évaluer ABC et la perfusion, prélever lactate et hémocultures sans retarder l\'antibiothérapie, débuter rapidement un traitement adapté au foyer, réévaluer prudemment le remplissage et organiser la surveillance rapprochée.', categorie: 'urgence', diffculte: 'A' },
  { id: 'qu-18', question: 'Loi encadrant la fin de vie en France ?', reponse: 'Loi Claeys-Leonetti (2016). Interdit l\'obstination déraisonnable. Autorise la sédation profonde et continue.', categorie: 'ethique', diffculte: 'A' },
  { id: 'qu-19', question: 'Seuil MNA pour la dénutrition ?', reponse: '< 17 = dénutrition. 17-23.5 = risque de dénutrition. ≥ 24 = normal.', categorie: 'geriatrie', diffculte: 'A' },
  { id: 'qu-20', question: 'Existe-t-il un médicament contre-indiqué du seul fait de l\'âge ?', reponse: 'Non. L\'âge seul ne suffit pas : vérifier indication, terrain, fonction rénale et hépatique, interactions et alternatives. Les AINS, benzodiazépines et anticholinergiques exigent une vigilance particulière mais ne se résument pas à une interdiction universelle.', categorie: 'geriatrie', diffculte: 'A' }
];
