// Scores d'urgence — Quick reference pour gardes
const SCORES_URGENCE = [
  { id: 'su-1', nom: 'SOFA (Sepsis)', items: 'Respiration (PaO2/FiO2) · Coagulation (Plaquettes) · Foie (Bilirubine) · Cardio (Hypotenseurs) · Neuro (GCS) · Rénal (Diurèse/Cr)',
    seuils: '0 = normal · 1-2 = défaillance légère · 3-5 = défaillance modérée · 6-10 = défaillance sévère · >10 = critique',
    utilisation: 'Évaluation défaillance d\'organe dans le sepsis. Augmentation ≥2 points = détérioration.' },
  { id: 'su-2', nom: 'qSOFA (Sepsis rapide)', items: 'FR ≥ 22/min · PAS ≤ 100 mmHg · Altération conscience (GCS < 15)',
    seuils: '≥ 2 = risque sepsis sévère → évaluation SOFA complète',
    utilisation: 'Dépistage rapide au lit du patient. Pas besoin de labo.' },
  { id: 'su-3', nom: 'NIHSS (AVC)', items: '15 items : conscience, regard, champs visuels, paralysie faciale, motricité bras/jambe, ataxie, sensibilité, langage, dysarthrie, extinction/négligence',
    seuils: '0 = pas d\'AVC · 1-4 = mineur · 5-15 = modéré · 16-20 = sévère · 21-42 = très sévère',
    utilisation: 'Évaluation gravité AVC et décision thrombolyse/thrombectomie.' },
  { id: 'su-4', nom: 'GRACE (SCA)', items: 'Âge · FC · PAS · Créatinine · Killip · Arrêt cardiaque · ST déviations · Enzymes cardiaques',
    seuils: '< 108 très faible · 109-140 faible · 141-166 modéré · > 185 très haut risque',
    utilisation: 'Pronostic syndrome coronaire aigu. Décide stratégie invasive.' },
  { id: 'su-5', nom: 'Wells (EP)', items: 'Clinique EP (3) · Immobilisation (1.5) · Chirurgie récente (1.5) · Tachycardie (1.5) · Signes TVP (3) · Hémoptysie (1) · Autre diagnostic (-3)',
    seuils: '< 4 faible probabilité · ≥ 4 haute probabilité',
    utilisation: 'Probabilité embolie pulmonaire avant imagerie.' },
  { id: 'su-6', nom: 'Glasgow (Coma)', items: 'Ouverture yeux (1-4) · Réponse verbale (1-5) · Réponse motrice (1-6)',
    seuils: '15 = normal · 13-14 = léger · 9-12 = modéré · 3-8 = sévère (intubation)',
    utilisation: 'Évaluation conscience. < 8 = intubation.' },
  { id: 'su-7', nom: 'NEWS2 (Détresse)', items: 'FR · SpO2 · Temp · PAS · FC · Conscience · O2 supplémentaire',
    seuils: '0-4 faible · 5-6 modéré (réévaluer H1) · ≥ 7 critique (urgence)',
    utilisation: 'Détection précoce détérioration. Standard NHS.' },
  { id: 'su-8', nom: 'HAS-BLED (Saignement)', items: 'HTA · Anomalie rénale/hépatique · AVC · Saignement · Labile INR · Âge > 65 · Médicaments/Alcool',
    seuils: '0-2 faible risque · 3-4 modéré · ≥ 5 haut risque',
    utilisation: 'Risque hémorragique sous anticoagulation FA.' },
  { id: 'su-9', nom: 'CHA2DS2-VASc (FA)', items: 'IC · HTA · Âge ≥ 75 (2) · DM2 · AVC (2) · Vasculaire · Âge 65-74 · Femme',
    seuils: '0 = pas d\'anticoagulation · 1 = considérer · ≥ 2 = anticoagulation obligatoire',
    utilisation: 'Décision anticoagulation dans la fibrillation atriale.' },
  { id: 'su-10', nom: 'Killip (IC aiguë)', items: 'Examen clinique pulmonaire et hémodynamique',
    seuils: 'I = pas de signes · II = crépitants basaux · III = OAP · IV = choc cardiogénique',
    utilisation: 'Classification insuffisance cardiaque aiguë post-IDM.' }
];
