// Situations EHPAD — Conduites à tenir en établissement
const SITUATIONS_EHPAD = [
  { id: 'se-1', situation: 'Résident qui erre la nuit', conduite: '1. Vérifier douleur (ECPA). 2. Vérifier infection (T°, ECBU). 3. Lumière veilleuse dans le couloir. 4. Porte chambre ouverte. 5. Activité diurne (fatigue le soir). 6. Si nécessaire: mélatonine 2mg. 7. Éviter BZD.' },
  { id: 'se-2', situation: 'Résident qui refuse de manger', conduite: '1. Rechercher cause (douleur, dépression, infection, dentition). 2. Enrichir les plats. 3. Fractionner (6 repas/j). 4. Repas en commun (stimulation sociale). 5. Si refus > 3 jours: CNO. 6. Si refus persistant: discussion équipe + famille.' },
  { id: 'se-3', situation: 'Résident qui tombe en répétition', conduite: '1. Déclarer chaque chute. 2. Réévaluer Tinetti trimestriellement. 3. Révision médicamenteuse. 4. Adaptation chambre (lit bas, tapis antidérapant, barres). 5. Rééducation 3x/sem. 6. Vit D 800UI. 7. Si malgré tout: matelas au sol, alarme.' },
  { id: 'se-4', situation: 'Résident agité qui frappe', conduite: '1. Rechercher douleur (ECPA). 2. Rechercher infection (T°, ECBU). 3. Environnement calme. 4. Approche non médicamenteuse (distraction, contact). 5. Si nécessaire: quétiapine 25mg. 6. Éviter contention. 7. Noter dans le dossier.' },
  { id: 'se-5', situation: 'Famille mécontente des soins', conduite: '1. Écouter sans interrompre. 2. Reconnaître le mécontentement. 3. Expliquer le projet de soins. 4. Proposer réunion avec l\'équipe. 5. Documenter les échanges. 6. Si conflit persistant: médiateur.' },
  { id: 'se-6', situation: 'Résident en fin de vie', conduite: '1. Projet de soins palliatifs. 2. Douleur: morphine SC. 3. Soins de bouche H2. 4. Hydratation cutanée. 5. Pas de nutrition artificielle. 6. Accompagnement famille. 7. Si sédation nécessaire: midazolam SC. 8. Chambre individuelle si possible.' },
  { id: 'se-7', situation: 'Épidémie de gastro-entérite', conduite: '1. Isolement des cas. 2. Lavage mains savon (pas hydroalcoolique pour Norovirus). 3. Désinfection surfaces (eau de Javel). 4. Hydratation des malades. 5. Signalement au médecin coordonnateur. 6. Restriction visiteurs si nécessaire.' },
  { id: 'se-8', situation: 'Résident qui perd son autonomie', conduite: '1. Réévaluation ADL/IADL. 2. Adapter le projet de soins. 3. Augmenter les aides. 4. Rééducation fonctionnelle. 5. Discussion avec la famille. 6. Si dépendance sévère: passage en USP (unité de soins prolongés).' }
];
