const CACHE_NAME = 'geriatrie-v146';
const CORE = [
  './',
  './index.html',
  './style.css',
  './app.js',
  './brainfeed.js',
  './quiz.js',
  './dashboard.js',
  './appsearch.js',
  './annales.js',
  './annales-expanded.js',
  "./annales-v2.js",
  './has-reco.js',
  './has-expanded.js',
  './flashcards-batch-A.js',
  './flashcards-batch-B.js',
  './flashcards-batch-C.js',
  './flashcards-memos.js',
  './flashcards-expanded.js',
  './data.js',
  './figures.js',
  './interactive-figures.js',
  './synthesis.js',
  './concepts.js',
  './flashcards.js',
  './graph.js',
  './fiches-garde.js',
  './protocoles-urgence.js',
  './protocoles-complets.js',
  './situations-evc.js',
  './cas-interactifs.js',
  './epreuves-externes.js',
  './evc-coach.js',
  './scores-geriatrie.js',
  './formules-geriatrie.js',
  './pharmaco-geriatrie.js',
  './pieges-exam.js',
  './memos-rapides.js',
  './quiz-urgence.js',
  './ressources-evc.js',
  './checklist-garde.js',
  './guide-accompagnant.js',
  './figures-index.js',
  './annales-archive.js',
  './synthesis-expanded.js',
  './concepts-expanded.js',
  './clinical-reference.js',
  './items-evc.js',
  './interactions-critiques.js',
  './mega-cases.js',
  './examens-guide.js',
  './vocabulaire-medical.js',
  './tableaux-comparatifs.js',
  './abbreviations.js',
  './doses-urgence.js',
  './faq-geriatrie.js',
  './situations-garde.js',
  './cas-evc-2024.js',
  './protocoles-reanimation.js',
  './aide-memoire-rapide.js',
  './cas-evc-2023.js',
  './mini-dossiers.js',
  './checklist-sortie.js',
  './phrases-examen.js',
  './cas-evc-2020-2022.js',
  './pieges-examen-evc.js',
  './memos-visuels.js',
  './effets-indesirables.js',
  './outils-evaluation.js',
  './tableau-bord-evc.js',
  './conduites-a-tenir.js',
  './resumes-chapitres.js',
  './guides-ehpad.js',
  './cas-evc-2018-2019.js',
  './cas-evc-2015-2017.js',
  './cas-evc-2010-2014.js',
  './protocoles-cognitif.js',
  './guides-dermatologie.js',
  './interpretation-imagerie.js',
  './cas-ethiques.js',
  './guides-endocrinologie.js',
  './protocoles-palliatif-avances.js',
  './guides-physiotherapie.js',
  './protocoles-readaptation.js',
  './techniques-examen.js',
  './protocoles-legislation.js',
  './protocoles-qualite.js',
  './guides-geriatrie-quotidien.js',
  './medicaments-urgence.js',
  './protocoles-formation.js',
  './scores-avances.js',
  './guides-medecine-legal.js',
  './guides-aidants.js',
  './interpretation-biologie.js',
  './guides-oncologie.js',
  './guides-infectiologie.js',
  './guides-hepatologie.js',
  './guides-urologie.js',
  './guides-ssr.js',
  './cas-complexes.js',
  './infections-reference.js',
  './checklist-admission.js',
  './situations-ehpad.js',
  './protocoles-kine.js',
  './guides-diabetologie.js',
  './guides-cardiologie.js',
  './pharmaco-complete.js',
  './protocoles-rcp.js',
  './guides-rhumatologie.js',
  './guides-pneumologie.js',
  './guides-neurologie.js',
  './cadre-juridique.js',
  './chiffres-cles-medicaux.js',
  './guides-consultation.js',
  './biologie-reference.js',
  './syndromes-geriatriques.js',
  './imagerie-reference.js',
  './examens-ecg.js',
  './guides-pratiques.js',
  './paroles-experts.js',
  './questions-vives.js',
  './scores-urgence.js',
  './demences-comparatif.js',
  './aide-memoire-evc.js',
  './synthesis-rapide.js',
  './guides-dentaire.js',
  './guides-geriatrie-chirurgicale.js',
  './guides-geriatrie-long-sejour.js',
  './guides-geriatrie-sociale.js',
  './guides-ophtalmologie.js',
  './guides-plaies.js',
  './guides-prevention-infection.js',
  './guides-recherche.js',
  './guides-sommeil.js',
  './guides-telesante.js',
  './mega-flashcards-2.js',
  './mega-flashcards-3.js',
  './mega-flashcards.js',
  './sujets-evc-2007-2009.js',
  './sujets-evc-2010-2012.js',
  './sujets-evc-2013-2015.js',
  './sujets-evc-2016-2018.js',
  './sujets-evc-2019-2021.js',
  './sujets-evc-complets.js',
  "./sujets-evc-detailles.js",
  "./sujets-evc-2004-2006.js",
  "./sujets-evc-supp.js",
  "./mega-flashcards-4.js",
  "./sujets-evc-2001-2003.js",
  "./mega-flashcards-5.js",
  "./mega-flashcards-6.js",
  "./mega-flashcards-7.js",
  "./mega-flashcards-8.js",
  "./mega-flashcards-9.js",
  "./mega-flashcards-10.js",
  "./sujets-evc-extra.js",
  "./guides-geriatrie-palliative-avancee.js",
  "./sujets-evc-1998-2000.js",
  "./sujets-evc-classiques.js",
  "./guides-geriatrie-nutrition-avancee.js",
  "./sujets-evc-fin.js",
  "./guides-geriatrie-cardio-avancee.js",
  "./sujets-evc-1995-1997.js",
  "./sujets-evc-items.js",
  './erreurs-journal.js',
  './manifest.json',
  './icons/icon-192.png',
  './icons/icon-512.png'
];

self.addEventListener('install', e => {
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  // Always fetch from network first for HTML/JS/CSS
  e.respondWith(
    fetch(e.request).then(resp => {
      if (resp.status === 200) {
        const clone = resp.clone();
        caches.open(CACHE_NAME).then(c => c.put(e.request, clone));
      }
      return resp;
    }).catch(() => caches.match(e.request))
  );
});
