// Synthèse rapide — Points clés par chapitre (version compacte)
const SYNTHESIS_RAPIDE = [
  { id: 'sr-1', chapitre: 'ch1', titre: 'Vieillissement en 5 points',
    points: ['Réserve fonctionnelle diminue (25-30% entre 30 et 80 ans)', 'Télomères raccourcissent → sénescence cellulaire', 'Inflammaging = inflammation chronique de bas grade', 'Immuno-sénescence = infections + cancers + vaccins moins efficaces', 'Le vieillissement ≠ maladie (physiologique vs pathologique)'] },
  { id: 'sr-2', chapitre: 'ch2', titre: 'Raisonnement gériatrique en 5 points',
    points: ['EGM = évaluation multidimensionnelle (cognition, humeur, autonomie, nutrition, chutes)', 'GDS = grille isolement social (1-7)', 'Polymorbidité = interactions médicamenteuses fréquentes', 'Approche gériatrique = équipe pluridisciplinaire', 'Objectif = maintien à domicile si possible'] },
  { id: 'sr-3', chapitre: 'ch3', titre: 'Autonomie en 5 points',
    points: ['ADL (Katz) = 6 AVD de base (baignade, habillage, toilette, transferts, continence, alimentation)', 'IADL (Lawton) = 8 AVD instrumentales (courses, cuisine, ménage, lessive, tel, transport, médicaments, argent)', 'IADL perdues AVANT ADL = signe précoce', 'Autonomie ≠ capacité physique seule (environnement compte)', 'Évaluer à chaque consultation'] },
  { id: 'sr-4', chapitre: 'ch4', titre: 'Éthique en 5 points',
    points: ['Autonomie du patient = principe premier', 'Loi Kouchner 2002 = consentement éclairé, personne de confiance', 'Loi Leonetti 2005 = interdiction obstination déraisonnable', 'Loi Claeys-Leonetti 2016 = sédation profonde et continue', 'Directives anticipées = contraignantes si rédigées correctement'] },
  { id: 'sr-5', chapitre: 'ch5', titre: 'Sensoriel en 5 points',
    points: ['Presbyacousie = perte fréquences aiguës (4-8 kHz) dès 50 ans', 'Presbytie = perte accommodation cristallin dès 45 ans', 'Troubles sensoriels = chutes + isolement + dépression + déclin cognitif', 'Appareillage auditif = améliore cognition et social', 'Bilan ophtalmo/audiométrique annuel après 70 ans'] },
  { id: 'sr-6', chapitre: 'ch6', titre: 'Ostéoporose en 5 points',
    points: ['T-score < -2.5 = ostéoporose (DEXA)', 'FRAX = score de risque fracturaire à 10 ans', 'Fracture ostéoporotique = 20% mortalité à 1 an (col fémoral)', 'Traitement : Vit D 800UI + Ca 1.2g + biphosphonate', 'Prévention : activité physique + arrêt tabac + éviter chutes'] },
  { id: 'sr-7', chapitre: 'ch7', titre: 'Arthrose en 5 points',
    points: ['Maladie mécanique du cartilage articulaire', 'Facteurs : âge, obésité, surmenage, génétique', 'Douleur mécanique + raideur matinale < 30 min', 'Rx : pincement articulaire, ostéophytes', 'Traitement : paracétamol + kiné + perte poids + prothèse si échec'] },
  { id: 'sr-8', chapitre: 'ch8', titre: 'Douleur en 5 points',
    points: ['Évaluation : EVA si communicant, ECPA si non communicant', 'Paracétamol = 1ère ligne (max 3g/j)', 'Éviter AINS chez sujet âgé', 'Tramadol = 2ème ligne (réduire dose si > 75 ans)', 'Douleur chronique = impact sur cognition, sommeil, humeur'] },
  { id: 'sr-9', chapitre: 'ch9', titre: 'Cognition en 5 points',
    points: ['MMS < 24 = trouble cognitif (corriger âge/scolarité)', 'GDS 3-4 = MCI (trouble cognitif léger)', 'Alzheimer = 70% des démences (déclin mnésique progressif)', 'Corps de Lewy = fluctuations + hallucinations + parkinson', 'Contre-indiquer neuroleptiques si DLB (hypersensibilité)'] },
  { id: 'sr-10', chapitre: 'ch10', titre: 'Dépression en 5 points',
    points: ['GDS-15 > 11 = dépression majeure', 'Présentation atypique : plaintes somatiques, pas de tristesse', 'Pseudodémence = dépression mimant une démence (réversible)', 'ISRS = 1ère ligne (sertraline 50mg)', 'Mirtazapine si insomnie + anorexie'] },
  { id: 'sr-11', chapitre: 'ch11', titre: 'Confusion en 5 points',
    points: ['CAM = diagnostic confusion aiguë (début aigu + inattention OU 1+3+4)', 'Causes : infection, médicaments, métabolique, douleur', 'Traitement : cause + halopéridol 0.5mg si agitation', 'Éviter contention (aggrave)', 'Confusion ≠ démence (réversible vs chronique)'] },
  { id: 'sr-12', chapitre: 'ch12', titre: 'Chutes en 5 points',
    points: ['Tinetti < 24 = risque élevé', '50% des chutes = cause médicamenteuse', 'Révision médicamenteuse systématique', 'Rééducation équilibre + Vit D 800UI', 'Adaptation domicile (éclairage, barres, tapis)'] },
  { id: 'sr-13', chapitre: 'ch13', titre: 'Alitement/Escarres en 5 points',
    points: ['Braden < 14 = risque élevé escarre', 'Changement position H2 + matelas anti-escarres', 'Albumine < 35 = facteur de risque', '4 stades : érythème → perte derme → perte totale → os/tendon', 'Conséquences alitement : fonte musculaire, dénutrition, TVP, confusion'] },
  { id: 'sr-14', chapitre: 'ch14', titre: 'Nutrition en 5 points',
    points: ['MNA < 17 = dénutrition', 'Perte > 5% en 1 mois = dénutrition', 'Albumine < 35 = dénutrition (marqueur inflammatoire aussi)', 'Protéines 1.0-1.2 g/kg/j (1.2-1.5 si stress)', 'Enrichissement + CNO + si échec : nutrition entérale'] },
  { id: 'sr-15', chapitre: 'ch15', titre: 'Incontinence en 5 points',
    points: ['3 types : effort (sphincter), urgence (vésicale), mixte', 'Effort = rééducation périnéale 1ère ligne', 'Urgence = anticholinergiques (solifénacine)', 'Éviter anticholinergiques si sujet âgé (confusion)', 'Calendrier mictionnel = outil diagnostique essentiel'] },
  { id: 'sr-16', chapitre: 'ch16', titre: 'Prescription en 5 points',
    points: ['Critères de Beers = médicaments inappropriés', 'START/STOP = prescrire/déprescrire', 'Cascade iatrogénique : A → effet indésirable → B → effet → C…', '≥ 5 médicaments = polymédication = risque', 'Revue médicamenteuse trimestrielle'] },
  { id: 'sr-17', chapitre: 'ch17', titre: 'Palliatif en 5 points',
    points: ['Loi Claeys-Leonetti 2016 = sédation profonde et continue', 'Morphine SC = traitement douleur en fin de vie', 'Obstination déraisonnable = interdite', 'Soins de bouche + hydratation cutanée + accompagnement', 'Trajectoire cancer = déclin progressif vs dégénérative = en dents de scie'] },
  { id: 'sr-18', chapitre: 'ch18', titre: 'Mini-dossiers en 5 points',
    points: ['Anamnèse → Examen → Hypothèses → Bilan → Diagnostic → Plan', 'Toujours commencer par les données (pas le diagnostic)', 'Argumenter chaque hypothèse (pour/contre)', 'Citer les échelles pertinentes (MMS, ADL, Tinetti…)', 'Plan de sortie = toujours prévoir (domicile ? SSR ? EHPAD ?)'] },
  { id: 'sr-19', chapitre: 'ch19', titre: 'Key Features en 5 points',
    points: ['Identifier le problème principal (pas tous les problèmes)', 'Structurer : Données → Hypothèses → Stratégie → Intervention', 'Prioriser : urgence > confort > prévention', 'Justifier chaque décision', 'Connaître les pièges classiques (voir liste pièges)'] },
  { id: 'sr-20', chapitre: 'ch20', titre: 'Questions isolées en 5 points',
    points: ['Connaître TOUS les ITEMS du programme', 'Chaque ITEM = question potentielle', 'Réponse courte + argumentée (pas de blabla)', 'Citer les scores et seuils exacts', 'Relier au contexte gériatrique (pas de réponse générique)'] }
];
