// Vocabulaire médical français-anglais pour étudiants
const VOCABULAIRE_MEDICAL = [
  { fr: 'Confusion aiguë', en: 'Delirium', definition: 'Trouble aigu et fluctuant de l\'attention et de la conscience' },
  { fr: 'Démence', en: 'Dementia', definition: 'Déclin cognitif progressif et chronique affectant les activités quotidiennes' },
  { fr: 'Dénutrition', en: 'Malnutrition', definition: 'État résultant d\'un apport nutritionnel insuffisant ou déséquilibré' },
  { fr: 'Fragilité', en: 'Frailty', definition: 'Syndrome gériatrique de diminution des réserves physiologiques' },
  { fr: 'Escarrre', en: 'Pressure ulcer/injury', definition: 'Lésion cutanée liée à une pression prolongée sur les tissus' },
  { fr: 'Chute', en: 'Fall', definition: 'Événement involontaire conduisant au sol' },
  { fr: 'Incontinence', en: 'Incontinence', definition: 'Perte involontaire d\'urine ou de selles' },
  { fr: 'Polymédication', en: 'Polypharmacy', definition: 'Utilisation simultanée de ≥5 médicaments' },
  { fr: 'Iatrogénie', en: 'Iatrogenesis', definition: 'Effet indésirable dû à un acte médical ou médicamenteux' },
  { fr: 'Sarcopénie', en: 'Sarcopenia', definition: 'Perte progressive de masse et de force musculaire liée à l\'âge' },
  { fr: 'Ostéoporose', en: 'Osteoporosis', definition: 'Maladie osseuse caractérisée par une diminution de la densité osseuse' },
  { fr: 'Presbyacousie', en: 'Presbycusis', definition: 'Perte auditive liée à l\'âge, touchant les fréquences aiguës' },
  { fr: 'Presbytie', en: 'Presbyopia', definition: 'Perte de l\'accommodation du cristallin liée à l\'âge' },
  { fr: 'Syndrome confusionnel', en: 'Delirium syndrome', definition: 'État confusionnel aigu, fluctuant, avec inattention' },
  { fr: 'Pseudodémence', en: 'Pseudodementia', definition: 'Troubles cognitifs réversibles causés par la dépression' },
  { fr: 'Cascade iatrogénique', en: 'Prescribing cascade', definition: 'Enchaînement: médicament → effet indésirable → nouveau médicament' },
  { fr: 'Rééducation périnéale', en: 'Pelvic floor rehabilitation', definition: 'Exercices pour renforcer le plancher pelvien (incontinence d\'effort)' },
  { fr: 'Nutrition entérale', en: 'Enteral nutrition', definition: 'Nutrition par sonde gastrique (SNG/PEG)' },
  { fr: 'Soins palliatifs', en: 'Palliative care', definition: 'Soins centrés sur le confort en fin de vie' },
  { fr: 'Directive anticipée', en: 'Advance directive', description: 'Document exprimant les volontés du patient pour sa fin de vie' },
  { fr: 'Personne de confiance', en: 'Trusted person', definition: 'Personne désignée pour accompagner le patient dans ses décisions médicales' },
  { fr: 'Évaluation gériatrique', en: 'Comprehensive geriatric assessment', definition: 'Évaluation multidimensionnelle (cognition, humeur, autonomie, nutrition)' },
  { fr: 'EHPAD', en: 'Nursing home', definition: 'Établissement d\'Hébergement pour Personnes Âgées Dépendantes' },
  { fr: 'SSR', en: 'Rehabilitation center', definition: 'Suite de Rétablissement et de Réadaptation' },
  { fr: 'HAD', en: 'Hospital at home', definition: 'Hospitalisation A Domicile' },
  { fr: 'APA', en: 'Personalized autonomy allowance', definition: 'Allocation Personnalisée d\'Autonomie' },
  { fr: 'GDS', en: 'Geriatric Depression Scale', definition: 'Échelle de dépistage de la dépression chez le sujet âgé' },
  { fr: 'MMS/MMSE', en: 'Mini Mental State Examination', definition: 'Test de dépistage des troubles cognitifs (30 points)' },
  { fr: 'MNA', en: 'Mini Nutritional Assessment', definition: 'Outil de dépistage de la dénutrition (24+ = normal)' },
  { fr: 'ADL/Katz', en: 'Activities of Daily Living', definition: 'Échelle d\'autonomie de base (6 activités)' },
  { fr: 'IADL/Lawton', en: 'Instrumental ADL', definition: 'Échelle d\'autonomie complexe (8 activités)' },
  { fr: 'Braden', en: 'Braden scale', definition: 'Échelle de risque d\'escarre (6 facteurs)' },
  { fr: 'Tinetti', en: 'Tinetti scale', definition: 'Échelle d\'équilibre et marche (prédicteur chutes)' },
  { fr: 'ECPA', en: 'ECPA scale', definition: 'Échelle comportementale de douleur pour sujets âgés non communicants' },
  { fr: 'FRAX', en: 'FRAX tool', definition: 'Outil de calcul du risque fracturaire à 10 ans' },
  { fr: 'DEXA', en: 'DEXA scan', definition: 'Absorptiométrie bi-énergétique (mesure densité osseuse)' },
  { fr: 'SNG', en: 'Nasogastric tube', definition: 'Sonde Naso-Gastrique pour nutrition entérale' },
  { fr: 'PEG', en: 'Percutaneous endoscopic gastrostomy', definition: 'Gastrostomie percutanée pour nutrition entérale prolongée' },
  { fr: 'TVT', en: 'Tension-free vaginal tape', definition: 'Bandelette sous-urétrale pour incontinence d\'effort' },
  { fr: 'HTA', en: 'Hypertension', definition: 'Hypertension Artérielle (PAS ≥ 140 ou PAD ≥ 90)' },
  { fr: 'BPCO', en: 'COPD', definition: 'Broncho-Pneumopathie Chronique Obstructive' },
  { fr: 'DM2', en: 'Type 2 diabetes', definition: 'Diabète de type 2' },
  { fr: 'AVC', en: 'Stroke', definition: 'Accident Vasculaire Cérébral (ischémique ou hémorragique)' },
  { fr: 'FA', en: 'Atrial fibrillation', definition: 'Fibrillation Atriale' },
  { fr: 'IC', en: 'Heart failure', definition: 'Insuffisance Cardiaque' },
  { fr: 'IRA', en: 'Acute kidney injury', definition: 'Insuffisance Rénale Aiguë' },
  { fr: 'EP', en: 'Pulmonary embolism', definition: 'Embolie Pulmonaire' },
  { fr: 'TVP', en: 'Deep vein thrombosis', definition: 'Thrombose Veineuse Profonde' },
  { fr: 'ITU', en: 'Urinary tract infection', definition: 'Infection des Voies Urinaires' },
  { fr: 'DMLA', en: 'Age-related macular degeneration', definition: 'Dégénérescence Maculaire Liée à l\'Âge' },
  { fr: 'DLB', en: 'Dementia with Lewy bodies', definition: 'Démence à Corps de Lewy' }
];
